### PR TITLE
pipe: don't crash on exceptions

### LINKED ISSUE #2619: Pipebackend can cause weird error if misconfigured
$ ../pdns/pdnssec --config-name=pipe --config-dir=. help
Error: Command '' cannot be executed: No such file or directory

pdns-pipe.conf
```
module-dir=./modules
launch=pipe
pipebackend-command=
pipebackend-abi-version=4
```

### PR DESCRIPTION
**Pull request by pieterlexis**
This commit cleans up the PipeBackend code so it handles all exceptions
itself. Be it initialization errors (i.e. "file not found", "command not
executable"), or error during runtime ("data not returned in pipe
format"). When these errors occur, we now recycle the coprocess so the
rest of the nameserver keeps running. This behaviour is similar to e.g.
an unavailable database server.

Also, make the error-message for ArgMap::asNum display the value of the
setting.

Closes #2619

### CODE REVIEW

File: modules/pipebackend/pipebackend.cc [hunk 1]
```diff
@@ -52,10 +52,14 @@ void CoWrapper::launch()
    if(d_cp)
       return;
 
+   if(d_command.size() == 0)
```
Comment (ahupowerdns) [inline modules/pipebackend/pipebackend.cc]: note for next time: d_command.empty() is a better habit. Does not actually matter here, but on some containers it is a lot faster.

**Comment by Habbie** [comment]
LGTM, please rebase and merge.

**Comment by Habbie** [comment]
Travis logs look like yesterday's master brokenness, please rebase again!

**Comment by cmouse** [comment]
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/travis/build/PowerDNS/pdns/docs/html/recursor/settings/scripting.md'>

**Comment by pieterlexis** [comment]
will rebase *again*
