### PR TITLE
rec: Fix validation of denial proofs

### LINKED ISSUE #5861: rec: unexpected SERVFAIL on a nodata answer for a secure domain
- Program: Recursor
 - Issue type: Bug report

### Short description
Signed domain gives SERVFAIL (bogus) answer on the AAAA query where auth says NODATA.

http://dnsviz.net/d/assets.webshopapp.com/dnssec/?rr=28&a=all&ds=all&ta=.&tk=

### Environment
 - Operating system: Debian/stretch
 - Software version: 0.0.1798g0e9a0d5-1pdns.stretch
 - Software source: repo

### Steps to reproduce

1. load pdns-recursor
2. dig AAAA assets.webshopapp.com \@resolver

### Expected behaviour
nodata

### Actual behaviour
servfail

### Other information
```irclog
13:28|   rgacogne: looking
13:31|   rgacogne: I think I have a fix for that this case on a branch
13:31|   rgacogne: let me check
13:32|   rgacogne: yeah, it works fine on my branch
13:32|   rgacogne: I'm not ready to PR it yet, though :-/
13:32|     kaisan: rgacogne: do you want me to file it
13:33|   rgacogne: kaisan: if you don't mind, so I don't forget to PR and merge before rec 4.1.0 :)
```

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Fix DNSSEC validation for:
* denial of wildcards in negative answer
* denial of existence proofs in wildcard expanded positive responses

Fixes #5861.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [x] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsname.cc [hunk 1]
```diff
@@ -253,6 +253,24 @@ void DNSName::makeUsRelative(const DNSName& zone)
...
 
+DNSName DNSName::getCommonLabels(const DNSName& other) const
+{
+  DNSName result;
+
+  const std::vector<std::string> ours = getRawLabels();
+  const std::vector<std::string> others = other.getRawLabels();
+
+  for (size_t pos = 0; ours.size() > pos && others.size() > pos; pos++) {
+    if (ours.at(ours.size() - pos - 1) != others.at(others.size() - pos - 1)) {
```
Comment (mind04) [inline pdns/dnsname.cc]: This compare is case sensitive

Comment (rgacogne) [reply pdns/dnsname.cc]: Nice catch, thanks! I just pushed a fix.
