### PR TITLE
dnsdist: add ability to update webserver credentials

### LINKED ISSUE #7112: Cannot change API key / web password in runtime
Hello!

For security reasons we do key rotation quite often.  But I cannot change API Key using runtime reconfiguration:
```
webserver("10.10.10.1:1234", "somesecret", "apikey")
```

dnsdist returns error:
```
Unable to bind to webserver socket on 10.10.10.1:1234: binding socket to 10.10.10.1:1234: Address already in use> 
```

Any chance to get two function to change API Key / web password without touching webserver?

Thank you!

### PR DESCRIPTION
**Pull request by chbruyand**
### Short description
This PR adds `setWebserverConfig` lua funciton to update webserver credentials and custom headers.

Fix #7112 

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsdist-lua.cc [hunk 1]
```diff
@@ -631,7 +631,8 @@ void setupLuaConfig(bool client)
 	SBind(sock, local);
 	SListen(sock, 5);
 	auto launch=[sock, local, password, apiKey, customHeaders]() {
-	  thread t(dnsdistWebserverThread, sock, local, password, apiKey ? *apiKey : "", customHeaders);
+          setWebserverConfig(password, apiKey, customHeaders);
+          thread t(dnsdistWebserverThread, sock, local);
 	  t.detach();
```
Comment (rgacogne) [inline pdns/dnsdist-lua.cc]: Just a nit but indentation seems off.

File: pdns/dnsdist-console.cc [hunk 2]
```diff
@@ -446,6 +446,7 @@ const std::vector<ConsoleKeyword> g_consoleKeywords{
   { "setUDPMultipleMessagesVectorSize", true, "n", "set the size of the vector passed to recvmmsg() to receive UDP messages. Default to 1 which means that the feature is disabled and recvmsg() is used instead" },
   { "setUDPTimeout", true, "n", "set the maximum time dnsdist will wait for a response from a backend over UDP, in seconds" },
   { "setVerboseHealthChecks", true, "bool", "set whether health check errors will be logged" },
+  { "setWebserverConfig", true, "password [, apiKey [, customHeaders ]]", "Updates webserver configuration" },
```
Comment (pieterlexis) [inline pdns/dnsdist-console.cc]: Perhaps this function should take a table? A user could then update one of the items without updating the others. e.g.

```lua
setWebserverConfig({password: "hello"})
```
```lua
setWebserverConfig({apiKey: "hello2"})
```

Comment (chbruyand) [reply pdns/dnsdist-console.cc]: this means using `setWebserverConfig({apiKey: ""})` to disable apiKey authentication. Is that something we want ? Otherwise I agree.

File: pdns/dnsdist-lua.cc (hunk 1 above)
Comment (chbruyand) [reply pdns/dnsdist-lua.cc]: The file has been partially indented with tabs :/

**Comment by chbruyand** [comment]
I followed pieter's remark and added two basic tests about custom headers

File: pdns/dnsdist-lua.cc [hunk 3]
```diff
@@ -646,6 +648,32 @@ void setupLuaConfig(bool client)
...
+      if (!vars) {
+        return ;
+      }
+      if(vars->count("password")) {
+        const std::string password = boost::get<std::string>(vars->at("password"));
+
+        setWebserverPassword(password);
+      }
+      if(vars->count("apiKey")) {
+        // allows setting apiKey: nil to disable access with it
```
Comment (rgacogne) [inline pdns/dnsdist-lua.cc]: does `nil` really work? It looks like we only test for an empty string?

Comment (chbruyand) [reply pdns/dnsdist-lua.cc]: indeed
