### PR TITLE
be more specific about trailing dot handling, fixes #5673

### LINKED ISSUE #5673: Segfault in pdnsutil check-zone
Sample database using postgresql backend:
```
insert into domains (name, type) values ('example.com', 'NATIVE'); 
insert into records (domain_id, type, name, content) values (currval('domains_id_seq'), 'SOA', 'example.com', 'ns1.example.com admin.example.com 2017010100 3600 600 1209600 3600');
insert into records (domain_id, name, type, ttl, prio, content) values (currval('domains_id_seq'), 'ns.example.com', 'A', 3600, default, '127.0.0.1');
insert into records (domain_id, name, type, ttl, prio, content) values (currval('domains_id_seq'), 'example.com', 'NS', 3600, default, 'ns.example.com');
insert into records (domain_id, type, name, content, ttl, prio) values (currval('domains_id_seq'), 'MX', 'example.com', 'alt4.aspmx.l.google.com.', 3600, 10);
```
```
[root@localhost ~]# pdnsutil check-zone example.com
[Warning] Parsed and original record content are not equal: example.com IN MX '10 alt4.aspmx.l.google.com.' (Content parsed as '10 alt4.aspmx.l.google.com')
Segmentation fault
```
If I delete "prio" from MX records, I got just the error:

```
powerdns=# update records set prio = null where name = 'example.com' and type = 'MX';

[root@localhost ~]# pdnsutil check-zone example.com
[Error] Following record had a problem: example.com IN MX  alt4.aspmx.l.google.com.
[Error] Error was: Parsing record content (try 'pdnsutil check-zone'): expected digits at position 1 in ' alt4.aspmx.l.google.com.'
Checked 4 records of 'example.com', 1 errors, 0 warnings.
```

rpm -q pdns
pdns-4.1.0-0.1.rc1.1pdns.el7.x86_64

### PR DESCRIPTION
**Pull request by Habbie**
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
This is ready for review but I'm planning to add a test. The test itself is not an auth 4.1 blocker so merge away after review.

File: pdns/dnsrecords.cc [hunk 1]
```diff
@@ -45,15 +45,26 @@ void DNSResourceRecord::setContent(const string &cont) {
...
+        ret << ".";
+      break;
     case QType::CNAME:
     case QType::DNAME:
     case QType::NS:
     case QType::PTR:
-      if (*(content.rbegin()) != '.') {
-        ret<<content;
+      ret<<content;
+      if (content != ".") {
```
Comment (rgacogne) [inline pdns/dnsrecords.cc]: I'm not sure I agree with this check, as it seems to me that it will add a dot if the existing content is not a single dot, even if it does already end with one? Perhaps the existing check makes more sense, as long as:
> res<<content;

is done before the check.

File: pdns/dnsrecords.cc [hunk 2]
```diff
@@ -45,15 +45,26 @@ void DNSResourceRecord::setContent(const string &cont) {
...
+  vector<string> parts;
+  string last;
+
   switch(qtype.getCode()) {
     case QType::SRV:
     case QType::MX:
+      stringtok(parts, content);
+      last = *parts.rbegin();
+      ret << content;
+      if (last == ".")
```
Comment (rgacogne) [inline pdns/dnsrecords.cc]: Just a nit but this test looks redundant with the next one.

File: pdns/dnsrecords.cc (hunk 1 above)
Comment (Habbie) [reply pdns/dnsrecords.cc]: If I feed in `15 example.com.` with noDot false, out comes `15 example.com.` so I think I'm missing the problem

Comment (Habbie) [reply pdns/dnsrecords.cc]: Sorry, you are right. Pushed another commit.

File: pdns/dnsrecords.cc (hunk 2 above)
Comment (Habbie) [reply pdns/dnsrecords.cc]: As discussed on IRC, leaving this explicitness in.
