### PR TITLE
rec: rec_control top* cleanup

### LINKED ISSUE #13066: Output for `top-remotes` for 0 entries is poor
- Program: Recursor
 - Issue type: Bug report

### Short description

The output for `top-remotes` with 0 records is poor, the `:` hints that there'd be another line, but there is no other line.

### Environment

 - Operating system: Debian 11
 - Software version: 4.9.0-1pdns.bullseye
 - Software source: PowerDNS repository

### Steps to reproduce

1. Set up a pdns-recursor and then don't ask it questions
2. run `rec_control top-remotes`

### Expected behaviour
Perhaps something saying `There are 0 queries.` ...

### Actual behaviour

```sh
# rec_control top-remotes
Over last 0 entries:
#
```

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

Fixes #13066 while there.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/recursordist/rec_channel_rec.cc [hunk 1]
```diff
@@ -1515,34 +1515,33 @@ vector<ComboAddress>* pleaseGetTimeouts()
...
   unsigned int limit = 0;
   unsigned int accounted = 0;
-  if (total != 0) {
-    for (auto i = rcounts.begin(); i != rcounts.end() && limit < 20; ++i, ++limit) {
-      ret << fmt % (-100.0 * i->first / total) % i->second.toString();
-      accounted += -i->first;
-    }
-    ret << '\n'
-        << fmt % (100.0 * (total - accounted) / total) % "rest";
+  for (auto i = rcounts.rbegin(); i != rcounts.rend() && limit < 20; ++i, ++limit) {
```
Comment (rgacogne) [inline pdns/recursordist/rec_channel_rec.cc:1539]: I'm surprised clang-tidy doesn't scream at this `i` variable name.

File: pdns/recursordist/rec_channel_rec.cc [hunk 2]
```diff
@@ -1585,37 +1584,34 @@ static DNSName nopFilter(const DNSName& name)
...
   unsigned int limit = 0;
   unsigned int accounted = 0;
-  if (total > 0) {
-    for (auto i = rcounts.begin(); i != rcounts.end() && limit < 20; ++i, ++limit) {
-      ret << fmt % (-100.0 * i->first / total) % (i->second.first.toLogString() + "|" + DNSRecordContent::NumberToType(i->second.second));
-      accounted += -i->first;
-    }
-    ret << '\n'
-        << fmt % (100.0 * (total - accounted) / total) % "rest";
+  for (auto i = rcounts.rbegin(); i != rcounts.rend() && limit < 20; ++i, ++limit) {
```
Comment (rgacogne) [inline pdns/recursordist/rec_channel_rec.cc:1609]: Same remark about `i` (that you did not introduce, to be clear!).

**Review by rgacogne — APPROVED** [review]
