### PR TITLE
rec: Fix erroneous check for section 4.1 of rfc6840

### LINKED ISSUE #5648: denials from root zone lead to Bogus
- Program: Recursor
 - Issue type: Bug report

### Short description
Querying for a name in a non-existing TLD leads the Recursor to decide the response is Bogus.

### Environment

- Operating system: Debian/Raspbian 8 Jessie, osx
 - Software version: 0.0.1705g4e3d44d-1pdns.jessie, da2869bb7a76e96e47054054c650de0eed0d0602
 - Software source: repo.powerdns.com, git

### Steps to reproduce
1. set `dnssec=log-fail`
2. query for `foo12345.` or `local.` etc.

### Expected behaviour
The recursor does not log a Bogus line.

### Actual behaviour
```
Aug 24 13:40:03 lorentz pdns_recursor[15407]: [825] Invalid denial found for foo7599, returning Bogus, res=0, expectedState=1
Aug 24 13:40:03 lorentz pdns_recursor[15407]: [825] validation state was Secure, state update is Bogus, validation state is now Bogus
Aug 24 13:40:03 lorentz pdns_recursor[15407]: Answer to foo7599|SOA for 192.168.0.29:18007 validates as Bogus
```

### Other information
From the mostly useless (in this case) trace I get the impression the query is asked at the root servers twice.

Interesting bit from the trace:
```
Aug 24 16:34:18 [1] local: got negative caching indication for name 'local' (accept=1), newtarget='(empty)'
Aug 24 16:34:18 Do have: ./NSEC
Aug 24 16:34:18 	aaa. NS SOA RRSIG NSEC DNSKEY
Aug 24 16:34:18 type is TYPE0, NS is 1, SOA is 1, signer is ., owner name is .
Aug 24 16:34:18 Did not deny existence of TYPE0, .?=local, 0, next: aaa
Aug 24 16:34:18 Do have: loans/NSEC
Aug 24 16:34:18 	locker. NS DS RRSIG NSEC
Aug 24 16:34:18 type is TYPE0, NS is 1, SOA is 0, signer is ., owner name is loans.
Aug 24 16:34:18 An ancestor delegation NSEC RR can only deny the existence of a DS
Aug 24 16:34:18 Now looking for the closest encloser for local
Aug 24 16:34:18 [1] Invalid denial found for local, returning Bogus, res=0, expectedState=1
Aug 24 16:34:18 [1] validation state was Secure, state update is Bogus, validation state is now Bogus
Aug 24 16:34:18 [1] local: status=NXDOMAIN, we are done (have negative SOA)
Aug 24 16:34:18 [1] local: failed (res=3)
Aug 24 16:34:18 Starting validation of answer to local|A for 127.0.0.1:57192
Aug 24 16:34:18 Answer to local|A for 127.0.0.1:57192 validates as Bogus
Aug 24 16:34:18 Sending out SERVFAIL for local|A because recursor or query demands it for Bogus results
Aug 24 16:34:18 2 [1/1] answer to question 'local|A': 0 answers, 0 additional, took 2 packets, 41.925 ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=3
```

Names between `.` and `aaa.` (the first NSEC in the root zone) do NOT fail.

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

The DNSSEC validation check for section 4.1 of rfc6840 was wrong, leading to a Bogus validation state when getting a denial from the root zone.
Also fixes a bug in a DNSSEC validation corner case with forwarded zones, uncovered by this fix (we should go Bogus if we get an `NXDomain` answer from the parent when trying to get a `DS` record for a name we were told exists, by the authoritative server we forwarded to).

Fixes #5648.
Supersedes #5651.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [x] added or modified unit test(s)

### CODE REVIEW

File: pdns/validate.cc [hunk 1]
```diff
@@ -49,24 +49,26 @@ dState getDenial(const cspmap_t &validrrsets, const DNSName& qname, const uint16
...
-
         /* RFC 6840 section 4.1 "Clarifications on Nonexistence Proofs":
            Ancestor delegation NSEC or NSEC3 RRs MUST NOT be used to assume
            nonexistence of any RRs below that zone cut, which include all RRs at
            that (original) owner name other than DS RRs, and all RRs below that
            owner name regardless of type.
         */
-        LOG("type is "<<QType(qtype).getName()<<", NS is "<<std::to_string(nsec->d_set.count(QType::NS))<<", SOA is "<<std::to_string(nsec->d_set.count(QType::SOA))<<", signer is "<<getSigner(v.second.signatures).toString()<<", owner name is "<<v.first.first.toString()<<endl);
-        if (qtype != QType::DS && nsec->d_set.count(QType::NS) && !nsec->d_set.count(QType::SOA) &&
+        if (nsec->d_set.count(QType::NS) && !nsec->d_set.count(QType::SOA) &&
```
Comment (Habbie) [inline pdns/validate.cc]: The SOA check feels redundant, isn't the label count right after it sufficient?

Comment (rgacogne) [reply pdns/validate.cc]: I think you are right, but since section 4.1 [1] of rfc6840 explicitly lists that condition and the check is cheaper than the label count one, I'd rather keep it. 

[1]: https://tools.ietf.org/html/rfc6840#section-4.1

**Comment by Habbie** [comment]
:+1:

On 12 September 2017 12:51:57 CEST, Remi Gacogne <notifications@github.com> wrote:
>rgacogne commented on this pull request.
>
>
>
>>          /* RFC 6840 section 4.1 "Clarifications on Nonexistence
>Proofs":
>       Ancestor delegation NSEC or NSEC3 RRs MUST NOT be used to assume
>  nonexistence of any RRs below that zone cut, which include all RRs at
>   that (original) owner name other than DS RRs, and all RRs below that
>            owner name regardless of type.
>         */
>-        LOG("type is "<<QType(qtype).getName()<<", NS is
>"<<std::to_string(nsec->d_set.count(QType::NS))<<", SOA is
>"<<std::to_string(nsec->d_set.count(QType::SOA))<<", signer is
>"<<getSigner(v.second.signatures).toString()<<", owner name is
>"<<v.first.first.toString()<<endl);
>-        if (qtype != QType::DS && nsec->d_set.count(QType::NS) &&
>!nsec->d_set.count(QType::SOA) &&
>+        if (nsec->d_set.count(QType::NS) &&
>!nsec->d_set.count(QType::SOA) &&
>
>I think you are right, but since section 4.1 [1] of rfc6840 explicitly
>lists that condition and the check is cheaper than the label count one,
>I'd rather keep it. 
>
>[1]: https://tools.ietf.org/html/rfc6840#section-4.1
>
>-- 
>You are receiving this because your review was requested.
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/pull/5670#discussion_r138313456

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
