### PR TITLE
 auth: Prevent more than one CNAME/SOA record in the same RRset

### LINKED ISSUE #7277: auth: API happily accepts the creation of a CNAME RRSET with multiple records
- Program: Authoritative
 - Issue type: Bug report

### Short description

The API happily accepts the creation of a CNAME RRSET with multiple records.

### Environment
 - Operating system: EL6
 - Software version: 4.1.5
 - Software source: PowerDNS repository

### Steps to reproduce

Create a "example.com" test zone on a PDNS server, for example via `pdnsutil create-zone example.com` the use the API to create a `CNAME` RRSET: 

```
curl -H 'X-API-Key: myAPIKey' --request PATCH -k http://127.0.0.1:8081/api/v1/servers/localhost/zones/example.com \
--data '{"rrsets": [{"name": "webserver.example.com.", "type": "CNAME", "ttl": 60, "changetype": "REPLACE", "records": [{"content": "web01.example.com.", "disabled": false}, {"content": "web02.example.com.", "disabled": false}, {"content":
"web03.example.com.", "disabled": false}] }] }'
```

### Expected behaviour
PowerDNS API must refuse to add/edit multiple CNAME records for the same name attribute, returning a 4xx error.

### Actual behaviour
PowerDNS API accepts more than one CNAME record for the same name attribute. Return code is 204.

```
MariaDB [pdnstest_1]> SELECT records.domain_id, records.name, records.type, records.content, records.ttl FROM domains LEFT JOIN records ON domains.id = records.domain_id WHERE domains.name = 'example.com' AND records.name = 'webserver.example.com';
+-----------+-----------------------+-------+-------------------+------+
| domain_id | name                  | type  | content           | ttl  |
+-----------+-----------------------+-------+-------------------+------+
|      1953 | webserver.example.com | CNAME | web01.example.com |   60 |
|      1953 | webserver.example.com | CNAME | web02.example.com |   60 |
|      1953 | webserver.example.com | CNAME | web03.example.com |   60 |
+-----------+-----------------------+-------+-------------------+------+
```

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Fixes #7277.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/ws-auth.cc [hunk 1]
```diff
@@ -504,6 +504,7 @@ static void validateGatheredRRType(const DNSResourceRecord& rr) {
 }
 
 static void gatherRecords(const Json container, const DNSName& qname, const QType qtype, const int ttl, vector<DNSResourceRecord>& new_records, vector<DNSResourceRecord>& new_ptrs) {
+  static const std::set<uint16_t> onlyOneEntryTypes = { QType::CNAME, QType::SOA};
```
Comment (zeha) [inline pdns/ws-auth.cc]: nit: add space before };
