### PR TITLE
auth: refactor health checks monitoring done from LUA records

### LINKED ISSUE #7988: LUA ifurlup health check does not clear checks if URL changes or record is deleted
- Program: Authoritative
 - Issue type: Bug report

### Short description
If you change the URL in an `ifurlup` health check, the old URL is not removed from the check that is run  every ~1 second.
If you delete the record, none of the URL health checks are stopped.

### Environment
 - Operating system: Ubuntu 18.04 amd64
 - Software version: 4.2.0~rc2-1pdns.bionic 
 - Software source: PowerDNS repository

### Steps to reproduce

1. Create LUA record with `ifurlup` check
2. Query the record, so that the monitoring is enabled
3. Change the URL in the record, to another valid URL
4. Query the record again, and observe the web server listed in the record is receiving a request for both URLs in the access log

### Expected behaviour

I expect the previous record to be removed from monitoring

### Actual behaviour

TTL of 5 minutes

Create:
```
dns-test.pfak.org IN LUA A "ifurlup('https://checkip.pfak.org/?format=json', {'198.50.219.2'})"
```

Lookup:
```
# dig dns-test.pfak.org @ns1.pfak.org`
```

syslog:
```
Jun 26 02:51:36 ns1 pdns_server[1499]: LUA record monitoring declaring 198.50.219.2 UP for URL https://checkip.pfak.org/?format=json!
```
access_log:
```
198.50.219.2 - - [26/Jun/2019:02:51:36 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:51:41 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:51:46 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:51:51 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:51:56 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:01 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:06 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:11 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:16 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:21 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:26 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:31 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:36 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
```

Change:
```
dns-test.pfak.org IN LUA A "ifurlup('https://checkip.pfak.org/', {'198.50.219.2'})"
```

Lookup:
```
# dig dns-test.pfak.org @ns1.pfak.org
```

syslog:
```
Jun 26 02:52:41 ns1 pdns_server[1499]: LUA record monitoring declaring 198.50.219.2 UP for URL https://checkip.pfak.org/!
```

access_log:
```
198.50.219.2 - - [26/Jun/2019:02:52:41 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:42 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:46 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:47 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:51 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:52 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:56 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:52:57 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:01 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:02 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:07 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:07 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:12 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:12 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:17 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:17 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:22 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:22 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:27 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:27 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:32 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:53:32 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
```

Change:
```
dns-test.pfak.org IN LUA A "ifurlup('https://checkip.pfak.org/?format=callback', {'198.50.219.2'})"
```

Lookup:
```
# dig dns-test.pfak.org @ns1.pfak.org
```

syslog:
```
Jun 26 02:56:01 ns1 pdns_server[1499]: LUA record monitoring declaring 198.50.219.2 UP for URL https://checkip.pfak.org/?format=callback!
```

access_log:
```
198.50.219.2 - - [26/Jun/2019:02:57:12 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:13 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:17 +0000] "GET /?format=callback HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:17 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:18 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:22 +0000] "GET /?format=callback HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:23 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:23 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:27 +0000] "GET /?format=callback HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:28 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:28 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:32 +0000] "GET /?format=callback HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:33 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:02:57:33 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
```

Just to make sure it's not tied to TTL, this is significantly after the TTL expires:

```
198.50.219.2 - - [26/Jun/2019:03:12:26 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:30 +0000] "GET /?format=callback HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:31 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:31 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:36 +0000] "GET /?format=callback HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:36 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:36 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:41 +0000] "GET /?format=callback HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:41 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:41 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:46 +0000] "GET /?format=callback HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:46 +0000] "GET / HTTP/1.1" 200 3760 "-" "PowerDNS Authoritative Server"
198.50.219.2 - - [26/Jun/2019:03:12:46 +0000] "GET /?format=json HTTP/1.1" 200 3775 "-" "PowerDNS Authoritative Server"
```

### PR DESCRIPTION
**Pull request by chbruyand**
### Short description
This PR puts TCP/IP and URL health checks in a single thread (instead of 1 thread per check).

This also removes checks that have been unused for a given period of time (currently 1 hour). This will prevent checks from modified or deleted records to keep being performed by the authoritative server (fix #7988).

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/lua-record.cc [hunk 1]
```diff
@@ -60,30 +60,133 @@ class IsUpOracle
...
+          if (state->first) {
+            state->first = false;
+          }
+          if (std::chrono::system_clock::from_time_t(state->lastAccess) < (checkStart - std::chrono::hours(1))) {
+            toDelete.push_back(it);
+          }
+        }
+      }
+      if (!toDelete.empty()) {
+        WriteLock lock{&d_lock};
```
Comment (rgacogne) [inline pdns/lua-record.cc]: We release the lock after scanning the map and the actual removals, so I believe another thread might be able to insert an entry during that time. Since `d_statuses` is based on a `std::map` the stored iterators should still be valid, but that might at the very least warrant a comment.

File: pdns/lua-record.cc [hunk 2]
```diff
@@ -108,25 +211,27 @@ class IsUpOracle
...
+    ReadLock lock{&d_lock};
+    auto iter = d_statuses.find(cd);
+    if (iter != d_statuses.end()) {
+      iter->second->lastAccess = now;
+      return iter->second->status;
+    }
+  }
+  {
+    WriteLock lock{&d_lock};
+    d_statuses[cd] = std::unique_ptr<CheckState>(new CheckState{now});
```
Comment (rgacogne) [inline pdns/lua-record.cc]: I'm not sure if we care but it looks like another thread might be able to insert the same entry between the time we release the lock then acquire it again.

**Comment by chbruyand** [comment]
Thanks for your review. I added an extra check on insertion when we have the lock and changed how we store items to be deleted.

**Comment by pfak** [comment]
> This also removes checks that have been unused for a given period of time (currently 1 hour). 

Not a fan of this behaviour. But, that being said. I'm not a fan of the current behaviour of not running a check until someones tries to look up the record. Is it possible to make this configurable? I would prefer ALL checks to be run if the record exists, and/or the existing behaviour.

**Comment by Someguy123** [comment]
The configurable health check would be great - it would help resolve the issue I've just reported: https://github.com/PowerDNS/pdns/issues/8261

**Comment by sbakhos** [comment]
If possible I would like to configure the timeout for the health check too. We're looking at implementing this and noticed in our lab a lot of flapping on some of the longer checks (about 500ms).

**Comment by chbruyand** [comment]
> > Also I don't understand why this broke the dnsdist circleci tests :/
> 
> Can you see if a rebase fixes that? We had/have an issue with CircleCI running commit X tests against commit Y builds, and we merged an improvement for that on master yesterday.

Looks like *it works (c)* now...

File: docs/settings.rst [hunk 3]
```diff
@@ -868,6 +868,32 @@ e.g. error = 3, warning = 4, notice = 5, info = 6
 
 Script to be used to edit incoming AXFRs, see :ref:`modes-of-operation-axfrfilter`
 
+.. _setting-lua-health-checks-expire-delay:
+
+``lua-health-checks-expire-delay``
+-----------------------------
```
Comment (rgacogne) [inline docs/settings.rst]:
```suggestion
----------------------------------
```

File: docs/settings.rst [hunk 4]
```diff
@@ -868,6 +868,32 @@ e.g. error = 3, warning = 4, notice = 5, info = 6
...
+
+.. versionadded:: 4.3.0
+
+Amount of time (in seconds) to expire (remove) a LUA monitoring check when the record
+isn't used any more (either deleted or modified).
+
+.. _setting-lua-health-checks-interval:
+
+``lua-health-checks-interval``
+-----------------------------
```
Comment (rgacogne) [inline docs/settings.rst]:
```suggestion
------------------------------
```

File: pdns/common_startup.cc [hunk 5]
```diff
@@ -217,6 +219,9 @@ void declareArguments()
 #ifdef HAVE_LUA_RECORDS
   ::arg().setSwitch("enable-lua-records", "Process LUA records for all zones (metadata overrides this)")="no";
   ::arg().set("lua-records-exec-limit", "LUA records scripts execution limit (instructions count). Values <= 0 mean no limit")="1000";
+  ::arg().set("lua-health-checks-expire-delay", "Stops doing health checks after the record hasn't been unused for that delay (in seconds)")="3600";
```
Comment (rgacogne) [inline pdns/common_startup.cc]:
```suggestion
  ::arg().set("lua-health-checks-expire-delay", "Stops doing health checks after the record hasn't been used for that delay (in seconds)")="3600";
```

File: pdns/lua-record.cc [hunk 6]
```diff
@@ -60,30 +60,145 @@ class IsUpOracle
...
+          g_log<<"(source "<<src.toString()<<") ";
+        g_log<<"UP!"<<endl;
+      }
+      setUp(cd);
+    }
+    catch (const NetworkError& ne) {
+      if(status || first) {
+        g_log<<Logger::Warning<<"Lua record monitoring declaring TCP/IP "<<cd.rem.toStringWithPort()<<" DOWN: "<<ne.what()<<endl;
+      }
+      setDown(cd);
```
Comment (rgacogne) [inline pdns/lua-record.cc]: I wonder if we should catch some other exception types here. I'm for example thinking of an invalid "source" address throwing a `PDNSException`.

File: pdns/common_startup.cc [hunk 7]
```diff
@@ -217,6 +219,9 @@ void declareArguments()
...
+  ::arg().set("lua-health-checks-interval", "LUA records health checks monitoring interval in seconds")="5";
+  ::arg().set("lua-health-checks-timeout", "Maximum time in milliseconds that you allow the LUA monitoring health checks to take")="500";
```
Comment (rgacogne) [inline pdns/common_startup.cc]:
```suggestion
```

File: pdns/lua-record.cc [hunk 8]
```diff
@@ -60,30 +60,145 @@ class IsUpOracle
...
   statuses_t d_statuses;
 
-  std::mutex d_mutex;
+  std::unique_ptr<std::thread> d_checkerThread;
 
   void setStatus(const CheckDesc& cd, bool status)
   {
-    std::lock_guard<std::mutex> l(d_mutex);
-    d_statuses[cd].status=status;
+    auto& state = d_statuses[cd];
```
Comment (rgacogne) [inline pdns/lua-record.cc]: Doing the access here without a lock is a bit scary. We know the entry already exists but, unless i'm missing something, a new insertion might occur at the exact same time from `IsUpOracle::isUp()`, right?

**Comment by chbruyand** [comment]
Thanks for your review. Invalid options (like `source`) will now trigger an error before being inserted in the check list.

File: pdns/lua-record.cc [hunk 9]
```diff
@@ -108,25 +224,37 @@ class IsUpOracle
...
+      iter->second->lastAccess = now;
+      return iter->second->status;
+    }
+  }
+  {
+    WriteLock lock{&d_lock};
+    // Make sure we don't insert new entry twice now we have the lock
+    if (d_statuses.find(cd) == d_statuses.end()) {
+      // try to parse options so we don't insert on malformed content
+      if (cd.opts.count("source")) {
```
Comment (rgacogne) [inline pdns/lua-record.cc]: Just a nit but perhaps the parsing could be done before taking the lock?

File: pdns/lua-record.cc [hunk 10]
```diff
@@ -239,6 +240,13 @@ bool IsUpOracle::isUp(const CheckDesc& cd)
       return iter->second->status;
     }
   }
+  // try to parse options so we don't insert any malformed content
+  if (cd.opts.count("source")) {
+    ComboAddress src(cd.opts.at("source"));
+  }
+  if (cd.opts.count("timeout")) {
+    int timeout = std::atoi(cd.opts.at("timeout").c_str());
```
Comment (Habbie) [inline pdns/lua-record.cc]:
```
lua-record.cc: In member function ‘bool IsUpOracle::isUp(const IsUpOracle::CheckDesc&)’:
lua-record.cc:248:9: warning: unused variable ‘timeout’ [-Wunused-variable]
     int timeout = std::atoi(cd.opts.at("timeout").c_str());
         ^~~~~~~
```

File: pdns/lua-record.cc [hunk 11]
```diff
@@ -952,7 +960,7 @@ std::vector<shared_ptr<DNSRecordContent>> luaSynth(const std::string& code, cons
         ret.push_back(DNSRecordContent::mastermake(qtype, QClass::IN, content ));
     }
   } catch(std::exception &e) {
-    g_log<<Logger::Error<<"Lua record reported: "<<e.what();
+    g_log << Logger::Info << "Lua record reported: " << e.what();
```
Comment (Habbie) [inline pdns/lua-record.cc]: I just wrote this into my local copy, it would conflict with this branch, so I'll leave it here:
```
    g_log<<Logger::Error<<"Lua record ("<<query<<"|"<<QType(qtype).getName()<<") reported: "<<e.what();
```

Can you take that change? I have no opinion on Info vs. Error.

Comment (Habbie) [reply pdns/lua-record.cc]: I've pushed this to your branch.

File: pdns/lua-record.cc (hunk 10 above)
Comment (Habbie) [reply pdns/lua-record.cc]: Pushed a commit to remove those 3 lines to your branch.

**Comment by Habbie** [comment]
rebased
