### PR TITLE
Fix recursor not responsive after Lua config reload

### LINKED ISSUE #11795: Recursor stops responding after `rec_control reload-lua-config`
- Program: Recursor
 - Issue type: Bug report

### Short description
Recursor stops responding after `rec_control  reload-lua-config`

### Environment
 - Operating system:  SLES15-SP4
 - Software version: PowerDNS Recursor 4.7.1
 - Software source: PowerDNS repository, [self compiled](https://github.com/PowerDNS/pdns/files/9181220/powerdns-recursor_4.7.1_build.log) (build-log)

### Steps to reproduce
```
mkdir -p tmp; cd tmp
> recursor.conf

echo 'dnstapFrameStreamServer( "10.20.30.40:1234" )' > lua.conf

pdns_recursor --daemon=no --config-dir=. --socket-dir=. --local-address=127.0.0.53 --lua-config-file=./lua.conf

dig +tries=1 +time=1 @127.0.0.53 localhost  ## WORKS

rec_control --socket-dir=. reload-lua-config

dig +tries=1 +time=1 @127.0.0.53 localhost  ## FAILS (timeout)


```

### Expected behaviour
Recursor should never stop responding after `reload-lua-config`

### Actual behaviour
Recursor does not work anymore after `reload-lua-config` on circumstances.

### Other information
To trigger the error, the FrameStreamServer IP address must *not* be a local address of the server itself, but a external one. It doesn't matter if the address answers or not.

There is nothing in the journal what indicates an error.

### PR DESCRIPTION
**Pull request by fredmorcos**
### Short description
- Avoid reloading Lua config if it hasn't changed
- Asynchronously destroys dnstap connections from the old config in case of reload

Fixes #11795

### Checklist
I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/rec-lua-conf.cc [hunk 1]
```diff
@@ -43,6 +43,28 @@ LuaConfigItems::LuaConfigItems()
 
 /* DID YOU READ THE STORY ABOVE? */
 
+bool operator==(const FrameStreamExportConfig& configA, const FrameStreamExportConfig& configB)
+{
+  // clang-format off
+  return configA.servers.size()       == configB.servers.size()       &&
```
Comment (omoerbeek) [inline pdns/rec-lua-conf.cc:49]: The size check is redundant, part of the vector `operator==`

File: pdns/recursordist/rec-main.cc [hunk 2]
```diff
@@ -626,31 +625,41 @@ static std::shared_ptr<std::vector<std::unique_ptr<FrameStreamLogger>>> startFra
...
+}
+
 bool checkFrameStreamExport(LocalStateHolder<LuaConfigItems>& luaconfsLocal)
 {
   if (!luaconfsLocal->frameStreamExportConfig.enabled) {
-    if (t_frameStreamServers) {
+    if (t_frameStreamServersInfo.servers) {
       // dt's take care of cleanup
-      t_frameStreamServers.reset();
+      asyncFrameStreamLoggersCleanup(std::move(t_frameStreamServersInfo.servers));
```
Comment (omoerbeek) [inline pdns/recursordist/rec-main.cc:641]:
```suggestion
      asyncFrameStreamLoggersCleanup(std::move(t_frameStreamServersInfo.servers));
      t_frameStreamServersInfo.config = luaconfsLocal->frameStreamExportConfig;
```

File: pdns/recursordist/rec-main.cc [hunk 3]
```diff
@@ -626,31 +625,41 @@ static std::shared_ptr<std::vector<std::unique_ptr<FrameStreamLogger>>> startFra
...
 
-    auto log = g_slog->withName("dnstap");
-    t_frameStreamServers = startFrameStreamServers(luaconfsLocal->frameStreamExportConfig, log);
-    t_frameStreamServersGeneration = luaconfsLocal->generation;
+    auto dnsTapLog = g_slog->withName("dnstap");
+    t_frameStreamServersInfo.servers = startFrameStreamServers(luaconfsLocal->frameStreamExportConfig, dnsTapLog);
+    t_frameStreamServersInfo.config = luaconfsLocal->frameStreamExportConfig;
   }
 
+  t_frameStreamServersInfo.generation = luaconfsLocal->generation;
```
Comment (omoerbeek) [inline pdns/recursordist/rec-main.cc:661]: This statement can be moved into the `if` block I believe

**Review by omoerbeek — CHANGES_REQUESTED** [review]
As this is also supposed to compile without  HAVE_FSTRM ...
`FrameStreamExportConfig` and its methods can be moved into `rec-main.cc`
`struct FrameStreamServersInfo` can be moved into `rec-main.hh` inside the existing `HAVE_FSTRM` block.

File: pdns/recursordist/rec-main.cc (hunk 2 above)
Comment (fredmorcos) [reply pdns/recursordist/rec-main.cc:641]: Is that change because the config was previously enabled and now it isn't and so we need to update it?

Comment (fredmorcos) [reply pdns/recursordist/rec-main.cc:641]: Right. Thanks!

**Review by omoerbeek — APPROVED** [review]
