### PR TITLE
lua comboaddress: raw docs, cleanups, dnsdist add getRaw

### LINKED ISSUE #15246: dnsdist: newCAFromRaw is missing from documentation, is in source
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description
newCAFromRaw is not in dnsdist documentation, while it exists in Lua bindings.

The dnsdist docs is here
https://www.dnsdist.org/reference/comboaddress.html

The function is here
https://github.com/PowerDNS/pdns/blob/e2370ee4005ceb3957a7769ef5bf9fb1fa3d1325/pdns/dnsdistdist/dnsdist-lua-bindings.cc#L224

I am writing this logic that I described in comment here, parsing RDATA for IP addresses in Lua

https://github.com/PowerDNS/pdns/issues/6759#issuecomment-2690979463

and realized it might be faster to use newCAFromRaw that is already in pdns... but it is not documented for dnsdist.

### PR DESCRIPTION
**Pull request by karelbilek**
### Short description
Add newCAFromRaw docs, getRaw func+doc

It's mostly dumb copy-paste

Fixes #15246

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
   - I don't see any existing dnsdist regression/unit tests using these functions and I think adding them is beyond the scope
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by rgacogne — COMMENTED** [review]
Thanks a lot for this pull request! The changes look good to me, but I'm pretty sure the code formatter will not be happy, and I expect clang-tidy to complain about the short variable name as well. I can fix these warnings for you, just let me know!

**Comment by karelbilek** [comment]
I was trying to fix it, but... maybe I can also move it to the shared iputils.hh? It's used in 3 places anyway, and it's not that trivial?

**Comment by rgacogne** [comment]
> I was trying to fix it, but... maybe I can also move it to the shared iputils.hh? It's used in 3 places anyway, and it's not that trivial?

I agree it would be better to make it a method of `ComboAddress` instead of re-implementing it several times.

**Comment by karelbilek** [comment]
it's actually already there?

```
[[nodiscard]] string toByteString() const
  {
    // NOLINTBEGIN(cppcoreguidelines-pro-type-reinterpret-cast)
    if (isIPv4()) {
      return {reinterpret_cast<const char*>(&sin4.sin_addr.s_addr), sizeof(sin4.sin_addr.s_addr)};
    }
    return {reinterpret_cast<const char*>(&sin6.sin6_addr.s6_addr), sizeof(sin6.sin6_addr.s6_addr)};
    // NOLINTEND(cppcoreguidelines-pro-type-reinterpret-cast)
  }
```

That's the same thing, right

**Comment by rgacogne** [comment]
Yes, good catch! Now we need to actually use it :D

File: pdns/lua-base4.cc [hunk 1]
```diff
@@ -147,22 +147,16 @@ void BaseLua4::prepareContext() {
...
-  d_lw->registerToStringFunction<string(ComboAddress::*)()>([](const ComboAddress& ca) { return ca.toString(); });
-  d_lw->registerFunction<string(ComboAddress::*)()>("toStringWithPort", [](const ComboAddress& ca) { return ca.toStringWithPort(); });
-  d_lw->registerFunction<string(ComboAddress::*)()>("getRaw", [](const ComboAddress& ca) {
-      if(ca.sin4.sin_family == AF_INET) {
-        auto t=ca.sin4.sin_addr.s_addr; return string((const char*)&t, 4);
-      }
-      else
-        return string((const char*)&ca.sin6.sin6_addr.s6_addr, 16);
-    } );
+  d_lw->registerFunction<bool(ComboAddress::*)()>("isIPv4", [](const ComboAddress& addr) { return addr.sin4.sin_family == AF_INET; });
```
Comment (karelbilek) [inline pdns/lua-base4.cc:150]: @rgacogne I renamed all the `ca` here to `addr` so the linter is happy (just the new line would be enough I guess, but I did it everywhere)

Comment (rgacogne) [reply pdns/lua-base4.cc:150]: That's great, many thanks!

File: docs/lua-records/reference/comboaddress.rst [hunk 2]
```diff
@@ -60,7 +60,7 @@ Functions and methods of a ``ComboAddress``
 
   .. method:: ComboAddress:getRaw() -> string
 
-    Returns in raw bytes format format
+    Returns in raw bytes format
```
Comment (karelbilek) [inline docs/lua-records/reference/comboaddress.rst:63]: @rgacogne Noticed typo in pdns docs, so fixed too :)
