### PR TITLE
Auth: Reload /etc/resolv.conf when modified. Fix #6263

### LINKED ISSUE #6263: Stub resolver should reload /etc/resolv.conf
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

When "`resolver`" isn't set, auth's stub resolver reads `/etc/resolv.conf` once at startup to determine what nameservers to use.

It uses them forever, even if `/etc/resolv.conf` is later changed.

### Environment

 - Operating system: Ubuntu 16.04 (x86-64)
 - Software version: 4.1.0-1pdns.xenial
 - Software source: PowerDNS repository

### Steps to reproduce

1. Start PowerDNS.
2. Change `/etc/resolv.conf` to use different nameservers.
3. Wait for PowerDNS to do a secpoll query.

### Expected behaviour

PowerDNS querying one of the nameservers currently in `/etc/resolv.conf`.

### Actual behaviour

PowerDNS querying the nameserver that was in `/etc/resolv.conf` when it started.

### Other information

I use resolvconf. Last time I rebooted, it changed `/run/resolvconf/resolv.conf` from a nameserver I don't like to a nameserver I do like 1 second after PowerDNS was started. Sad face.

It's not a problem for me, it just makes me unhappy.

I don't often change `/etc/resolv.conf`.

### PR DESCRIPTION
**Pull request by chbruyand**
### Short description
Reload /etc/resolv.conf when file has been modified
Issue #6263

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

File: pdns/stubresolver.cc [hunk 1]
```diff
@@ -14,9 +16,15 @@
...
 
+#define LOCAL_RESOLV_CONF_PATH "/etc/resolv.conf"
+
 // s_resolversForStub contains the ComboAddresses that are used by
 // stubDoResolve
 static vector<ComboAddress> s_resolversForStub;
+static pthread_mutex_t s_resolversForStubLock = PTHREAD_MUTEX_INITIALIZER;
+
+// /etc/resolv.conf last modification time
+static auto s_localResolvConfMtime = 0;
```
Comment (ahupowerdns) [inline pdns/stubresolver.cc]: In this case, you leave the compiler guessing with = 0. I suggest static time_t s_localResolvConfTime

File: pdns/stubresolver.cc [hunk 2]
```diff
@@ -30,6 +38,47 @@ bool resolversDefined()
...
+  struct stat st;
+  string line;
+
+  if(!ifs)
+    return;
+  if (stat(LOCAL_RESOLV_CONF_PATH, &st) == -1)
+    return ;
+  s_localResolvConfMtime = st.st_mtime;
+
+  pthread_mutex_lock(&s_resolversForStubLock);
```
Comment (ahupowerdns) [inline pdns/stubresolver.cc]: the lock.hh include file has 'resource acquisition is initialization' (RAII) wrappers for setting and releasing locks. These are much recommended as you can't forget to unlock - the destructor does that for you.

File: pdns/stubresolver.cc [hunk 3]
```diff
@@ -80,6 +104,16 @@ void stubParseResolveConf()
 // s_resolversForStub contains the ComboAddresses that are used to resolve the
 int stubDoResolve(const DNSName& qname, uint16_t qtype, vector<DNSZoneRecord>& ret)
 {
+  // only check if resolvers come from he local resolv.conf in the first place
+  if (s_localResolvConfMtime != 0) {
+    struct stat st;
+
+    if (stat(LOCAL_RESOLV_CONF_PATH, &st) != -1) {
+      if (st.st_mtime > s_localResolvConfMtime) {
```
Comment (ahupowerdns) [inline pdns/stubresolver.cc]: I'd say != instead of > - any change is a good reason to reload

Comment (mnordhoff) [inline pdns/stubresolver.cc]: What about using `!=` instead of `>`? It's a bit weird, but someone could revert to an older backup copy of the file or something.

File: pdns/stubresolver.cc [hunk 4]
```diff
@@ -80,6 +114,10 @@ void stubParseResolveConf()
 // s_resolversForStub contains the ComboAddresses that are used to resolve the
 int stubDoResolve(const DNSName& qname, uint16_t qtype, vector<DNSZoneRecord>& ret)
 {
+  // only check if resolvers come from he local resolv.conf in the first place
```
Comment (zeha) [inline pdns/stubresolver.cc]: s/he/the/
