### PR TITLE
dnsdist: Remove JSONP, limit command to /jsonstat, add security HTTP headers and CORS

### LINKED ISSUE #3217: XSS vulnerability in dnsdist webserver
**Steps to reproduce**

1. Start a dnsdist instance
2. Enable the webserver: `webserver("127.0.0.1:8083", "supersecret")`
3. Navigate to this URL:
`http://127.0.0.1:8083/?callback=%22%3E%3Cscript/src=data:,alert("evilcorp()")%26sol;%26sol;`

**Expected result**
The `callback` query string is sanitized.
**Actual result**
The Javascript submitted with the `callback` parameter is injected in the resulting page and executed in the users browser.

### PR DESCRIPTION
**Pull request by rgacogne**
- Remove the JSONP callback, using simple JSON data instead (Fixes #3217)
- Add basic CORS support in the webserver
- Support command= only on /jsonstat URL
- Add several security-related HTTP headers:
 * X-Content-Type-Options: no-sniff to prevent browsers from guessing MIME type
 * X-Frame-Options: deny to prevent clickjacking
 * X-Permitted-Cross-Domain-Policies: none to keep flash from crossing boundaries
 * X-XSS-Protection: 1; mode=block to mitigate XSS
 * Content-Security-Policy: default-src 'self'; img-src *; style-src 'self' 'unsafe-inline',
 a basic CSP policy to restrict which scripts and CSS can be loaded

### CODE REVIEW

**Comment by zeha** [comment]
LGTM apart from the minor thing above

File: pdns/dnsdist-web.cc [hunk 1]
```diff
@@ -58,68 +72,77 @@ static void connectionThread(int sock, ComboAddress remote, string password)
...
-    }
-
     req.getvars.erase("_"); // jQuery cache buster
 
     YaHTTP::Response resp(req);
+    resp.headers["X-Content-Type-Options"] = "nosniff";
+    resp.headers["X-Frame-Options"] = "deny";
+    resp.headers["X-Permitted-Cross-Domain-Policies"] = "none";
+    resp.headers["X-XSS-Protection"] = "1; mode=block";
+    resp.headers["Content-Security-Policy"] = "default-src 'self'; img-src *; style-src 'self' 'unsafe-inline'";
```
Comment (cmouse) [inline pdns/dnsdist-web.cc]: why is img-src *?

Comment (rgacogne) [inline pdns/dnsdist-web.cc]: Because the current index.html loads images from s3.amazonaws.com and www.powerdns.com, and allowing s3.amazonaws.com felt like allowing pretty much anything. Do you think it should be more restrictive?

Comment (ahupowerdns) [inline pdns/dnsdist-web.cc]: in general, we should remove the external links & add our logo to our own distribution, and remove the GitHub image. It is not nice for monitoring screens to ping externally.

**Comment by rgacogne** [comment]
Removed the remote images in the main page

File: pdns/dnsdist-web.cc [hunk 2]
```diff
@@ -58,68 +72,77 @@ static void connectionThread(int sock, ComboAddress remote, string password)
...
+          if(const auto& val = boost::get<DNSDistStats::stat_t*>(&e.second))
+            obj.insert({e.first, (int)(*val)->load()});
+          else if (const auto& val = boost::get<double*>(&e.second))
+            obj.insert({e.first, (**val)});
+          else
+            obj.insert({e.first, (int)(*boost::get<DNSDistStats::statfunction_t>(&e.second))(e.first)});
+        }
+        Json my_json = obj;
+        resp.body=my_json.dump();
+        resp.headers["Content-Type"] = "application/json";
```
Comment (cmouse) [inline pdns/dnsdist-web.cc]: should we specify ;charset=utf-8 here?

File: pdns/dnsdist-web.cc [hunk 3]
```diff
@@ -205,6 +228,8 @@ static void connectionThread(int sock, ComboAddress remote, string password)
         resp.headers["Content-Type"] = "text/css";
       else if(parts.back() == "js")
         resp.headers["Content-Type"] = "application/javascript";
```
Comment (cmouse) [inline pdns/dnsdist-web.cc]: as well as here.

Comment (tunage) [inline pdns/dnsdist-web.cc]: DNSSec on Bind is broke. 2 different distros and hours on #bind and never found a solution. It work with one or 2 zone but as soon as you cram an feed it 5 or 6 new domains for DNSsec, it just dies.
powerdns fixed all of that and a number of other anomalies first shot, and only took a couple of minutes to configure.
This is a very well maintained project.

**Comment by rgacogne** [comment]
Added charset to JSON, JS, CSS and HTML contents, as suggested by @cmouse. Rebased because it conflicted with the recent HTML fixes.
