### PR TITLE
rec: Fix DNSSEC validation of wildcard-expanded proof

### LINKED ISSUE #17136: NSEC wildcard proof checks expanded qname, not next-closer: signed in-bailiwick NSEC at next-closer satisfies RFC 4035 §5.3.4 → `AD=1` on RFC 4592-invalid wildcard expansion
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)
- [x] I have read and understood the [PowerDNS AI policy](https://github.com/PowerDNS/pdns/blob/master/AI_POLICY.md)

# NSEC wildcard proof checks expanded qname, not next-closer: signed in-bailiwick NSEC at next-closer satisfies RFC 4035 §5.3.4 → `AD=1` on RFC 4592-invalid wildcard expansion

**Reporter:** Qifan Zhang, Palo Alto Networks

---

### Summary

PowerDNS Recursor 5.4.0, in full-recursive DNSSEC-validating mode, can be made to return `AD=1` on a wildcard-expanded answer the victim zone never authorised for the queried owner, using only legitimately signed records.

When `checkWildcardProof()` calls `getDenial()` to verify RFC 4035 §5.3.4 compliance, it passes the expanded qname (`a.b.victim.`) rather than the next-closer (`b.victim.`). `getDenial`'s NSEC path then checks whether any NSEC covers the qname via `isCoveredByNSEC`. A legitimately signed NSEC at `b.victim.` satisfies this check (because `b.victim. < a.b.victim. < ns1.victim.` canonically) but proves the opposite of what is required: it proves the next-closer exists, making the wildcard synthesis invalid per RFC 4592 §3.3.1.

The NSEC3 path in `getDenial` correctly computes and checks the next-closer (`validate.cc:908-969`). The NSEC path lacks this step. BIND 9.20.22 and Unbound 1.24.2 are not affected; they return SERVFAIL.

---

### PowerDNS Recursor version affected

```
PowerDNS Recursor 5.4.0
Tested: 2026-04-11

Affected mode:  Full-recursive with DNSSEC validation enabled (default).
Not affected:   NSEC3 zones; single-label wildcard expansions (trim_labels == 1).
```

---

### Steps to reproduce

1. Operate a DNSSEC-signed NSEC zone `attacker.test.` with:
   - A wildcard: `*.attacker.test. 300 IN A 192.0.2.163` (signed ECDSAP256, RRSIG Labels=2).
   - A non-delegation leaf: `b.attacker.test. 300 IN TXT "exists"` with a corresponding signed NSEC `b.attacker.test. 300 IN NSEC ns1.attacker.test. TXT RRSIG NSEC`.
   - A valid DS chain so PowerDNS Recursor can build the trust chain to this zone.

2. Configure the authoritative to respond to `a.b.attacker.test./A` with:
   ```
   ;; ANSWER SECTION
   a.b.attacker.test.  300  IN  A     192.0.2.163
   a.b.attacker.test.  300  IN  RRSIG A 13 2 300 <exp> <inc> <tag> attacker.test. <wc-sig>
   ;; AUTHORITY SECTION
   b.attacker.test.    300  IN  NSEC  ns1.attacker.test. TXT RRSIG NSEC
   b.attacker.test.    300  IN  RRSIG NSEC 13 3 300 <exp> <inc> <tag> attacker.test. <nsec-sig>
   ```
   Both signatures are legitimately valid under the zone's DNSKEY.

3. Run PowerDNS Recursor 5.4.0 with DNSSEC validation enabled (default), root hints pointing to the synthetic hierarchy, and the synthetic root as the only trust anchor.

4. Send one query:
   ```
   dig @<pdns-ip> a.b.attacker.test. A +dnssec
   ```

5. **Expected (correct) behavior:** PowerDNS Recursor should return `SERVFAIL` (or Bogus) because the `b.attacker.test.` NSEC proves the next-closer exists, invalidating the wildcard expansion.

6. **Observed (buggy) behavior:** PowerDNS Recursor returns `NOERROR`, `AD=1`, `192.0.2.163`. Log shows:
   ```
   msg="Answer" … qname="a.b.attacker.test" qtype="A" rcode="0" … validationState="Secure"
   ```

---

### Data Flow

```
Response at PowerDNS Recursor (a.b.attacker.test. A):

  ANSWER:    a.b.attacker.test.  A  192.0.2.163
             a.b.attacker.test.  RRSIG A 13 2 300 … attacker.test.  [Labels=2]
  AUTHORITY: b.attacker.test.    NSEC ns1.attacker.test. TXT RRSIG NSEC  [signed]
             b.attacker.test.    RRSIG NSEC 13 3 300 … attacker.test.    [Labels=3]

1. updateCacheFromRecords() detects RRSIG Labels=2 < 4 (owner labels)
   → needWildcardProof=true, wildcardLabelsCount=2

2. checkWildcardProof() [syncres.cc:4964]:
   harvestNXRecords → negEntry with b.attacker.test. NSEC (validated, Secure)
   csp = {b.attacker.test./NSEC → record+rrsig}
   getDenial(csp, qname="a.b.attacker.test.", …, wildcardLabelsCount=2)  ← BUG: qname

3. getDenial() NSEC path [validate.cc:678]:
   isCoveredByNSEC("a.b.attacker.test.", "b.attacker.test.", "ns1.attacker.test.")
     b.attacker.test. < a.b.attacker.test. < ns1.attacker.test.  (canonical order)
     → true → dState::NXDOMAIN returned

4. checkWildcardProof(): res==NXDOMAIN → no Bogus set → validationState=Secure → AD=1
```

---

### Source Code Analysis

**`syncres.cc:4984-4985`** — `getDenial` called with qname:

```cpp
cspmap_t csp = harvestCSPFromNE(negEntry);
dState res = getDenial(csp, qname, negEntry.d_qtype.getCode(), false, false,
                       d_validationContext, LogObject(prefix), false, wildcardLabelsCount);
```

`qname` = `"a.b.attacker.test."`. The next-closer `"b.attacker.test."` is not computed here.

**`validate.cc:678`** — NSEC path checks qname:

```cpp
if (isCoveredByNSEC(qname, owner, nsec->d_next)) {
```

**`validate.cc:124-130`** — `isCoveredByNSEC` returns true:

```cpp
int order_bh = begin.canonCompare_three_way(name);    // b. < a.b. → order_bh < 0
int order_hn = name.canonCompare_three_way(next);     // a.b. < ns1. → order_hn < 0
if (order_bh < 0 && order_hn < 0) {
    return true;    // ← "no wrap: BEGINNING --- NAME --- NEXT"
}
```

Canonical DNS order (RFC 4034 §6.1): for `b.attacker.test.` vs `a.b.attacker.test.`, the name with the extra label `a.` after the common suffix `b.attacker.test.` sorts after the shorter one, so `b. < a.b.`. For `a.b.attacker.test.` vs `ns1.attacker.test.`, comparing the next-to-last labels (`b` vs `ns1`): `b`=0x62 < `n`=0x6e, so `a.b. < ns1.`.

**`validate.cc:908-969`** — NSEC3 path correctly computes next-closer (for contrast):

```cpp
DNSName nextCloser(closestEncloser);
nextCloser.prependRawLabel(qname.getRawLabel(labelIdx - 1));
VLOG(log, qname << ":Looking for a NSEC3 covering the next closer name "<<nextCloser<<endl);
...
if (isCoveredByNSEC3Hash(hash, beginHash, nsec3->d_nexthash)) {
    nextCloserFound = true;
```

The NSEC3 path is correct; the NSEC path is missing the equivalent next-closer computation.

---

### Expected correct behavior

RFC 7129 §5.6: the §5.3.4 proof NSEC must cover the **next-closer name** (`b.victim.` for a two-label expansion from `*.victim.`). `isCoveredByNSEC("b.victim.", "b.victim.", "ns1.victim.")`:
- `order_bh = begin.canonCompare(name) = 0` (begin == name)
- Neither the "no-wrap" nor "wrap" condition is met → `return false`
- `getDenial` finds no covering NSEC → `NODENIAL` → `checkWildcardProof` marks Bogus → correct.

---

### Suggested fix

Compute the next-closer name in `checkWildcardProof()` before calling `getDenial()`:

```diff
--- a/syncres.cc
+++ b/syncres.cc
@@ -4982,7 +4982,16 @@ void SyncRes::checkWildcardProof(...)
       cspmap_t csp = harvestCSPFromNE(negEntry);
+      /* RFC 7129 §5.6: the §5.3.4 NSEC must cover the *next-closer* name.
+       * Compute next-closer by chopping (qname.countLabels() - wildcardLabelsCount - 1)
+       * labels from qname.  For single-label wildcard (chopCount==0) this is a no-op. */
+      DNSName nextCloser(qname);
+      const unsigned int chopCount = qname.countLabels() - wildcardLabelsCount - 1;
+      for (unsigned int i = 0; i < chopCount; ++i) {
+        nextCloser.chopOff();
+      }
       dState res = getDenial(csp, qname, negEntry.d_qtype.getCode(), false, false,
-                             d_validationContext, LogObject(prefix), false, wildcardLabelsCount);
+      dState res = getDenial(csp, nextCloser, negEntry.d_qtype.getCode(), false, false,
+                             d_validationContext, LogObject(prefix), false, wildcardLabelsCount);
```

---

### Workaround for operators

No configuration change disables the wildcard-proof check while preserving DNSSEC validation. A code fix is required.

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

When the answer has been expanded from a wildcard, we need to check that the next closer does not exist, and not that the qname does not. If the next closer does exist, the wildcard cannot be applied.

Fixes https://github.com/PowerDNS/pdns/issues/17136

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] read and accepted the [Developer Certificate of Origin](https://github.com/PowerDNS/pdns/blob/master/DCO) document, including the [AI Policy](https://github.com/PowerDNS/pdns/blob/master/AI_POLICY.md), and added a ["Signed-off-by"](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) to my commits
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [x] added or modified unit test(s)

### CODE REVIEW

File: pdns/validate.cc [hunk 1]
```diff
@@ -574,9 +574,24 @@ dState getDenial(const cspmap_t& validrrsets, const DNSName& qname, const uint16
...
+        if (!needWildcardProof) {
+          /* we are trying to prove that a wildcard can apply, so in effect we need to prove that the
+             next closer does not exist: the next closer can be different from the qname,
+             and can prevent the wildcard from applying.
+          */
+          nameToDeny = qname;
+          const auto chopCount = nameToDeny.countLabels() - wildcardLabelsCount - 1;
+          for (size_t idx = 0; idx < chopCount; ++idx) {
+            nameToDeny.chopOff();
+          }
```
Comment (miodvallat) [inline pdns/validate.cc:587]: I think that's
```suggestion
          nameToDeny.trimToLabels(wildcardLabelsCount + 1);
```

**Review by omoerbeek — APPROVED** [review]
