### PR TITLE
rec: improve dnssec record skipping for non dnssec queries

### LINKED ISSUE #4084: DNSPacketWriter::commit() called without startRecord ever having been called, but a record was added
Regression in 4.0 rc1 compared to 3-series:

`dig +noedns @10.10.7.77 nos-avg.cz. RRSIG` causes the following error in the logs:

```
DNS parser error (nos-avg.cz./RRSIG from 10.10.7.1): nos-avg.cz., DNSPacketWriter::commit() called without startRecord ever having been called, but a record was added
```

### PR DESCRIPTION
**Pull request by mind04**
successor of #4096

closes #4096
fixes #4084

### CODE REVIEW

File: pdns/pdns_recursor.cc [hunk 1]
```diff
@@ -1006,7 +1006,8 @@ void startDoResolve(void *p)
 
       bool needCommit = false;
       for(auto i=ret.cbegin(); i!=ret.cend(); ++i) {
-        if(!DNSSECOK && (i->d_type == QType::RRSIG || i->d_type==QType::NSEC || i->d_type==QType::NSEC3))
+        if(!DNSSECOK && ((((i->d_type == QType::RRSIG || i->d_type==QType::NSEC) && i->d_place != DNSResourceRecord::ANSWER) || i->d_type==QType::NSEC3) ||
+                        (i->d_type == QType::RRSIG && dc->d_mdp.d_qtype != i->d_type &&  dc->d_mdp.d_qtype != QType::ANY)))
```
Comment (Habbie) [inline pdns/pdns_recursor.cc]: Can we reformat this to more lines so the () levels are clearer? And can you replace the last `i->d_type` with `QType::RRSIG`? I think this would make the code easier to understand.

Otherwise LGTM.

**Comment by Habbie** [comment]
Note: first half already merged as #4096
