### PR TITLE
auth: Create additional `reuseport` sockets before dropping privileges

### LINKED ISSUE #1715: reuseport does not combine well with setuid=
I have `setuid=pdns`, `setgid=pdns`in my config

This results in:

```
/usr/sbin/pdns_server --daemon=no --guardian=no --reuseport=yes
Sep 16 13:31:31 Reading random entropy from '/dev/urandom'
Sep 16 13:31:31 This is a standalone pdns
Sep 16 13:31:31 Listening on controlsocket in '/var/run/pdns.controlsocket'
Sep 16 13:31:31 UDP server bound to 127.0.0.1:53
Sep 16 13:31:31 TCP server bound to 127.0.0.1:53
Sep 16 13:31:31 PowerDNS Authoritative Server UNKNOWN (mockbuild@dev-ruben.tilaa.nl) (C) 2001-2014 PowerDNS.COM BV
Sep 16 13:31:31 Using 64-bits mode. Built on 20140915211512 by mockbuild@dev-ruben.tilaa.nl, gcc 4.4.7 20120313 (Red Hat 4.4.7-4).
Sep 16 13:31:31 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Sep 16 13:31:31 Creating backend connection for TCP
Sep 16 13:31:31 About to create 3 backend threads for UDP
Sep 16 13:31:31 About to create 3 backend threads for UDP
Sep 16 13:31:31 About to create 3 backend threads for UDP
Sep 16 13:31:31 About to create 3 backend threads for UDP
Sep 16 13:31:32 Done launching threads, ready to distribute questions
Sep 16 13:31:32 Done launching threads, ready to distribute questions
Sep 16 13:31:32 binding UDP socket to '127.0.0.1:53: Permission denied
Sep 16 13:31:32 Done launching threads, ready to distribute questions
Sep 16 13:31:32 Done launching threads, ready to distribute questions
terminate called after throwing an instance of 'PDNSException'
Sep 16 13:31:32 Got a signal 6, attempting to print trace: 
Sep 16 13:31:32 binding UDP socket to '127.0.0.1:53: Permission denied
terminate called recursively
Sep 16 13:31:32 binding UDP socket to '127.0.0.1:53: Permission denied
terminate called recursively
Sep 16 13:31:32 Got a signal 6, attempting to print trace: 
Sep 16 13:31:32 Got a signal 6, attempting to print trace: 
Sep 16 13:31:32 /usr/sbin/pdns_server() [0x50391e]
Sep 16 13:31:32 /lib64/libc.so.6(+0x326b0) [0x7f8c5c1d06b0]
Sep 16 13:31:32 /lib64/libc.so.6(gsignal+0x35) [0x7f8c5c1d0635]
Sep 16 13:31:32 /lib64/libc.so.6(abort+0x175) [0x7f8c5c1d1e15]
Sep 16 13:31:32 /usr/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x12d) [0x7f8c5cca7a5d]
Sep 16 13:31:32 /usr/lib64/libstdc++.so.6(+0xbcbe6) [0x7f8c5cca5be6]
Sep 16 13:31:32 /usr/lib64/libstdc++.so.6(+0xbcc13) [0x7f8c5cca5c13]
Sep 16 13:31:32 /usr/lib64/libstdc++.so.6(+0xbcd0e) [0x7f8c5cca5d0e]
Sep 16 13:31:32 /usr/sbin/pdns_server(_ZN13UDPNameserver8bindIPv4Ev+0x791) [0x48c341]
Sep 16 13:31:32 /usr/sbin/pdns_server(_ZN13UDPNameserverC2Eb+0xde) [0x48d07e]
Sep 16 13:31:32 /usr/sbin/pdns_server(_Z7qthreadPv+0x332) [0x542ed2]
Sep 16 13:31:32 /lib64/libpthread.so.0(+0x79d1) [0x7f8c5c5399d1]
Sep 16 13:31:32 /lib64/libc.so.6(clone+0x6d) [0x7f8c5c28686d]
Aborted
```

Each thread does its own bind now, and since privileges are dropped, they can't bind to port 53.

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description
When `reuseport` support is enabled and available, we used to create additional sockets after dropping privileges, making impossible to use that feature in a `setuid` setup. This PR moves the additional sockets creation before dropping privileges.
Fixes #1715.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/receiver.cc [hunk 1]
```diff
@@ -605,8 +605,24 @@ int main(int argc, char **argv)
     }
 
     UeberBackend::go();
-    N=new UDPNameserver; // this fails when we are not root, throws exception
-    
+    N=std::make_shared<UDPNameserver>(); // this fails when we are not root, throws exception
```
Comment (Habbie) [inline pdns/receiver.cc]: Should this comment go then?

Comment (rgacogne) [inline pdns/receiver.cc]: It will still fail if we try to bind to a privileged port and don't have the relevant capabilities. This might happen if we are not started as root, for example.
