### PR TITLE
dnsdist: Fix the oustanding counter when an exception is raised

### LINKED ISSUE #5652: dnsdist 1.2.0 - negative values in web gui stats
Hi,

first of all - congrats to the new stable version! I have found a small issue so far: dnsdist 1.2.0 running for about 17 hours shows negative values of outgoing req. in web gui.

`#       Name    Address Status  Latency Queries Drops   QPS     Out     Weight  Order   Pools`
`0       beluga1 a.b.c.2:53      up      7       91783938        452810  2159    -78     100     1`
`1       beluga2 a.b.c.3:53      up      5       91783128        444472  2193    -67     100     1`
`2       beluga3 a.b.c.4:53      up      5       91793134        451395  2180    -96     100     1`
`3       beluga4 a.b.c.5:53      up      28      594399  1915    5       1       100     1       quarantine`
`4       murena4 a.b.c.37:53     up      27      593830  1800    6       0       100     1       quarantine`
`5       beluga1-ipv6    [x:x:x:x:1:2]:53        up      10      3362255 10574   66      1       100     1       ipv6_pool`
`6       beluga2-ipv6    [x:x:x:x:1:3]:53        up      7       3367511 10676   66      4       100     1       ipv6_pool`
`7       beluga3-ipv6    [x:x:x:x:1:4]:53        up      9       3368539 10726   89      2       100     1       ipv6_pool`
`8       beluga4-ipv6    [x:x:x:x:1:5]:53        up      0       0       0       0       0       100     1       ipv6_quarantine`
`9       murena4-ipv6    [x:x:x:y:1:5]:53        up      0       0       0       0       0       100     1       ipv6_quarantine`

Thanks

Aleš

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

If an exception is raised in the responder thread after the outstanding queries counter has been decremented, but before we could mark the state as processed, the same state would be processed again and the counter decremented a second time, either because of a duplicate answer or more likely by the timeout handler.
This commit simply increase back the outstanding counter when such an exception occurs. It might fixes #5652.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsdist.cc [hunk 1]
```diff
@@ -509,12 +511,21 @@ try {
...
 
       rewrittenResponse.clear();
     }
-    catch(std::exception& e){
+    catch(const std::exception& e){
       vinfolog("Got an error in UDP responder thread while parsing a response from %s, id %d: %s", state->remote.toStringWithPort(), queryId, e.what());
+      if (outstandingDecreased) {
+        /* so an exception was raised after we decreased the outstanding queries counter,
+           but before we could set ids->origFD to -1 (because we also set outstandingDecreased
+           to false then), meaning the IDS still considered active and we will decrease the
```
Comment (zeha) [inline pdns/dnsdist.cc]: `... the IDS still ...`  add `is` before `still`
