### PR TITLE
dnsdist: Fix release builds by updating the locked Rust lib version

### LINKED ISSUE #16177: dnsdist: Package building is broken
```
#32 34.32 error: the lock file /pdns/dnsdist-2.1.0-alpha0.870.master.gc64b979bc/dnsdist-rust-lib/rust/Cargo.lock needs to be updated but --locked was passed to prevent this
#32 34.32 If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Since we are now dynamically setting the version of our internal Rust library when generating the release tarball, `cargo` needs to update the `Cargo.lock` file to reflect the new version, which is not possible if we are passing `--locked`:
```
error: the lock file /pdns/dnsdist-2.1.0-alpha0.870.master.gc64b979bc/dnsdist-rust-lib/rust/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```
This commit fixes that also updating the `Cargo.lock` file when generating the release tarball so that `cargo` no longer needs to update the `Cargo.lock`.

Fixes #16177 

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] read and accepted the [Developer Certificate of Origin](https://github.com/PowerDNS/pdns/blob/master/DCO) document, including the [AI Policy](https://github.com/PowerDNS/pdns/blob/master/AI_POLICY.md), and added a ["Signed-off-by"](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) to my commits
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by omoerbeek — APPROVED** [review]
This looks good.I suppose rec suffers from the same.

File: pdns/dnsdistdist/meson-dist-script.sh [hunk 1]
```diff
@@ -53,6 +51,16 @@ meson compile rust-lib-sources
 cp -vp dnsdist-rust-lib/*.cc dnsdist-rust-lib/*.hh "$MESON_PROJECT_DIST_ROOT"/dnsdist-rust-lib/
 cp -vp "$MESON_SOURCE_ROOT"/dnsdist-rust-lib/rust/src/lib.rs "$MESON_PROJECT_DIST_ROOT"/dnsdist-rust-lib/rust/src/
 
+echo Updating the version of the Rust library to ${BUILDER_VERSION}
+"$MESON_SOURCE_ROOT"/../../builder-support/helpers/update-rust-library-version.py "$MESON_PROJECT_DIST_ROOT"/dnsdist-rust-lib/rust/Cargo.toml dnsdist-rust ${BUILDER_VERSION}
+# Update the version of the Rust library in Cargo.lock as well,
+# This needs to be done AFTER the sources of the Rust library have been generated
+# Unfortunately we cannot use --offline because for some reason cargo-update wants
+# to check all dependencies even though we are telling it exactly what to update
```
Comment (miodvallat) [inline pdns/dnsdistdist/meson-dist-script.sh:59]: Does this behaviour persist if adding `--workspace` to the `cargo update` commandline?

Comment (rgacogne) [reply pdns/dnsdistdist/meson-dist-script.sh:59]: Unfortunately it seems so, running `cargo update --workspace --offline --verbose --precise ${BUILDER_VERSION} dnsdist-rust`:

```
#20 17.74 error: no matching package named `serde` found
#20 17.74 location searched: registry `crates-io`
#20 17.74 required by package `dnsdist-rust v2.1.0-alpha0.872.ddistfixreleaserustupdate.gf0ed6f996 (/tmp/dnsdist-meson-dist-build/meson-dist/dnsdist-2.1.0-alpha0.872.ddistfixreleaserustupdate.gf0ed6f996/dnsdist-rust-lib/rust)`
#20 17.74 As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
```

Comment (miodvallat) [reply pdns/dnsdistdist/meson-dist-script.sh:59]: 🤷🏻
