### PR TITLE
auth: catalog, include groups in hash calculation

### LINKED ISSUE #13204: Catalog group editing does not increment the SOA serial in the catalog zone
- Program: Authoritative 
 - Issue type: Bug report

### Short description
If a catalog group is modified in a member zone, the SOA serial is not incremented in the corresponding catalog zone and slaves are not notified of that change.

### Environment

 - Operating system: Ubuntu 20.04.6
 - Software version: 4.7.4 (PostgreSQL backend is used)
 - Software source: PowerDNS repository

### Steps to reproduce

1. Set up an environment with a catalg zone and a member zone
2. Let slave servers configure member zone (optional)
3. Change the group in the member zone, e.g. via pdnsutil
    ```
    pdnsutil set-option example.com producer group testgroup
    ```

### Expected behaviour
The SOA serial in the catalog zone should be incremented in the same way as it is when listing or delisting a member zone.

### Actual behaviour
SOA serial is not incremented and these changes are not notified to slave servers.

### PR DESCRIPTION
**Pull request by mind04**
### Short description
fixes #13204

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/auth-catalogzone.cc [hunk 1]
```diff
@@ -108,6 +108,9 @@ std::string CatalogInfo::toJson() const
 void CatalogInfo::updateHash(CatalogHashMap& hashes, const DomainInfo& di) const
 {
   hashes[di.catalog].process(static_cast<char>(di.id) + di.zone.toLogString() + "\0" + d_coo.toLogString() + "\0" + d_unique.toLogString());
+  for (const auto& group : d_group) {
+    hashes[di.catalog].process(static_cast<char>(group.length()) + group);
```
Comment (omoerbeek) [inline pdns/auth-catalogzone.cc:112]: I find this a somewhat obscure construct. First I had to realize is `char + string` and not `char + char *`, which wold not work at all as expected. Why not use `std::to_string(group(length())`? Also, I do wonder why the length is explicitly hashed.
Similar issue with `static_cast<char>(di.id)` above. If `di.id` does not fit into a char you loose significant bits.

Comment (omoerbeek) [reply pdns/auth-catalogzone.cc:112]: Last comment: is it wise to create all the tmp strings? You could hash the individual parts separately, working with the raw presentation: `process(di.zone.getStorage())` etc...

**Review by Habbie — APPROVED** [review]

**Comment by Habbie** [comment]
rebased
