### PR TITLE
dnsdist: Better handling of multiple carbon servers

### LINKED ISSUE #10517: dnsdist: Carbon intervals are slightly off when exporting to multiple servers and one is unreachable
- Program: dnsdist
 - Issue type: Bug report

### Short description
When multiple Carbon servers are configured in dnsdist (with multiple "carbonServer" statements) and one is unreachable the reporting frequency to the remaining server(s) becomes unreliable, for example 32 seconds instead of 30 at random intervals, which causes some issues for reports that rely on exact data update intervals.

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: 1.5.2
 - Software source: PowerDNS repo (1.5.2-1pdns.bionic)

### Steps to reproduce

1. Configure at least two carbonServer's
2. Make one of them unreachable (timeout)
3. Validate reporting frequency to the remaining reachable carbon server

### Expected behaviour
Strict reporting interval

### Actual behaviour
Random reporting interval +/- a few seconds each..

### Other information
"As discussed."
Thanks. :wink:

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

This PR implements a refactoring of the Carbon handling in dnsdist. Each remote endpoint is now handled by its own thread, as to prevent a slow/unreachable server from impacting others.
It also implements an exponential back-off when a server cannot be reached properly, as to not overload a suffering endpoint.

Hopefully closes #10517 and #11216.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsdist-carbon.cc [hunk 1]
```diff
@@ -31,255 +31,321 @@
...
+  }
+  catch (const std::exception& e) {
+    warnlog("Problem sending carbon data to %s: %s", server.toStringWithPort(), e.what());
+    return false;
+  }
+
+  return true;
+}
+
+static void carbonHandler(Carbon::Endpoint endpoint)
```
[the remark this answers is not in the document]
Comment (omoerbeek) [reply pdns/dnsdist-carbon.cc:267]: A comment that this argument copy is needed would be nice, as not doing a call by value would break things. Potentially a call by ref and a local var copy would silence the warning and make intentions more clear.

File: pdns/dnsdist-carbon.cc [hunk 2]
```diff
@@ -31,255 +31,321 @@
...
         }
-        catch(const std::exception& e) {
-          warnlog("Problem sending carbon data: %s", e.what());
+        consecutiveFailures = 0;
+      }
+      else {
+        /* maximum interval between two attempts is 10 minutes */
+        const time_t maxBackOff = 10 * 60;
+        time_t backOff = 1;
+        double backOffTmp = std::pow(2.0, consecutiveFailures);
```
Comment (omoerbeek) [inline pdns/dnsdist-carbon.cc:292]: likely some static analysis tool will complain about the implicit `size_t` -> `double` conversion.

File: pdns/dnsdist-carbon.cc [hunk 3]
```diff
@@ -31,255 +31,321 @@
...
+  if (config->d_running) {
+    // we already started the threads, let's just spawn a new one
+    std::thread newHandler(carbonHandler, endpoint);
+    newHandler.detach();
   }
-  catch(const PDNSException& e)
-  {
-    errlog("Carbon thread died, PDNSException: %s", e.reason);
+  else {
+    config->d_endpoints.push_back(std::move(endpoint));
```
Comment (omoerbeek) [inline pdns/dnsdist-carbon.cc:331]: Should the endpoint only be pushed if not running? In that case you might as well clear the endpoint vector in `run()` as it is only used for the defered startup.

**Review by omoerbeek — APPROVED** [review]
A few nits

File: pdns/dnsdist-carbon.cc (hunk 3 above)
Comment (rgacogne) [reply pdns/dnsdist-carbon.cc:333]: Done!

**Comment by rgacogne** [comment]
I pushed a new commit:
- We now explicitly convert to double, making sure that we will not overflow by restricting the value of the counter
- Clear the endpoints list when the carbon threads are started, to make clear we do not need them anymore
- Move the endpoints passed to the carbon threads, to make static analysis tools happy.
