### PR TITLE
rec: When looking for a DS, skip NXD if the auth matches the qname

### LINKED ISSUE #5749: trafficmanager.net issue post 5716 (likely not needed for RC1)
Recursor, DNSSEC bug in validating domains within trafficmanager.net

### Short description
The following sequence breaks with 'dnssec=validate':
``` 
dig production.calling.skype.trafficmanager.net @127.0.0.1 -p 5400
sleep 15
dig trafficmanager.net @127.0.0.1 -p 5400
sleep 20
dig production.calling.skype.trafficmanager.net @127.0.0.1 -p 5400
```
Startup of pdns_recursor:
```
./pdns_recursor --local-port=5400 --socket-dir=./  --dnssec=validate --threads=1 --trace --packetcache-ttl=0
```

We should do better than this I am afraid. However, this issue is not super frequent and may be ok for RC1.

### Environment

 - Operating system: 
 - Software version: 
 - Software source: 

### Steps to reproduce

1. 
2. 
3.

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

When looking for a `DS`, ignore a cached `NXDOMAIN` answer whose `SOA` matches the exact domain we are looking the `DS` for.

Fixes #5749.
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [x] added or modified unit test(s)

### CODE REVIEW

File: pdns/syncres.cc [hunk 1]
```diff
@@ -948,17 +948,24 @@ bool SyncRes::doCacheCheck(const DNSName &qname, const QType &qtype, vector<DNSR
...
+       and ask for a specific denial instead */
+    if (qtype != QType::DS || ne.d_qtype.getCode() || ne.d_auth != qname ||
+        t_sstorage.negcache.get(qname, qtype, d_now, ne, true))
+    {
+      res = 0;
+      sttl = ne.d_ttd - d_now.tv_sec;
+      giveNegative = true;
+      cachedState = ne.d_validationState;
+      if(ne.d_qtype.getCode()) {
+        LOG(prefix<<qname<<": "<<qtype.getName()<<" is negatively cached via '"<<ne.d_auth<<"' for another "<<sttl<<" seconds"<<endl);
```
Comment (pieterlexis) [inline pdns/syncres.cc]: (not related to your PR) Shouldn't this line also contain the qtype for logging clarity?
