### PR TITLE
dnsdist: Fix cache hit and miss metrics with DoH queries

### LINKED ISSUE #12762: dnsdist: Pool metrics don't match global metrics (DoH cache misses/hits)
- Program: dnsdist
 - Issue type: Bug report

### Short description
Global counters are accurate, but the pool counters are not. Seems like a variation of #12405 still in play.

### Environment
 - Operating system: Debian
 - Software version:  git
 - Software source: semi-recently compiled

### Steps to reproduce
1. Setup dnsdist for DoH, add a pool cache, and blast it with queries
2. Check global and pool counters for cache hits/misses

### Expected behaviour
1. Similar type of numbers between global and pool

### Actual behaviour
1. Pool counters are incrementing both, global counters fine

```
> dumpStats()
acl-drops                          	          0    latency1-10                        	          0
cache-hits                         	       1247    latency10-50                       	          0
cache-misses                       	          1    latency100-1000                    	          0
```

```
> getPool(""):getCache():printStats()
Entries: 1/100000
Hits: 1247
Misses: 1248
```

### Other information
Similar issue as described in #12405, looks like global counters got updated, but maybe not pool counters.

Maybe this is just the way it has to work, which is also OK.

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Since we do two lookups for DoH queries forwarded over UDP (first TCP then UDP), we need to be careful to only record a cache miss in our last attempt.

Fixes #12762.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsdist.cc [hunk 1]
```diff
@@ -1347,7 +1347,9 @@ ProcessQueryResult processQueryAfterRules(DNSQuestion& dq, LocalHolders& holders
         forwardedOverUDP = false;
       }
 
-      if (dq.ids.packetCache->get(dq, dq.getHeader()->id, &dq.ids.cacheKey, dq.ids.subnet, dq.ids.dnssecOK, forwardedOverUDP, allowExpired, false, true, true)) {
+      /* we do not record a miss for queries received over DoH and forwarded over TCP
+         yet, as we will do a second-lookup */
+      if (dq.ids.packetCache->get(dq, dq.getHeader()->id, &dq.ids.cacheKey, dq.ids.subnet, dq.ids.dnssecOK, forwardedOverUDP, allowExpired, false, true, (dq.ids.protocol != dnsdist::Protocol::DoH || forwardedOverUDP) ? true : false)) {
```
Comment (omoerbeek) [inline pdns/dnsdist.cc:1352]:
```suggestion
      if (dq.ids.packetCache->get(dq, dq.getHeader()->id, &dq.ids.cacheKey, dq.ids.subnet, dq.ids.dnssecOK, forwardedOverUDP, allowExpired, false, true, dq.ids.protocol != dnsdist::Protocol::DoH || forwardedOverUDP) {
```

**Review by omoerbeek — APPROVED** [review]
One nit.
