### PR TITLE
rec: add feature to switch off unsupported DNSSEC algos

### LINKED ISSUE #12890: auth, rec: RSA-SHA1 broken on EL9
- Program: Authoritative, Recursor
 - Issue type: Bug report
- Affects: auth 4.8, rec 4.9
- 
### Short description
Red Hat has decided that RSASHA1 validation (and signing?) is, by default, [forbidden in EL9, even for DNSSEC](https://bugzilla.redhat.com/show_bug.cgi?id=2073068).

This breaks auth if a user has algo 5/7 keys:
```
# pdnsutil test-algorithms
Testing algorithm 5(RSASHA1): 'OpenSSL RSA' ->'OpenSSL RSA' -> 'OpenSSL RSA' (2048 bits) OpenSSL RSA: Could not initialize context for signing: 50331800:digital envelope routines::invalid digest - crypto/evp/m_sigver.c:343 - do_sigver_init
Testing algorithm 7(RSASHA1-NSEC3-SHA1): 'OpenSSL RSA' ->'OpenSSL RSA' -> 'OpenSSL RSA' (2048 bits) OpenSSL RSA: Could not initialize context for signing: 50331800:digital envelope routines::invalid digest - crypto/evp/m_sigver.c:343 - do_sigver_init
```

This breaks recursor - `icann.org`, which currently is signed with algo 7, is declared BOGUS.

### Workaround
Running `update-crypto-policies --set DEFAULT:SHA1` (and restarting affected daemons) makes the problem go away. `LEGACY` also works, but likely allows more things that users may not want. (you may need to `dnf install crypto-policies-scripts`)

### Handling in other software
For BIND, `update-crypto-policies` generates a snippet (included from `named.conf`) that explicitly disables the affected algorithms, which changes the outcome from Bogus to Insecure.

Unbound handles the failure case explicitly: https://github.com/nlnetLabs/unbound/commit/6cfcf214516b93622602684be5c3036bc1e3df1e

cznic libdnssec (gnutls, not openssl): https://gitlab.nic.cz/knot/knot-dns/-/commit/b0c6f0709aeab#3b7edfb68fbd436c6b46dcbb2c7a8c0cc6d5fd92_264_266

### Fixing this

Some proposals:

#### configurable DNSSEC policy

if we add support for a feature like `disable-algorithms=5,7` to Recursor, users at least have a quick workaround to go insecure for such keys without changing the systemwide policy. Configuration of that feature could maybe be integrated into the systemwide policy like RHEL has done for BIND.

#### detect the situation/handle the error

Either during validation handle the specific error (like Unbound does), or do a check at startup and then automatically disable the algorithms.

#### document it

We could also decide to just document that everything will be broken until the user updates the systemwide policy so OpenSSL allows RSA-SHA1 validation.

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

introduce a way to disable DNSSEC algos. Default is to determine automatically (for algos 5 and 7 only) . You can also set it manually by setting `"dnssec-disabled-algorithms` to a list of algorithm numbers.
Fixes #12890

On a Rocky Linux 9.2 system with default config:
`Jun 07 09:20:07 msg="Disabled DNSSEC algorithms" subsystem="config" level="0" prio="Notice" tid="0" ts="1686129607.324" algorithms="5 7"`
and [icann.org](http://icann.org/) is Insecure
And after setting the crypto policy to --set DEFAULT:SHA1 it does not print the log line and starts validating [icann.org](http://icann.org/)

You can get the status wit a new `rec_control command: list-dnssec-algos`. Example output:
`RSASHA1(disabled) RSASHA1-NSEC3-SHA1(disabled) RSASHA256 RSASHA512 ECDSAP256SHA256 ECDSAP384SHA384 ED25519 ED448`

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnssecinfra.cc [hunk 1]
```diff
@@ -291,6 +316,103 @@ bool DNSCryptoKeyEngine::testOne(int algo)
   return ret;
 }
 
+static map<string, string> ICSStringToMap(const string& argStr)
```
Comment (Habbie) [inline pdns/dnssecinfra.cc:319]: `ICS` should be `ISC`.

I know you did not introduce this duplication, but it looks like `DNSCryptoKeyEngine::makeFromISCString` might be reusable here. Not necessary for this PR.

File: pdns/dnssecinfra.cc [hunk 2]
```diff
@@ -364,6 +456,15 @@ void DNSCryptoKeyEngine::testMakers(unsigned int algo, maker_t* creator, maker_t
...
   unsigned int udiffSign= dt.udiff()/100, udiffVerify;
 
+#if 0
+  if (algo == 7) {
+    auto pubkey = Base64Encode(dckeSign->getPublicKeyString());
+    auto sig = Base64Encode(signature);
+    cerr << "PubKey: " << pubkey << endl;
+    cerr << "Signature: " << sig << endl;
+  }
+#endif
```
Comment (Habbie) [inline pdns/dnssecinfra.cc:466]: remove this?

File: pdns/recursordist/docs/settings.rst [hunk 3]
```diff
@@ -533,6 +533,23 @@ Set the mode for DNSSEC processing, as detailed in :doc:`dnssec`.
...
+- Comma separated list of DNSSEC algorithm numbers
+- Default: (none)
+
+A list of DNSSEC algorithm numbers that should be considered disabled.
+These algorithms will not be used to validate DNSSEC signatures.
+Zones (only) signed with these algorithms will be considered ``Insecure``.
+
+If this setting is empty (the default), :program:`Recursor` will determine which algorithms to disable automatically.
+This is important on systems that have a default strict crypto policy, like RHEL9 derived systems.
+On such systems not disabling some algorithms (or changing the security policy) will make affected zones to be considered ``Bogus`` as using these algorithms fails.
```
Comment (Habbie) [inline pdns/recursordist/docs/settings.rst:551]: maybe mention which algorithms we do the check for

**Review by Habbie — CHANGES_REQUESTED** [review]
just a few things

File: pdns/dnssecinfra.cc [hunk 4]
```diff
@@ -291,6 +316,103 @@ bool DNSCryptoKeyEngine::testOne(int algo)
...
+  string pubkey;
+  string sig;
+  B64Decode(b64pubkey, pubkey);
+  B64Decode(b64sig, sig);
+  auto dckeVerify = verifier(algo);
+  dckeVerify->fromPublicKeyString(pubkey);
+
+  auto ret = dckeVerify->verify(message, sig);
+  if (!ret) {
+    throw runtime_error("Verification of verifier "+dckeVerify->getName() + " failed");
```
Comment (rgacogne) [inline pdns/dnssecinfra.cc:397]: Would it make sense to return a boolean instead?

File: pdns/dnssecinfra.hh [hunk 5]
```diff
@@ -189,6 +194,7 @@ class DNSCryptoKeyEngine
       static allmakers_t s_allmakers;
       return s_allmakers;
     }
+    static std::unordered_set<unsigned int> s_switchedOff;
```
Comment (rgacogne) [inline pdns/dnssecinfra.hh:197]: Perhaps we could add a comment stating that this can only be altered at configuration time, when no other thread can touch it? Perhaps one day we could even automatically enforce that with a wrapper class that refuses to provide write access once the configuration phase is over?

**Review by rgacogne — APPROVED** [review]
A couple suggestions, but nothing that would prevent merging as it is.

File: pdns/dnssecinfra.cc (hunk 4 above)
Comment (omoerbeek) [reply pdns/dnssecinfra.cc]: done

File: pdns/dnssecinfra.hh (hunk 5 above)
Comment (omoerbeek) [reply pdns/dnssecinfra.hh:198]: done

File: pdns/recursordist/docs/settings.rst [hunk 6]
```diff
@@ -546,7 +546,10 @@ A list of DNSSEC algorithm numbers that should be considered disabled.
 These algorithms will not be used to validate DNSSEC signatures.
 Zones (only) signed with these algorithms will be considered ``Insecure``.
 
-If this setting is empty (the default), :program:`Recursor` will determine which algorithms to disable automatically.
+If this setting is empty (the default), :program:`Recursor` will determine which algorithms to
```
Comment (Habbie) [inline pdns/recursordist/docs/settings.rst:549]: you accidentally introduced a newline

File: pdns/dnssecinfra.cc [hunk 7]
```diff
@@ -393,21 +393,19 @@ void DNSCryptoKeyEngine::testVerify(unsigned int algo, maker_t* verifier)
...
 
 bool DNSCryptoKeyEngine::verifyOne(unsigned int algo)
 {
-  bool ret=true;
+  bool ret = false;
 
   for (auto* verifier : getAllMakers()[algo]) {
     try {
-      testVerify(algo, verifier);
+      ret = testVerify(algo, verifier);
```
Comment (rgacogne) [inline pdns/dnssecinfra.cc:405]: We might want to `break` when `ret` is `false`.

**Comment by omoerbeek** [comment]
I'll squash before merge

**Review by rgacogne — APPROVED** [review]
:+1:

**Review by Habbie — APPROVED** [review]
