### PR TITLE
rec: handle applicable dynamic parts of YAML only config when reloading Lua config

### LINKED ISSUE #16673: pdns-rec: new 5.4 tls_configurations option makes it impossible to use any Lua config
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [GitHub Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)
- [x] I have read and understood the [PowerDNS AI policy](https://github.com/PowerDNS/pdns/blob/master/AI_POLICY.md)

 - Program: Recursor 
 - Issue type: Bug report

### Short description

New yaml-only config options are marked as Lua config, making pdns-rec impossible to start if any other Lua config is in use.

### Environment

 - Operating system: Debian 13
 - Software version: 5.4.0-alpha1
 - Software source: PowerDNS repository

### Steps to reproduce

1. configure [`recursor.lua_config_file`](https://docs.powerdns.com/recursor/yamlsettings.html#recursor-lua-config-file) in `recursor.yml` (using for instance [`rpzPrimary`](https://doc.powerdns.com/recursor/lua-config/rpz.html#rpzPrimary) is very useful for an environment without dynamically generated config files, ie a simple loop instead of a lot of repetitive config)

2. configure [`outgoing.tls_configurations`](https://docs.powerdns.com/recursor/yamlsettings.html#setting-yaml-outgoing-tls-configurations) in `recursor.yml`

### Expected behaviour

Pdns-rec should run as there is no conflicting config (`tls_configurations` does not actually have any Lua counterpart)

### Actual behaviour

Pdns-rec refuses to start. Error message:
```
YAML settings include values originally in Lua but also sets `recursor.lua_config_file`. This is unsupported
```

### Other information

New yaml-only configuration options are flagged as Lua options, effectively making any use of Lua config impossible as pdns-rec cannot start if there is conflicting use of yaml/Lua config:

```
  alldefault = alldefault && settings.outgoing.tls_configurations.empty(); // actually not a Lua item, but very much alike
  alldefault = alldefault && settings.logging.opentelemetry_trace_conditions.empty(); // actually not a Lua item, but very much alike
```

https://github.com/PowerDNS/pdns/blob/rec-5.4.0-alpha1/pdns/recursordist/rec-rust-lib/cxxsupport.cc#L1432-L1433
https://github.com/PowerDNS/pdns/blob/rec-5.4.0-alpha1/pdns/recursordist/rec-rust-lib/cxxsupport.cc#L1457-L1458

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

Fixes #16673

This is all a bit tricky and in need of a more thorough refactoring. The existing regression tests exercise some of the reloading (see `test_Protobuf.py`). I modified the `SimpleForward` regression test to also use reloading, so more cases are covered. Setting this as ready for review. The refactoring can be done a a separate PR, maybe for next release.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] read and accepted the [Developer Certificate of Origin](https://github.com/PowerDNS/pdns/blob/master/DCO) document, including the [AI Policy](https://github.com/PowerDNS/pdns/blob/master/AI_POLICY.md), and added a ["Signed-off-by"](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) to my commits
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [X] documented the code
- [X] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/recursordist/rec_channel_rec.cc [hunk 1]
```diff
@@ -2075,32 +2075,69 @@ static RecursorControlChannel::Answer help(ArgIterator /* begin */, ArgIterator
...
+    // We might have a lua config file, but also process dynamic YAML parts if applicable, currently those are:
+    // - the OT trace conditions
+    // - the outgoing TLS config
     try {
-      if (::arg()["lua-config-file"].empty()) {
-        return {0, "No Lua or corresponding YAML configuration active\n"};
+      if (yamlstat == pdns::settings::rec::YamlSettingsStatus::OK) {
+        // YAML read above succeeded
+        ProxyMapping dummyProxyMapping; // taken from lua, so ignore YAML
+        LuaConfigItems dummyLuaConfig; // we do not use the converted orm YAML LuaConfigItems, but the "real thing"
```
Comment (rgacogne) [inline pdns/recursordist/rec_channel_rec.cc]:
```suggestion
        LuaConfigItems dummyLuaConfig; // we do not use the converted from YAML LuaConfigItems, but the "real thing"
```

File: pdns/recursordist/rec_channel_rec.cc [hunk 2]
```diff
@@ -2075,32 +2075,69 @@ static RecursorControlChannel::Answer help(ArgIterator /* begin */, ArgIterator
...
+        loadRecursorLuaConfig(::arg()["lua-config-file"], proxyMapping, lci); // will bump generation
       }
-      else {
-        // Initial proxy mapping
-        g_proxyMapping = proxyMapping.empty() ? nullptr : std::make_unique<ProxyMapping>(proxyMapping);
-      }
-      if (broadcast) {
-        g_slog->withName("config")->info(Logr::Info, "Reloaded");
+      activateLua(lci, broadcast, std::move(proxyMapping), std::move(conditions));
+      string msg = "Reloaded dynamic parts of YAML config";
```
Comment (rgacogne) [inline pdns/recursordist/rec_channel_rec.cc]:
```suggestion
      string msg = "Reloaded dynamic parts of YAML configuration";
```
for consistency.

**Comment by omoerbeek** [comment]
> Two nits but the changes look OK to me. I'm a bit out of my depth with the way the recursor's configuration works these days, though.

That's one of the reasons I'd like to do a refactor the next release cycle. Probably going to steal some ideas from dnsdist when I do that.
