### PR TITLE
auth SVCB fixes: avoid a crash; don't chase chains outside of zones

### LINKED ISSUE #10521: SERVFAIL with HTTPS record (lmdb backend)
- Program: Authoritative
 - Issue type: Bug report

### Short description
With `example.com IN HTTPS 0 foo.bar.com.`, queries are answered with SERVFAIL when a) the backend is lmdb, b) the zone is presigned (retrieved via AXFR). (Not sure if this is a necessary and/or sufficient set of conditions.)

### Environment
 - Operating system: Ubuntu 18.04
 - Software version: 4.4.0-1pdns.bionic
 - Software source: PowerDNS repository

### Steps to reproduce
@Habbie already reproduced (IRC on June 22, 2021).

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
fixes #10521

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

File: pdns/packethandler.cc [hunk 1]
```diff
@@ -512,7 +518,7 @@ void PacketHandler::doAdditionalProcessing(DNSPacket& p, std::unique_ptr<DNSPack
           if (content.isRoot()) {
             content = rr.dr.d_name;
           }
-          content = doAdditionalServiceProcessing(content, rr.dr.d_type, r);
+          content = doAdditionalServiceProcessing(content, rr.dr.d_type, r, extraRecords);
```
Comment (mind04) [inline pdns/packethandler.cc:521]:
```suggestion
          if (rrc->getPriority() == 0) {
            content = doAdditionalServiceProcessing(content, rr.dr.d_type, r, extraRecords);
          }
```
Only perform  AdditionalServiceProcessing for aliasform records.

**Review by pieterlexis — APPROVED** [review]
looks good, @mind04 made a nice comment :)
