### PR TITLE
dnsdist: Fix several signed/unsigned comparison warnings on ARM

### LINKED ISSUE #5489: dnsdist: signed/unsigned comparison warning
- Program: dnsdist
 - Issue type: Bug report

### Short description
it looks like the TimedIPSetRule does signed/unsigned comparisons:

```
In file included from dnsdist-lua.cc:26:0:
dnsrulactions.hh: In member function ‘virtual bool TimedIPSetRule::matches(const DNSQuestion*) const’:
dnsrulactions.hh:167:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       return time(0) < fnd->second;
                      ^
dnsrulactions.hh:174:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       return time(0) < fnd->second;
                      ^
dnsrulactions.hh: In member function ‘void TimedIPSetRule::cleanup()’:
dnsrulactions.hh:224:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(iter->second < now)
                  ^
dnsrulactions.hh:236:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(iter->second < now)
                  ^
dnsrulactions.hh: In member function ‘virtual std::string TimedIPSetRule::toString() const’:
dnsrulactions.hh:253:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if(now < ip.second)
                ^
dnsrulactions.hh:259:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if(now < ip.second)
                ^
```

Found when building dnsdist on raspbian (ARM)

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
Closes #5489

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsdist-tcp.cc [hunk 1]
```diff
@@ -190,7 +190,7 @@ static bool sendResponseToClient(int fd, const char* response, uint16_t response
 static bool maxConnectionDurationReached(unsigned int maxConnectionDuration, time_t start, unsigned int& remainingTime)
 {
   if (maxConnectionDuration) {
-    time_t elapsed = time(NULL) - start;
+    unsigned int elapsed = time(NULL) - start;
```
Comment (rgacogne) [inline pdns/dnsdist-tcp.cc]: It probably doesn't matter much but this would lead to closing the connection right away if the time goes backward, because then `elapsed` becomes huge instead of negative. Perhaps we should store `time(nullptr)`, and if it's lesser than `start` set `elapsed` to 0.
