### PR TITLE
rec: alternative way to do "skip cname check" for DS and DNSKEY records.

### LINKED ISSUE #9266: rec: CNAME record causes excessive DS and QNAME min queries
- Program: Recursor
 - Issue type: Bug report

### Short description
When the `DS` or QNAME minimization algorithms encounter a `CNAME` record, it seems to produce several `DS` or `A` queries, not just 1.

In the example below, of `dig _http._tcp.repo.powerdns.com srv`, there are 4 `DS` queries for `repo.powerdns.com` and 2 `A` queries.

I have a suspicion it depends on the number of labels -- that `foo._http._tcp.repo.powerdns.com` might add an extra round of queries -- but I haven't confirmed it.

### Environment
 - Operating system: Ubuntu 16.04 x86-64
 - Software version: 4.4.0~alpha1+master.270.ga42b446d6-1pdns.xenial
 - Software source: PowerDNS repository

### Steps to reproduce
1. `sudo rec_control wipe-cache 'powerdns.com$'`
2. `sudo rec_control trace-regex 'powerdns\.com\.$'`
3. `dig _http._tcp.repo.powerdns.com srv`

### Expected behaviour
1 `DS` query, 1 `A` query.

### Actual behaviour
tcpdump:

```
2020-06-22 07:25:00.791483 IP6 ::1.51574 > ::1.53: 18765+ [1au] SRV? _http._tcp.repo.powerdns.com. (69)
2020-06-22 07:25:00.792324 IP6 2600:3c02:e000:bc::3.31763 > 2001:503:a83e::2:30.53: 37495 [1au] DS? powerdns.com. (41)
2020-06-22 07:25:00.805286 IP6 2001:503:a83e::2:30.53 > 2600:3c02:e000:bc::3.31763: 37495*- 4/14/21 DS, DS, DS, RRSIG (1227)
2020-06-22 07:25:00.806464 IP 45.33.103.94.19811 > 192.33.14.30.53: 34831 [1au] A? powerdns.com. (41)
2020-06-22 07:25:00.998294 IP 192.33.14.30.53 > 45.33.103.94.19811: 34831- 0/6/5 (516)
2020-06-22 07:25:00.999195 IP 45.33.103.94.33554 > 188.166.104.87.53: 24418 [1au] DS? repo.powerdns.com. (46)
2020-06-22 07:25:01.091544 IP 188.166.104.87.53 > 45.33.103.94.33554: 24418*- 2/4/1 CNAME repo1.powerdns.com., RRSIG (687)
2020-06-22 07:25:01.092123 IP6 2600:3c02:e000:bc::3.29059 > 2a03:b0c0:2:d0::4af:b001.53: 22912 [1au] DNSKEY? powerdns.com. (41)
2020-06-22 07:25:01.184361 IP6 2a03:b0c0:2:d0::4af:b001.53 > 2600:3c02:e000:bc::3.29059: 22912*- 3/0/1 DNSKEY, DNSKEY, RRSIG (765)
2020-06-22 07:25:01.185617 IP6 2600:3c02:e000:bc::3.44474 > 2604:a880:1:20::132:5001.53: 41482 [1au] A? repo.powerdns.com. (46)
2020-06-22 07:25:01.260944 IP6 2604:a880:1:20::132:5001.53 > 2600:3c02:e000:bc::3.44474: 41482*- 4/0/1 CNAME repo1.powerdns.com., RRSIG, RRSIG, A 188.166.116.224 (426)
2020-06-22 07:25:01.261695 IP 45.33.103.94.50373 > 45.55.10.200.53: 7106 [1au] DS? repo1.powerdns.com. (47)
2020-06-22 07:25:01.335691 IP 45.55.10.200.53 > 45.33.103.94.50373: 7106*- 0/4/1 (496)
2020-06-22 07:25:01.336505 IP 45.33.103.94.49796 > 45.55.10.200.53: 57372 [1au] A? repo1.powerdns.com. (47)
2020-06-22 07:25:01.400377 IP 45.55.10.200.53 > 45.33.103.94.49796: 57372*- 2/0/1 A 188.166.116.224, RRSIG (235)
2020-06-22 07:25:01.401087 IP 45.33.103.94.60958 > 45.55.10.200.53: 25903 [1au] DS? repo.powerdns.com. (46)
2020-06-22 07:25:01.474862 IP 45.55.10.200.53 > 45.33.103.94.60958: 25903*- 2/4/1 CNAME repo1.powerdns.com., RRSIG (687)
2020-06-22 07:25:01.475808 IP 45.33.103.94.39059 > 45.55.10.200.53: 65090 [1au] DS? repo.powerdns.com. (46)
2020-06-22 07:25:01.548580 IP 45.55.10.200.53 > 45.33.103.94.39059: 65090*- 2/4/1 CNAME repo1.powerdns.com., RRSIG (687)
2020-06-22 07:25:01.549466 IP 45.33.103.94.52276 > 45.55.10.200.53: 48371 [1au] A? repo.powerdns.com. (46)
2020-06-22 07:25:01.613042 IP 45.55.10.200.53 > 45.33.103.94.52276: 48371*- 4/0/1 RRSIG, CNAME repo1.powerdns.com., RRSIG, A 188.166.116.224 (426)
2020-06-22 07:25:01.613896 IP 45.33.103.94.28094 > 45.55.10.200.53: 56222 [1au] DS? repo.powerdns.com. (46)
2020-06-22 07:25:01.677149 IP 45.55.10.200.53 > 45.33.103.94.28094: 56222*- 2/4/1 CNAME repo1.powerdns.com., RRSIG (687)
2020-06-22 07:25:01.677962 IP 45.33.103.94.1775 > 45.55.10.200.53: 36825 [1au] DS? _tcp.repo.powerdns.com. (51)
2020-06-22 07:25:01.741381 IP 45.55.10.200.53 > 45.33.103.94.1775: 36825 NXDomain*- 0/4/1 (507)
2020-06-22 07:25:01.742297 IP 45.33.103.94.28058 > 45.55.10.200.53: 41010 [1au] A? _tcp.repo.powerdns.com. (51)
2020-06-22 07:25:01.815968 IP 45.55.10.200.53 > 45.33.103.94.28058: 41010 NXDomain*- 0/4/1 (507)
2020-06-22 07:25:01.836167 IP6 ::1.53 > ::1.51574: 18765 NXDomain$ 0/1/1 (122)
```

### Other information
`trace-regex` log: https://mn0.us/fNA6hZBMxJznVcMfpk_Fow6/syslog.txt

`recursor.conf`:

```
allow-from=127.0.0.0/8, ::1/128, 2600:3c02::13:0/116, 2600:3c02::13:5000/116, 2600:3c02::f03c:91ff:fe70:fd08/128, 2600:3c02::f03c:91ff:febc:a28b/128, 2600:3c02:e000:74::/64, 2600:3c02:e000:bc::/64
allow-trust-anchor-query
carbon-ourname=jane_mattnordhoff_net
carbon-server=2a02:2770:8::2635:0:1
config-dir=/etc/powerdns
dnssec=validate
dnssec-log-bogus
hint-file=/usr/share/dns/root.hints
include-dir=/etc/powerdns/recursor.d
local-address=127.0.0.1, ::1, 2600:3c02::13:5210
log-common-errors
lua-config-file=/etc/powerdns/recursor.lua
max-cache-ttl=172800
max-negative-ttl=10800
query-local-address=0.0.0.0, ::
quiet=yes
setgid=pdns
setuid=pdns
threads=1
```

`recursor.d` is empty and `recursor.lua` is stock.

### PR DESCRIPTION
**Pull request by omoerbeek**
The current code effectively disables lookup of cached CNAME results
for zone cut computations, which results in more queries than needed.

Should fix #9266 or at least give more insight.

Needs critical eyes badly!

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

File: pdns/syncres.cc [hunk 1]
```diff
@@ -1238,6 +1238,10 @@ bool SyncRes::doCNAMECacheCheck(const DNSName &qname, const QType &qtype, vector
     return false;
   }
 
+  if (qtype == QType::DS || qtype == QType::DNSKEY) {
```
Comment (rgacogne) [inline pdns/syncres.cc:1241]: I wonder if that check is not done too soon? That does skip just-in-time DNSSEC validation, for example, perhaps we should do it later as done in https://github.com/PowerDNS/pdns/commit/b0d6e4085102a4cff5105ba02cea91d0bbf7d937 ?
