### PR TITLE
dnsdist: Make custom LuaAction and LuaResponsAction second return value optional

### LINKED ISSUE #6346: LuaAction is underdocumented
- Program: dnsdist
 - Issue type: Bug report

### Short description
https://dnsdist.org/rules-actions.html#addLuaAction which links to https://dnsdist.org/reference/constants.html#dnsaction suggests that the Lua function should return a single value, being one of the `DNSAction` constants. However, this fails with `LuaAction failed inside lua, returning ServFail: Trying to cast a lua variable from "number" to "NSt3__15tupleIJiNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEE"` because dnsdist expects that constant plus a string. The `dnsdistconf.lua` example script in the repo does show this.

### Environment
 - Operating system: 
 - Software version: git master as of 385aa46087553fcb5deebaf8c2b1de293289d947
 - Software source: git

### Steps to reproduce
1. `dnsdist.conf`: (compare to the version in #6348 which does work as far as *this* ticket is concerned)
```
newServer('8.8.8.8')
function luarule(dq) if (dq.qtype==dnsdist.NAPTR) then return DNSAction.Nxdomain else return DNSAction.Allow end end
addLuaAction(AllRule(), luarule)
```
2. `[sudo] ./dnsdist -C dnsdist.conf`
3. send any query to dnsdist

### Expected behaviour
A spoofed `NXDOMAIN` for NAPTR queries, normal processing otherwise.

### Actual behaviour
dnsdist reports `LuaAction failed inside lua, returning ServFail: Trying to cast a lua variable from "number" to "NSt3__15tupleIJiNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEE"` and the client receives a SERVFAIL.

### Other information
Proposed fixes (why not both):
1. Improve the documentation in this area.
2. Make the second return value optional for cases where it does not make sense (I think `Nxdomain` would qualify for that).

### PR DESCRIPTION
**Pull request by chbruyand**
### Short description
Make custom LuaAction and LuaResponsAction second return value optional.
This allows shorter return syntax for custom lua actions : `return DNSAction.None` instead of `return DNSAction.None, ""`.

Fix #6346 

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [x] included documentation (including possible behaviour changes)
- [x] documented the code
- [x] added or modified regression test(s)
- [  ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsdist-lua.hh [hunk 1]
```diff
@@ -24,7 +24,7 @@
 class LuaAction : public DNSAction
 {
 public:
-  typedef std::function<std::tuple<int, string>(DNSQuestion* dq)> func_t;
+  typedef std::function<std::tuple<int, boost::optional<string> >(DNSQuestion* dr)> func_t;
```
Comment (rgacogne) [inline pdns/dnsdist-lua.hh]: Just a nit but `dq` made more sense than `dr` here :)

File: pdns/dnsdistdist/docs/reference/constants.rst [hunk 2]
```diff
@@ -83,4 +83,21 @@ These constants represent an Action that can be returned from the functions invo
...
+
+
+.. _DNSResponseAction:
+
+DNSResponseAction
+-----------------
+
+These constants represent an Action that can be returned from the functions invoked by :func:`addLuaResponseAction`.
+
+ * ``DNSResponseAction.Allow``: let the query pass, skipping other rules
```
Comment (rgacogne) [inline pdns/dnsdistdist/docs/reference/constants.rst]: s/query/response/

File: pdns/dnsdistdist/docs/reference/constants.rst [hunk 3]
```diff
@@ -83,4 +83,21 @@ These constants represent an Action that can be returned from the functions invo
...
+ * ``DNSResponseAction.Delay``: delay the response for the specified milliseconds (UDP-only), continue to the next rule
+ * ``DNSResponseAction.Drop``: drop the query
```
Comment (rgacogne) [inline pdns/dnsdistdist/docs/reference/constants.rst]: s/query/response/

File: pdns/dnsdistdist/docs/rules-actions.rst [hunk 4]
```diff
@@ -150,7 +150,9 @@ Rule Generators
 
   Invoke a Lua function that accepts a :class:`DNSQuestion`.
   This function works similar to using :func:`LuaAction`.
-  The ``function`` should return a :ref:`DNSAction`. If the Lua code fails, ServFail is returned.
+  The ``function`` should return both a :ref:`DNSAction` and its argument `rule`. The `rule` is used as an argument
+  of the following :ref:`DNSAction`: `DNSAction.Spoof`, `DNSAction.Pool` and `DNSAction.Delay`. As of version `1.3.0`, you can
+  ommit the argument. For earlier releases, simply return an empty string. If the Lua code fails, ServFail is returned.
```
Comment (rgacogne) [inline pdns/dnsdistdist/docs/rules-actions.rst]: s/ommit/omit/

File: pdns/dnsdistdist/docs/rules-actions.rst [hunk 5]
```diff
@@ -160,14 +162,30 @@ Rule Generators
 
   * ``uuid``: string - UUID to assign to the new rule. By default a random UUID is generated for each rule.
 
+  ::
+
+    function luarule(dq)
+      if(dq.qtype==35) -- NAPTR
```
Comment (rgacogne) [inline pdns/dnsdistdist/docs/rules-actions.rst]: Wouldn't `dnsdist.NAPTR` work here?

File: pdns/dnsdistdist/docs/rules-actions.rst [hunk 6]
```diff
@@ -160,14 +162,30 @@ Rule Generators
...
 .. function:: addLuaResponseAction(DNSrule, function [, options])
 
   .. versionchanged:: 1.3.0
     Added the optional parameter ``options``.
 
   Invoke a Lua function that accepts a :class:`DNSResponse`.
   This function works similar to using :func:`LuaResponseAction`.
-  The ``function`` should return a :ref:`DNSResponseAction`. If the Lua code fails, ServFail is returned.
+  The ``function`` should return both a :ref:`DNSResponseAction` and its argument `rule`. The `rule` is used as an argument
+  of the `DNSResponseAction.Delay`. As of version `1.3.0`, you can ommit the argument (see :func:`addLuaAction`). For earlier
```
Comment (rgacogne) [inline pdns/dnsdistdist/docs/rules-actions.rst]: s/ommit/omit/

File: regression-tests.dnsdist/test_Advanced.py [hunk 7]
```diff
@@ -1279,6 +1279,42 @@ def testRefusedViaLua(self):
...
+    end
+    addAction(AllRule(), LuaAction(refuse))
+    newServer{address="127.0.0.1:%s"}
+    """
+
+    def testRefusedWithEmptyRule(self):
+        """
+        Advanced: Short syntax for LuaAction return values
+        """
+        name = 'refused.advanced.tests.powerdns.com.'
```
Comment (rgacogne) [inline regression-tests.dnsdist/test_Advanced.py]: Would you mind using a different qname than the previous test? It often makes debugging easier.
