### PR TITLE
verify parts.size(). Fixes #5688

### LINKED ISSUE #5688: Segfault#2 in pdnsutil check-zone
Sample data from postgresql:

```
insert into domains (name, type) values ('example.com', 'NATIVE'); 
insert into records (domain_id, type, name, content) values (currval('domains_id_seq'), 'SOA', 'example.com', 'ns1.example.com admin.example.com 2017010100 3600 600 1209600 3600');
insert into records (domain_id, name, type, ttl, prio, content) values (currval('domains_id_seq'), 'ns.example.com', 'A', 3600, default, '127.0.0.1');
insert into records (domain_id, name, type, ttl, prio, content) values (currval('domains_id_seq'), 'example.com', 'NS', 3600, default, 'ns.example.com');
insert into records (domain_id, type, name, content, ttl, prio) values (currval('domains_id_seq'), 'SRV', 'example.com', '0 443example.com', 3600, 10);
```
```
[root@localhost ~]# pdnsutil check-zone example.com
[Warning] Parsed and original record content are not equal: example.com IN SRV '0 0 443example.com' (Content parsed as '0 0 443 example.com')
Segmentation fault
```

Again, prio plays a role
```
update records set prio = null where domain_id = currval('domains_id_seq') and type = 'SRV';
```
```
[root@localhost ~]# pdnsutil check-zone example.com
[Error] Following record had a problem: example.com IN SRV  0 443example.com
[Error] Error was: Parsing record content (try 'pdnsutil check-zone'): expected digits at position 6 in ' 0 443example.com'
Checked 5 records of 'example.com', 2 errors, 0 warnings.
```

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
We would read out of bounds if SRV or MX content did not have enough parts.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

File: pdns/pdnsutil.cc [hunk 1]
```diff
@@ -584,16 +584,16 @@ int checkZone(DNSSECKeeper &dk, UeberBackend &B, const DNSName& zone, const vect
...
         vector<string> parts;
         stringtok(parts, rr.getZoneRepresentation());
-        toCheck = DNSName(parts[1]);
+        if (parts.size() == 2) toCheck = DNSName(parts[1]);
       } else {
         toCheck = DNSName(rr.content);
       }
 
-      if (!toCheck.isHostname()) {
+      if (!toCheck.empty() && !toCheck.isHostname()) {
```
Comment (rgacogne) [inline pdns/pdnsutil.cc]: Perhaps we should display a warning if the hostname is empty? Something like:

` if (toCheck.empty() || !toCheck.isHostname()) {`

Comment (Habbie) [reply pdns/pdnsutil.cc]: I pondered that, but I couldn't imagine a code path that ends with an empty `toCheck` without having given some other warning before. But it doesn't hurt to check, so I'll fix it.

Comment (Habbie) [reply pdns/pdnsutil.cc]: pushed!
