### PR TITLE
Fix ipv*hint=auto on lmdb backend

### LINKED ISSUE #12653: auth: Following the SVCB guide results in a broken zone
- Program: Authoritative
 - Issue type: Bug report

### Short description
Inserting the zone content from https://docs.powerdns.com/authoritative/guides/svcb.html#automatic-hints via `pdnsutil edit-zone` results in a broken zone (cannot be edited anymore via pdnsutil).

### Environment

 - Operating system: Arch Linux
 - Software version: master / 4c5f1277cf0a2fde0cf3cfb3f5d97b9104e932b6
 - Software source: git
 - LMDB backend

### Steps to reproduce
```
$ pdnsutil create-zone sigsegv1.fr
Creating empty zone 'sigsegv1.fr'
$ pdnsutil edit-zone sigsegv1.fr
[Error] No NS record at zone apex in zone 'sigsegv1.fr'
Checked 8 records of 'sigsegv1.fr', 1 errors, 0 warnings.

There was a problem with your zone
Options are: (e)dit your changes, (r)etry with original zone, (a)pply change anyhow, (q)uit: a
Detected the following changes:
+sigsegv1.fr 3600 IN HTTPS 0 www.sigsegv1.fr
+ipv6.sigsegv1.fr 3600 IN AAAA 2001:db8::2
+ipv6.sigsegv1.fr 3600 IN AAAA 2001:db8::3
+ipv6.sigsegv1.fr 3600 IN HTTPS 1 . ipv6hint=auto
+www.sigsegv1.fr 3600 IN A 192.0.2.1
+www.sigsegv1.fr 3600 IN AAAA 2001:db8::1
+www.sigsegv1.fr 3600 IN HTTPS 1 . ipv4hint=auto

You have not updated the SOA record! Would you like to increase-serial?
(y)es - increase serial, (n)o - leave SOA record as is, (e)dit your changes, (q)uit: y
(a)pply these changes, (e)dit again, (r)etry with original zone, (q)uit: a
Adding empty non-terminals for non-DNSSEC zone 'sigsegv1.fr', 3 updates
$ pdnsutil check-zone sigsegv1.fr
[Error] Following record had a problem: "ipv6.sigsegv1.fr IN HTTPS 1 . ipv6hint="
[Error] Error was: Parsing record content (try 'pdnsutil check-zone'): expected value after ipv6hint=
[Error] Following record had a problem: "www.sigsegv1.fr IN HTTPS 1 . ipv4hint="
[Error] Error was: Parsing record content (try 'pdnsutil check-zone'): expected value after ipv4hint=
[Error] No NS record at zone apex in zone 'sigsegv1.fr'
Checked 8 records of 'sigsegv1.fr', 3 errors, 0 warnings.
$ pdnsutil check-zone sigsegv1.fr
[Error] Following record had a problem: "ipv6.sigsegv1.fr IN HTTPS 1 . ipv6hint="
[Error] Error was: Parsing record content (try 'pdnsutil check-zone'): expected value after ipv6hint=
[Error] Following record had a problem: "www.sigsegv1.fr IN HTTPS 1 . ipv4hint="
[Error] Error was: Parsing record content (try 'pdnsutil check-zone'): expected value after ipv4hint=
[Error] No NS record at zone apex in zone 'sigsegv1.fr'
Checked 8 records of 'sigsegv1.fr', 3 errors, 0 warnings.
$ pdnsutil edit-zone sigsegv1.fr
Error: Parsing record content (try 'pdnsutil check-zone'): expected value after ipv6hint=
$
```

### PR DESCRIPTION
**Pull request by miodvallat**
### Short description

This is an attempt to fix #12653. When using LMDB as backend, DNS records are serialized using `GenericDNSPacketWriter<>::xfrSvcParamKeyVals`, which writes no value in the "auto" case. Thus, when reading back with `PacketReader::xfrSvcParamKeyVals`, we should handle an empty value as the absent serialization of "auto".

Note that this does not change the way data is serialized, so there should be no interoperability problem caused by this.

- [x] TODO: add tests to demonstrate this

### Checklist
I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by miodvallat** [comment]
> This looks ook for internal serialization for lmdb purposes, but if I'm not mistaken this case is also used to deserialize packets coming from the net. [7.3](https://www.rfc-editor.org/rfc/rfc9460.html#section-7.3) specifies the address sequences should have size >= 1. I'm not sure if setting `auto` in the case we receive an empty address sequence is right.

You're right. I don't know (yet) whether we can tell apart the origin of the data when deserializing, so as to correctly reject data coming from the wire.

**Comment by miodvallat** [comment]
This new flavour will only allow interpreting empty hints as "auto" if the data comes from the lmdb backend. It's a tad intrusive but ought to work as intended.

File: pdns/dnsparser.cc [hunk 1]
```diff
@@ -80,7 +80,7 @@ void UnknownRecordContent::toPacket(DNSPacketWriter& pw) const
   pw.xfrBlob(string(d_record.begin(),d_record.end()));
 }
 
-shared_ptr<DNSRecordContent> DNSRecordContent::deserialize(const DNSName& qname, uint16_t qtype, const string& serialized, uint16_t qclass)
+shared_ptr<DNSRecordContent> DNSRecordContent::deserialize(const DNSName& qname, uint16_t qtype, const string& serialized, uint16_t qclass, bool trusted)
```
Comment (rgacogne) [inline pdns/dnsparser.cc:83]: Small nit: I'm not a big fan of using `trusted` for this variable name, I'm pretty sure the next person reading this code will wonder what that means exactly. Perhaps something like `internalRepresentation`?

Comment (miodvallat) [reply pdns/dnsparser.cc:83]: It's (currently) `trusted` for "coming from a trusted source". I had also considered using a `bool` with a reverse polarity, which would be called `fromWire` - would you prefer that?

Comment (rgacogne) [reply pdns/dnsparser.cc:83]: Yeah, I think it would be better. What I'm worried about with `trusted` is that at some point someone interprets it as "coming from a trusted source, possibly over the network" which is not what we want. We could also write a comment, which might actually be a good idea, something like:
> fromWire is set to false when the content comes is deserialized from an internal source, like the LMDB backend.

Comment (Habbie) [reply pdns/dnsparser.cc:83]: fromWire is tricky, as LMDB also is "wire format", but I think it at least is clearer than `trusted`. `internalRepresentation` is not too bad

Comment (omoerbeek) [reply pdns/dnsparser.cc:83]: fromLMDB? Or is that too narrow?

Comment (Habbie) [reply pdns/dnsparser.cc:83]: too narrow. LMDB is not even the only backend that uses wire storage (tinydns is the other one), and one day we might add even more.

Saying that out loud makes me realise that once a test is added, we might indeed find the same problem with tinydns - which then should be easy to fix.

Comment (omoerbeek) [reply pdns/dnsparser.cc]: last bid: `fromBackend` :)

Comment (miodvallat) [reply pdns/dnsparser.cc]: I went with `internalRepresentation` which has two votes (we're outnumbered, Otto!)

**Comment by miodvallat** [comment]
Disclaimer: be sure to have your barf bag ready when looking at the python test changes.

**Comment by Habbie** [comment]
> Disclaimer: be sure to have your barf bag ready when looking at the python test changes.

I guess the testing framework is unable to pick up inherited methods?

**Comment by miodvallat** [comment]
No, the main problem is that this is probably not the right place to perform these tests, and I'm {ab,re}using a test setup which probably does not make sense with an lmdb backend.

**Comment by Habbie** [comment]
Right, these would be easier to test in `regression-tests/` I think. When we get rid of that dir entirely, and thus have a decent (Python based?) framework for simple 'does query X yield response Y' testing, perhaps this PR can also be rewritten into it.

**Review by Habbie — APPROVED** [review]
