### PR TITLE
Auth: Incremental backoff for failed slave checks

### LINKED ISSUE #349: slave domain needs checking - mass repeating
Hi,

as already discussed on channel, there seems to be some incorrect timeout values for rechecking failed AXFR, even though `slave-cycle-interval` is set to a good value (like 86400).

After doing an `rndc reload` on the master server, this was the first message:

```
Mar 31 10:50:13 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:13 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:13 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
```

Since then, it repeats every three seconds:

```
Mar 31 10:50:16 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:17 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:17 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 10:50:20 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:20 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:20 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 10:50:23 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:24 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:24 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 10:50:27 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:27 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:27 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 10:50:30 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:31 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:31 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 10:50:34 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:35 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:35 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 10:50:38 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:38 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:38 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 10:50:41 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:42 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:42 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 10:50:45 s-dns pdns[4167]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 10:50:45 s-dns pdns[4167]: gmysql Connection successful
Mar 31 10:50:45 s-dns pdns[4167]: 1 slave domain needs checking, 0 queued for AXFR
```

and has yet not stopped:

```
Mar 31 11:33:33 s-dns pdns[4730]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 11:33:33 s-dns pdns[4730]: gmysql Connection successful
Mar 31 11:33:33 s-dns pdns[4730]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 11:33:36 s-dns pdns[4730]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 11:33:36 s-dns pdns[4730]: gmysql Connection successful
Mar 31 11:33:36 s-dns pdns[4730]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 11:33:39 s-dns pdns[4730]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 11:33:40 s-dns pdns[4730]: gmysql Connection successful
Mar 31 11:33:40 s-dns pdns[4730]: 1 slave domain needs checking, 0 queued for AXFR
Mar 31 11:33:43 s-dns pdns[4730]: Received serial number updates for 0 zones, had 1 timeouts
Mar 31 11:33:43 s-dns pdns[4730]: gmysql Connection successful
Mar 31 11:33:43 s-dns pdns[4730]: 1 slave domain needs checking, 0 queued for AXFR
```

It doesn't seem to reduce performance of the pdns itself, but it's blowing the logfile up and renders it unreadable.

### LINKED ISSUE #602: removed domains checked very often from slave
If a type=SLAVE domain has been removed from a master, and thus the SOA check returns rcode=9 or the like, the domain will be rechecked every slave cycle.

Worse, slave-cycle-interval (default 60 seconds) can be interrupted by many events for single domains, but the wakeup will cause this recheck for all failing domains. Busy slaves might re-check their failed domains every few seconds because of this.

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
When we cannot retrieve the SOA record for a slave domain, use an increasing interval between checking the domain again. This prevents hammering down or already busy servers.
Closes #349
Closes #602

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added regression tests
- [ ] added unit tests
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by mind04** [comment]
Is soa-retry-default not a better value for the backoff time if you cannot retreive a soa? With the current max 60 * slave-cycle-interval the backoff time will grow quickly if you increase slave-cycle-interval  (1 hour = max 2.5 days).

File: pdns/slavecommunicator.cc [hunk 1]
```diff
@@ -748,8 +748,13 @@ void CommunicatorClass::slaveRefresh(PacketHandler *P)
   {
     Lock l(&d_lock);
     domains_by_name_t& nameindex=boost::multi_index::get<IDTag>(d_suckdomains);
+    time_t now = time(0);
 
     for(DomainInfo& di :  rdomains) {
+      auto failed = d_failedSlaveRefresh.find(di.zone);
```
Comment (Habbie) [inline pdns/slavecommunicator.cc]: const? &?

File: pdns/slavecommunicator.cc [hunk 2]
```diff
@@ -748,8 +748,13 @@ void CommunicatorClass::slaveRefresh(PacketHandler *P)
...
+      if (failed != d_failedSlaveRefresh.end() && now < failed->second.second )
+        // If the domain has fialed before and the time before the next check has not expired, skip this domain
```
Comment (Habbie) [inline pdns/slavecommunicator.cc]: fialed

File: pdns/slavecommunicator.cc [hunk 3]
```diff
@@ -836,8 +842,24 @@ void CommunicatorClass::slaveRefresh(PacketHandler *P)
         continue;
     }
 
-    if(!ssr.d_freshness.count(di.id)) // what does this mean? XXX
+    if(!ssr.d_freshness.count(di.id)) { // If we don't have an answer for the domain
+      uint64_t newCount = 1;
+      auto failedEntry = d_failedSlaveRefresh.find(di.zone);
```
Comment (Habbie) [inline pdns/slavecommunicator.cc]: const? &?

File: pdns/slavecommunicator.cc [hunk 4]
```diff
@@ -836,8 +842,24 @@ void CommunicatorClass::slaveRefresh(PacketHandler *P)
...
+      if (failedEntry != d_failedSlaveRefresh.end())
+        newCount = d_failedSlaveRefresh[di.zone].first + 1;
+      uint64_t checkOffset = std::min(newCount, (uint64_t)60); // On the default slave-cycle-interval, this ensures a maximum of one hour.
+      time_t nextCheck = now + checkOffset * d_tickinterval;
+      d_failedSlaveRefresh[di.zone] = {newCount, nextCheck};
+      if (newCount == 1 || newCount % 10 == 0) {
+        L<<Logger::Warning<<"Unable to retrieve SOA for "<<di.zone<<", this was the "<<(newCount == 1 ? "first" : std::to_string(newCount) + "th")<<" time."<<endl;
```
Comment (Habbie) [inline pdns/slavecommunicator.cc]: :heart:

File: pdns/slavecommunicator.cc (hunk 3 above)
Comment (pieterlexis) [inline pdns/slavecommunicator.cc]: Could you give some more context here? _what_ should be const?

Comment (Habbie) [inline pdns/slavecommunicator.cc]: Uhm. Don't recall. Perhaps I was thinking that .find returns a whole object while all you need is a const reference.

**Comment by pieterlexis** [comment]
> Is soa-retry-default not a better value for the backoff time if you cannot retreive a soa? With the current max 60 * slave-cycle-interval the backoff time will grow quickly if you increase slave-cycle-interval (1 hour = max 2.5 days).

Both for soa-retry-default and slave-cycle-interval appear 'related' settings for this... We could limit the time between checks to the minimum of `slave-cycle-interval*60` and `soa-retry-default*2`?

**Comment by pieterlexis** [comment]
Hrm, that is confusing... maybe it should be `std::min(slave-cycle-interval*num_failures, soa-retry-default)`

**Comment by klaus3000** [comment]
Thanks for this great feature. Just a comment from our experience with failing masters: a zone which was removed form the master but not from the slave causes plenty of logging every slave-check cycle, but rarely caused problem on the slave. But what really causes massive problems is a non-responsive master. Because then the queries have to timeout which massively slow downs the slave. We have customers with >200.000 domains. If their master is not available we have to manually remove these customer from the slave checks to avoid performance issues on our slave. Hence, it would be great if you could also implement a similar feature but not per "domain", but per "master IP". So, skipping SOA checks for some time for certain master IP addresses if the a certain amount of queries failed in a certain time.

**Comment by pieterlexis** [comment]
That sounds not unreasonable on first glance, can you open a feature request?
