### PR TITLE
dnsdist: default set "Connection: close" header for web requests

### LINKED ISSUE #6532: dnsdist: webserver should set Connection: close in standard headers
- Program: dnsdist
 - Issue type: Bug report

### Short description
The dnsdist webserver seems to close connections after each request without signaling to the client that it's going to do so with a `Connection: close` header. This introduces a race condition where an HTTP/1.1 client that implements connection reuse may try to send a second request over the connection if it doesn't receive the TCP FIN in time, and this second request will get hung up on.

Specifying `{["Connection"]="close"}` in `webserver()`'s custom headers seems to work around the problem.

### Environment
 - Operating system: Debian buster (aka "testing" as of right now)
 - Software version: 1.3.0
 - Software source: Debian repo

### PR DESCRIPTION
**Pull request by chbruyand**
### Short description
Default add the `Connection: close` header to dnsdist http responses to indicate that the connection will be closed after completion of the response.

Fix #6532 
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsdist-web.cc [hunk 1]
```diff
@@ -194,6 +194,7 @@ static void addSecurityHeaders(YaHTTP::Response& resp, const boost::optional<std
     { "X-Permitted-Cross-Domain-Policies", "none" },
     { "X-XSS-Protection", "1; mode=block" },
     { "Content-Security-Policy", "default-src 'self'; style-src 'self' 'unsafe-inline'" },
+    { "Connection", "close" },
```
Comment (rgacogne) [inline pdns/dnsdist-web.cc]: The name of the function (`addSecurityHeaders`) might not be relevant anymore after that change.

File: pdns/dnsdistdist/docs/guides/webserver.rst [hunk 2]
```diff
@@ -21,6 +21,7 @@ By default, our web server sends some security-related headers::
    X-Permitted-Cross-Domain-Policies: none
    X-XSS-Protection: 1; mode=block
    Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
+   Connection: close
```
Comment (rgacogne) [inline pdns/dnsdistdist/docs/guides/webserver.rst]: I don't think `Connection: close` belongs here, it's not a security-related header at all.

**Comment by chbruyand** [comment]
Sorry, didn't pay attention to the name of the function. I did move setting the header where it cannot be overriden as we will always close the connection.
