### PR TITLE
auth 2136: apply new TTL to whole RRset, not only to the added record

### LINKED ISSUE #10921: auth: 2136 does not enforce per-RRset TTL
- Program: Authoritative,
 - Issue type: Bug report

### Short description
using nsupdate it's possible to add two A records for the same DNS entry having a different TTL

### Environment

 - Operating system: CentOS 7
 - Software version: 4.4.1
 - it happens also in vesion 4.5.1

### Steps to reproduce

[root@localhost ~]# nsupdate
> server 127.0.0.1
> update add test.example.com 60 IN A 192.168.1.111
> send
> quit

[root@localhost ~]# nsupdate
> server 127.0.0.1
> update add test.example.com 3600 IN A 192.168.1.112
> send
> quit

[root@localhost ~]# pdnsutil list-zone example.com

test.example.com	60	IN	A	192.168.1.111
test.example.com	3600	IN	A	192.168.1.112

### Expected behaviour

nsupdate should return an error and not insert the two same A record with different TTL

### Actual behaviour

nsupdate applied the two update without any warning and doing a check with pdnsutil  it shows the error

[root@localhost ~]# pdnsutil check-all-zones |grep Err
[Error] TTL mismatch in rrset: 'test.example.com IN A 192.168.1.112' (60 != 3600)

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
fixes #10921

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Review by Kian0815 — APPROVED** [review]
test the pull an it works

File: pdns/rfc2136handler.cc [hunk 1]
```diff
@@ -204,10 +206,10 @@ uint PacketHandler::performUpdate(const string &msgPrefix, const DNSRecord *rr,
         }
         if (updateTTL > 0) {
           di->backend->replaceRRSet(di->id, rr->d_name, rrType, rrset);
-          g_log<<Logger::Notice<<msgPrefix<<"Replacing record "<<rr->d_name<<"|"<<rrType.toString()<<endl;
+          g_log<<Logger::Notice<<msgPrefix<<"Updating TTLs for "<<rr->d_name<<"|"<<rrType.toString()<<endl;
```
Comment (rgacogne) [inline pdns/rfc2136handler.cc:209]: I'm a bit confused by that change, since it looks like we might be updating more than the TTLs in that case, or am I missing something?

Comment (Habbie) [reply pdns/rfc2136handler.cc:209]: It is, painfully, a full DELETE+INSERT, but the net change really should be just the TTLs. If that's not true, I missed something.

Comment (rgacogne) [reply pdns/rfc2136handler.cc:209]: You are not, I was! It took me several tries to understand exactly what `rr` and `rrset` are at this point, sorry.

**Review by rgacogne — APPROVED** [review]

**Comment by Habbie** [comment]
I split this into two commits, same content.
