### PR TITLE
rec: Better handling of stranded DNSKeys

### LINKED ISSUE #10219: rec: Signed, insecure zone with broken DNSKEY is bogus
- Program: Recursor
 - Issue type: Bug report

### Short description
I have a test zone, `unpublished.mattnordhoffdns.work`. It's insecure, signed, but the key is set to unpublished, so `DNSKEY` queries get a (signed) `NODATA` response. `mattnordhoffdns.work` is secure. The child zone is hosted on 2 of the 4 nameservers the parent zone uses.

The Recursor considers the child zone "Bogus - No valid RRSIG".

I believe this broke within the last few days -- the zone cut computation changes are obviously suspect, but who knows -- but I'm not 100% sure. It definitely broke within the last few months.

### Environment
 - Operating system: Ubuntu 20.04 amd64
 - Software version: 4.5.0~beta1+master.9.g3fa870294-1pdns.focal (yesterday-ish)
 - Software source: PowerDNS repository

### Steps to reproduce
1. Enable DNSSEC validation
2. `dig unpublished.mattnordhoffdns.work`

I haven't checked, but it may succeed sometimes, since some of the parent zone's nameservers will send a referral, so it will trivially discover the zone cut.

### Expected behaviour
Insecure.

### Actual behaviour
Bogus.

### Other information

```
$ dig +dnssec +cd unpublished.mattnordhoffdns.work soa

; <<>> DiG 9.17.11-1+ubuntu20.04.1+isc+1-Ubuntu <<>> +dnssec +cd unpublished.mattnordhoffdns.work soa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22892
;; flags: qr rd ra cd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION: 
; EDNS: version: 0, flags: do; udp: 512
; EDE: 6 (DNSSEC Bogus)
;; QUESTION SECTION:  
;unpublished.mattnordhoffdns.work. IN   SOA

;; ANSWER SECTION:
unpublished.mattnordhoffdns.work. 3316 IN SOA   pdns0.mattnordhoff.net. rname.mn0.us. 2021012900 1800 900 432000 7200
unpublished.mattnordhoffdns.work. 3316 IN RRSIG SOA 13 3 3600 20210408000000 20210318000000 4819 unpublished.mattnordhoffdns.work. uAVYPmtozksUF5+Ve72cTzSy1bVNl4bFtNNdhbc+4qQrbV1o1wFnwhls 15KZ4+6+B7chgcfYbqlOm0xwtKZifw==

;; Query time: 0 msec
;; SERVER: ::1#53(::1) (UDP)
;; WHEN: Thu Mar 25 22:57:00 UTC 2021
;; MSG SIZE  rcvd: 265

$ dig +dnssec +cd unpublished.mattnordhoffdns.work dnskey

; <<>> DiG 9.17.11-1+ubuntu20.04.1+isc+1-Ubuntu <<>> +dnssec +cd unpublished.mattnordhoffdns.work dnskey
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31064
;; flags: qr rd ra ad cd; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 512
;; QUESTION SECTION:
;unpublished.mattnordhoffdns.work. IN   DNSKEY

;; AUTHORITY SECTION:
unpublished.mattnordhoffdns.work. 3314 IN SOA   pdns0.mattnordhoff.net. rname.mn0.us. 2021012900 1800 900 432000 7200
unpublished.mattnordhoffdns.work. 3314 IN NSEC  foo.unpublished.mattnordhoffdns.work. A NS SOA AAAA RRSIG NSEC
unpublished.mattnordhoffdns.work. 3314 IN RRSIG SOA 13 3 3600 20210408000000 20210318000000 4819 unpublished.mattnordhoffdns.work. uAVYPmtozksUF5+Ve72cTzSy1bVNl4bFtNNdhbc+4qQrbV1o1wFnwhls 15KZ4+6+B7chgcfYbqlOm0xwtKZifw==
unpublished.mattnordhoffdns.work. 3314 IN RRSIG NSEC 13 3 3600 20210408000000 20210318000000 4819 unpublished.mattnordhoffdns.work. feY5p9akg6nRcwXzaS65j8ln15Z3d4H7/Mn0BKwtpdMqLu3uA9Hr3yfN pavwklvm9SYxkOF6PN7R6U2/i+hMiA==

;; Query time: 3 msec
;; SERVER: ::1#53(::1) (UDP)
;; WHEN: Thu Mar 25 22:57:02 UTC 2021
;; MSG SIZE  rcvd: 445
```

`trace-regex` (mostly from cache):

```
Mar 25 23:16:12 ultimate pdns_recursor[74786]: 1 [3887/1] question for 'unpublished.mattnordhoffdns.work|A' from [::1]:52899
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : no TA found for 'unpublished.mattnordhoffdns.work' among 1
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : no TA found for 'mattnordhoffdns.work' among 1
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : no TA found for 'work' among 1
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : got TA for '.'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: QM unpublished.mattnordhoffdns.work.|A child=(empty): doResolve
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Wants DNSSEC processing, auth data in query for A
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Recursion not requested for 'unpublished.mattnordhoffdns.work|A', peeking at auth/forward zones
Mar 25 23:16:12 ultimate pdns_recursor[74786]: QM unpublished.mattnordhoffdns.work.|A child=(empty): Step0 Not cached
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Checking if we have NS in cache for 'unpublished.mattnordhoffdns.work'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: no valid/useful NS in cache for 'unpublished.mattnordhoffdns.work'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Checking if we have NS in cache for 'mattnordhoffdns.work'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns10.mattnordhoffdns.com'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns10.mattnordhoffdns.org'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns11.mattnordhoffdns.com'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns11.mattnordhoffdns.org'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns12.mattnordhoffdns.org'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns13.mattnordhoffdns.org'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: We have NS in cache for 'mattnordhoffdns.work' (flawedNSSet=0)
Mar 25 23:16:12 ultimate pdns_recursor[74786]: QM unpublished.mattnordhoffdns.work.|A child=(empty): Step1 Ancestor from cache is mattnordhoffdns.work
Mar 25 23:16:12 ultimate pdns_recursor[74786]: QM unpublished.mattnordhoffdns.work.|A child=unpublished.mattnordhoffdns.work: Step2 New child
Mar 25 23:16:12 ultimate pdns_recursor[74786]: QM unpublished.mattnordhoffdns.work.|A child=unpublished.mattnordhoffdns.work: Step3 Going to do final resolve
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Wants DNSSEC processing, auth data in query for A
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: No cache hit for 'unpublished.mattnordhoffdns.work|A', trying to find an appropriate NS record
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Checking if we have NS in cache for 'unpublished.mattnordhoffdns.work'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: no valid/useful NS in cache for 'unpublished.mattnordhoffdns.work'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Checking if we have NS in cache for 'mattnordhoffdns.work'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns10.mattnordhoffdns.com'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns10.mattnordhoffdns.org'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns11.mattnordhoffdns.com'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns11.mattnordhoffdns.org'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns12.mattnordhoffdns.org'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: NS (with ip, or non-glue) in cache for 'mattnordhoffdns.work' -> 'ns13.mattnordhoffdns.org'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: within bailiwick: 0, not in cache / did not look at cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: We have NS in cache for 'mattnordhoffdns.work' (flawedNSSet=0)
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Cache consultations done, have 6 NS to contact
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work.: Nameservers: ns13.mattnordhoffdns.org(0.00ms), ns11.mattnordhoffdns.com(0.00ms), ns10.mattnordhoffdns.org(0.00ms),
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work.:              ns12.mattnordhoffdns.org(0.00ms), ns10.mattnordhoffdns.com(0.00ms), ns11.mattnordhoffdns.org(0.00ms)
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Trying to resolve NS 'ns13.mattnordhoffdns.org' (1/6)
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : no TA found for 'ns13.mattnordhoffdns.org' among 1
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : no TA found for 'mattnordhoffdns.org' among 1
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : no TA found for 'org' among 1
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : got TA for '.'
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  QM ns13.mattnordhoffdns.org.|A child=(empty): doResolve
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  ns13.mattnordhoffdns.org: Wants DNSSEC processing, NO auth data in query for A
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  ns13.mattnordhoffdns.org: Recursion not requested for 'ns13.mattnordhoffdns.org|A', peeking at auth/forward zones
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  ns13.mattnordhoffdns.org: Found cache hit for A: 45.33.103.94[ttl=5764]
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  ns13.mattnordhoffdns.org: updating validation state with cache content for ns13.mattnordhoffdns.org to Indeterminate
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  QM ns13.mattnordhoffdns.org.|A child=(empty): Step0 Found in cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: Nameserver ns13.mattnordhoffdns.org IPs: 45.33.103.94(0.00ms)
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Resolved 'mattnordhoffdns.work' NS ns13.mattnordhoffdns.org to: 45.33.103.94
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Trying IP 45.33.103.94:53, asking 'unpublished.mattnordhoffdns.work|A'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: Got 3 answers from ns13.mattnordhoffdns.org (45.33.103.94), rcode=0 (No Error), aa=1, in 2ms
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: accept answer 'unpublished.mattnordhoffdns.work|A|192.0.2.0' from 'mattnordhoffdns.work' nameservers? ttl=3600, place=1 YES!
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: accept answer 'unpublished.mattnordhoffdns.work|RRSIG|A 13 3 3600 20210408000000 20210318000000 4819 unpublished.mattnordhoffdns.work. u/E6LKhgEx6hoLhIrCynFkCLVuexWvaagao9M3tLSQ1BsXixI7PIkYQh5FK5eqjnzMuolbsj5vm+nfOEyi7sPw==' from 'mattnordhoffdns.work' nameservers? ttl=3600, place=1 RRSIG - separate
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: OPT answer '.' from 'mattnordhoffdns.work' nameservers
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : got initial zone status Secure for record unpublished.mattnordhoffdns.work|A
Mar 25 23:16:12 ultimate pdns_recursor[74786]: Validating non-additional A record for unpublished.mattnordhoffdns.work
Mar 25 23:16:12 ultimate pdns_recursor[74786]: Retrieving DNSKeys for unpublished.mattnordhoffdns.work
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : no TA found for 'unpublished.mattnordhoffdns.work' among 1
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : no TA found for 'mattnordhoffdns.work' among 1
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : no TA found for 'work' among 1
Mar 25 23:16:12 ultimate pdns_recursor[74786]: : got TA for '.'
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  QM unpublished.mattnordhoffdns.work.|DNSKEY child=(empty): doResolve
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  unpublished.mattnordhoffdns.work: Wants DNSSEC processing, auth data in query for DNSKEY
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  unpublished.mattnordhoffdns.work: Recursion not requested for 'unpublished.mattnordhoffdns.work|DNSKEY', peeking at auth/forward zones
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  unpublished.mattnordhoffdns.work: DNSKEY is negatively cached via 'unpublished.mattnordhoffdns.work' for another 2164 seconds
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  unpublished.mattnordhoffdns.work: updating validation state with negative cache content for unpublished.mattnordhoffdns.work to Secure
Mar 25 23:16:12 ultimate pdns_recursor[74786]:  QM unpublished.mattnordhoffdns.work.|DNSKEY child=(empty): Step0 Found in cache
Mar 25 23:16:12 ultimate pdns_recursor[74786]: Retrieved 0 DNSKeys for unpublished.mattnordhoffdns.work, state is Secure
Mar 25 23:16:12 ultimate pdns_recursor[74786]: Going to validate 1 record contents with 1 sigs and 0 keys for unpublished.mattnordhoffdns.work|A
Mar 25 23:16:12 ultimate pdns_recursor[74786]: Bogus - No valid RRSIG!
Mar 25 23:16:12 ultimate pdns_recursor[74786]: Validation result is Bogus - No valid RRSIG, current state is Indeterminate
Mar 25 23:16:12 ultimate pdns_recursor[74786]: validation state was Indeterminate, state update is Bogus - No valid RRSIG, validation state is now Bogus - No valid RRSIG
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: determining status after receiving this packet
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: answer is in: resolved to '192.0.2.0|A'
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: status=got results, this level of recursion done
Mar 25 23:16:12 ultimate pdns_recursor[74786]: unpublished.mattnordhoffdns.work: validation status is Bogus - No valid RRSIG
Mar 25 23:16:12 ultimate pdns_recursor[74786]: QM unpublished.mattnordhoffdns.work.|A child=unpublished.mattnordhoffdns.work: Step3 Final resolve: No Error/2
Mar 25 23:16:12 ultimate pdns_recursor[74786]: Answer to unpublished.mattnordhoffdns.work|A for [::1]:52899 validates as Bogus - No valid RRSIG
Mar 25 23:16:12 ultimate pdns_recursor[74786]: Sending out SERVFAIL for unpublished.mattnordhoffdns.work|A because recursor or query demands it for Bogus results
```

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

Fixes #10219.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [x] added or modified unit test(s)

### CODE REVIEW

File: pdns/syncres.cc [hunk 1]
```diff
@@ -2768,6 +2770,19 @@ vState SyncRes::validateRecordsWithSigs(unsigned int depth, const DNSName& qname
...
+            /* if we are trying to validate the DNSKEY (should not happen here),
+               or more likely NSEC(3)s proving that it does not exist, we have a problem.
+               In that case let's see if the DS does exist, and if it does let's go Bogus
+            */
+            dsmap_t results;
+            vState dsState = getDSRecords(signer, results, false, depth, true);
+            if (dsState == vState::Insecure) {
+              return dsState;
+            }
+            return vState::BogusUnableToGetDNSKEYs;
```
Comment (omoerbeek) [inline pdns/syncres.cc:2783]: What's a bit confusing for me is that we call `getDSRecords` but the error says `BogusUnableToGetDNSKEYs`. The casual reader would expect `BogusUnableToGetDSs`.

**Comment by rgacogne** [comment]
I know of some possible issues remaining with that PR, please don't spend any time on it for now.

File: pdns/syncres.cc (hunk 1 above)
Comment (rgacogne) [reply pdns/syncres.cc:2783]: What's happening is that we are trying to validate a record signed by the `DNSKEY` for `X` while trying to retrieve that exact DNSKEY, which is of course a problem. For some records we can afford to go `Indeterminate`, but for `NSEC` or `NSEC3` records trying to prove that the `DNSKEY` does not exist we can't do that. So we try to see if the zone is indeed signed, which we don't know for sure even though we have some `RRSIG`s because we don't compute the zone cuts beforehand anymore. If we get an `Insecure` result that's fine, there isn't a secure chain from the root to that zone and no `TA` either. But otherwise, we are in a signed Zone, trying to get the corresponding `DNSKEY` and we need that `DNSKEY` to validate records so the problem is not the `DS`.

**Comment by rgacogne** [comment]
Fixed NSEC3 handling, and added unit tests.

File: pdns/recursordist/test-syncres_cc6.cc [hunk 2]
```diff
@@ -404,6 +404,210 @@ BOOST_AUTO_TEST_CASE(test_dnssec_dnskey_signed_child)
   BOOST_CHECK_EQUAL(queriesCount, 6U);
 }
 
+BOOST_AUTO_TEST_CASE(test_dnssec_dnskey_unpublished)
+{
+  /* check that we properly handle an insecure (no DS) but  signed zone whose DNSKEY is not published (so NODATA) */
```
Comment (jsoref) [inline pdns/recursordist/test-syncres_cc6.cc:409]:
```suggestion
  /* check that we properly handle an insecure (no DS) but signed zone whose DNSKEY is not published (so NODATA) */
```

File: pdns/recursordist/test-syncres_cc6.cc [hunk 3]
```diff
@@ -404,6 +404,210 @@ BOOST_AUTO_TEST_CASE(test_dnssec_dnskey_signed_child)
...
+  res = sr->beginResolve(target, QType(QType::SOA), QClass::IN, ret);
+  BOOST_CHECK_EQUAL(res, RCode::NoError);
+  BOOST_CHECK_EQUAL(sr->getValidationState(), vState::Insecure);
+  BOOST_REQUIRE_EQUAL(ret.size(), 2U);
+  BOOST_CHECK_EQUAL(queriesCount, 6U);
+}
+
+BOOST_AUTO_TEST_CASE(test_dnssec_dnskey_unpublished_nsec3)
+{
+  /* check that we properly handle an insecure (no DS) but  signed zone whose DNSKEY is not published (so NODATA) with NSEC3 this time */
```
Comment (jsoref) [inline pdns/recursordist/test-syncres_cc6.cc:511]:
```suggestion
  /* check that we properly handle an insecure (no DS) but signed zone whose DNSKEY is not published (so NODATA) with NSEC3 this time */
```

**Review by omoerbeek — APPROVED** [review]
