### PR TITLE
dnsdist: Remove the --daemon option

### LINKED ISSUE #6329: dnsdist loses remote logger thread on daemonizing (-d)
- Program:  dnsdist
 - Issue type: Bug report

### Short description

When starting _dnsdist_ with `-d` (`--daemonize`), the program doesn't log to a remote logger. It's as though this action were never specified, though the connect is seen:

```
addAction(AllRule(), RemoteLogAction(newRemoteLogger("10.0.0.1:4242", 2, 2)))
```
In a private conversation with @rgacogne it turns out that:

>  we call daemonize() after creating the remote logger thread
> daemonize() calls fork() and the parent process exits
> so there is no remote logger worker thread anymore

For the record, Remi also says

> same pain for TeeAction and, obviously, dnstap

### Environment

 - Operating system:  SLES12SP3
 - Software version: 1.2.1
 - Software source: OBS package

### Expected behaviour

Logging should occur as without _daemonize_

### PR DESCRIPTION
**Pull request by rgacogne**
### Short description

We keep finding bugs with this option because we don't use it on a regular basis and most users run dnsdist under some kind of supervision anyway.

Closes #6329.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsdist.cc [hunk 1]
```diff
@@ -2564,24 +2517,17 @@ try
...
-    vector<string> vec;
-    std::string acls;
-    g_ACL.getLocal()->toStringVector(&vec);
-    for(const auto& s : vec) {
-      if (!acls.empty())
-        acls += ", ";
-      acls += s;
-    }
-    infolog("ACL allowing queries from: %s", acls.c_str());
+  vinfolog("Running in the foreground");
```
Comment (pieterlexis) [inline pdns/dnsdist.cc]: nit: not sure this message is still relevant

Comment (rgacogne) [reply pdns/dnsdist.cc]: Oh right
