### PR TITLE
Refuse to start with chroot set in a systemd env

### LINKED ISSUE #4848: chroot option + systemd do not coexist well
There are various issues when running pdns with chroot= set under systemd.

IIRC:

  * notification to systemd fails because the systemd socket is unreachable
  * pdns_control has (with some specific settings) trouble talking to the daemon

Personally, I'd think refusing to start under systemd with chroot set would be good.

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
When `chroot` is used while ruinning in systemd, PowerDNS can't use [`sd_notify()`](https://www.freedesktop.org/software/systemd/man/sd_notify.html)'s `NOTIFY_SOCKET` to send a notification to systemd that it started successfully, resulting in systemd believing the start up timed out.

This PR exits the server before starting up with a proper error message so the operator can take action.

Closes #4848

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added regression tests
- [ ] added unit tests
- [ ]  checked that this code was merged to master

### CODE REVIEW

File: pdns/common_startup.cc [hunk 1]
```diff
@@ -498,6 +498,14 @@ void mainthread()
    stubParseResolveConf();
 
    if(!::arg()["chroot"].empty()) {
+#ifdef HAVE_SYSTEMD
+     char *ns;
+     ns = getenv("NOTIFY_SOCKET");
+     if (ns != nullptr) {
+       L<<Logger::Error<<"Unable to chroot when running from systemd. Please disable chrooting or set the 'Type' for this service to 'simple'"<<endl;
```
Comment (zeha) [inline pdns/common_startup.cc]: `... Please disable chroot= or set ...`?

File: docs/markdown/recursor/settings.md [hunk 2]
```diff
@@ -129,6 +129,9 @@ in the configuration are relative to the new root.
 When using `chroot` and the API ([`webserver`](#webserver)), [`api-readonly`](#api-readonly)
 must be set and [`api-config-dir`](#api-config-dir) unset.
 
+When running on a system where systemd manages services, `chroot` does not work out of the box, as PowerDNS cannot use the `NOTIFY_SOCKET`.
+Either don't `chroot` on these systems or set the 'Type' of the this service to 'simple' instead of 'notify' (refer to the systemd documentation on how to modify unit-files)
```
Comment (zeha) [inline docs/markdown/recursor/settings.md]: - `of the this`
- i think habbie usually wants `do not` not `don't`
