### PR TITLE
rec: QM can get confused by expiring infra records

### LINKED ISSUE #12078: rec: Repetitive refetches to parent zones (occasionally)
- Program: Recursor
 - Issue type: Bug report

### Short description
A couple times recently, I've seen Recursor trying to refetch nameservers(?), and sending somewhat repetitive queries of e.g. `example.net` `A`, and `ns1.example.net` `A` and `AAAA` queries to the root and `net` zone. It makes progress figuring out the delegations but seems to usually give up before actually sending `ns1.example.net` queries to the `example.net` nameservers.

I haven't noticed any real consequences, like `SERVFAIL`.

My only recent changes I can think of are upgrading Recursor and enabling serve-stale. (There shouldn't _be_ any stale responses -- and a cache dump doesn't show any -- but the feature is on.)

Similar to #11371.

### Environment
 - Operating system: Ubuntu 20.04 (amd64)
 - Software version: 4.9.0~alpha0+master.11.g054012aeb-1pdns.focal
 - Software source: PowerDNS repository

### Steps to reproduce
I don't know. Today, "`dig dnsflagday.net`" and "`dig dnsflagday.net aaaa`".

### Expected behaviour
Fewer, successful refetch queries, to the right zones, with QNAME minimisation. :-)

### Actual behaviour
`tcpdump` sample:

```
2022-10-07 21:06:04.801119 IP6 ::1.39726 > ::1.53: 43005+ [1au] A? dnsflagday.net. (55)
2022-10-07 21:06:04.808303 IP 45.79.214.107.29235 > 185.136.98.79.53: 58318 [1au] A? dnsflagday.net. (43)
2022-10-07 21:06:04.827210 IP 185.136.98.79.53 > 45.79.214.107.29235: 58318*- 0/4/1 (409)
2022-10-07 21:06:04.831269 IP6 ::1.53 > ::1.39726: 43005$ 0/1/1 (101)
2022-10-07 21:06:06.025160 IP6 ::1.52261 > ::1.53: 5215+ [1au] AAAA? dnsflagday.net. (55)
2022-10-07 21:06:06.025527 IP 45.79.214.107.17621 > 185.136.96.79.53: 22497 [1au] AAAA? dnsflagday.net. (43)
2022-10-07 21:06:06.044852 IP 185.136.96.79.53 > 45.79.214.107.17621: 22497*- 0/4/1 (409)
2022-10-07 21:06:06.045896 IP6 ::1.53 > ::1.52261: 5215$ 0/1/1 (101)
2022-10-07 21:06:06.047483 IP 45.79.214.107.64181 > 192.31.80.30.53: 18043 [1au] A? cloudns.net. (40)
2022-10-07 21:06:06.061905 IP 192.31.80.30.53 > 45.79.214.107.64181: 18043- 0/9/11 (903)
2022-10-07 21:06:06.063720 IP6 2600:3c02:e000:74::53c:1.34568 > 2001:500:2d::d.53: 21324 [1au] A? cloudns.net. (40)
2022-10-07 21:06:06.064372 IP6 2001:500:2d::d.53 > 2600:3c02:e000:74::53c:1.34568: 21324- 0/15/27 (1168)
2022-10-07 21:06:06.064940 IP 45.79.214.107.24975 > 192.203.230.10.53: 24002 [1au] A? cloudns.net. (40)
2022-10-07 21:06:06.065806 IP 192.203.230.10.53 > 45.79.214.107.24975: 24002- 0/15/27 (1168)
2022-10-07 21:06:06.066535 IP 45.79.214.107.37286 > 192.5.6.30.53: 13205 [1au] A? pns41.cloudns.net. (46)
2022-10-07 21:06:06.080943 IP 192.5.6.30.53 > 45.79.214.107.37286: 13205- 0/9/11 (909)
2022-10-07 21:06:06.082144 IP 45.79.214.107.11918 > 192.26.92.30.53: 1694 [1au] A? ns4.cloudns.net. (44)
2022-10-07 21:06:06.094988 IP 192.26.92.30.53 > 45.79.214.107.11918: 1694- 0/9/11 (903)
2022-10-07 21:06:06.096762 IP 45.79.214.107.65087 > 192.12.94.30.53: 46195 [1au] A? dns2.cloudns.net. (45)
2022-10-07 21:06:06.111147 IP 192.12.94.30.53 > 45.79.214.107.65087: 46195- 0/9/11 (903)
2022-10-07 21:06:06.112508 IP6 2600:3c02:e000:74::53c:1.26288 > 2001:502:8cc::30.53: 8086 [1au] A? pns4.cloudns.net. (45)
2022-10-07 21:06:06.129599 IP6 2001:502:8cc::30.53 > 2600:3c02:e000:74::53c:1.26288: 8086- 0/9/11 (903)
2022-10-07 21:06:06.130548 IP6 2600:3c02:e000:74::53c:1.3193 > 2001:500:a8::e.53: 4213 [1au] A? ns4.cloudns.net. (44)
2022-10-07 21:06:06.131499 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.3193: 4213- 0/15/27 (1172)
2022-10-07 21:06:06.132095 IP6 2600:3c02:e000:74::53c:1.40618 > 2001:503:39c1::30.53: 40060 [1au] A? ns4.cloudns.net. (44)
2022-10-07 21:06:06.149689 IP6 2001:503:39c1::30.53 > 2600:3c02:e000:74::53c:1.40618: 40060- 0/9/11 (903)
2022-10-07 21:06:06.151235 IP 45.79.214.107.53421 > 192.5.5.241.53: 49443 [1au] A? dns2.cloudns.net. (45)
2022-10-07 21:06:06.152014 IP 192.5.5.241.53 > 45.79.214.107.53421: 49443- 0/15/27 (1173)
2022-10-07 21:06:06.152934 IP 45.79.214.107.15712 > 192.35.51.30.53: 714 [1au] A? dns2.cloudns.net. (45)
2022-10-07 21:06:06.170053 IP 192.35.51.30.53 > 45.79.214.107.15712: 714- 0/9/11 (903)
...
```

### Other information
More tcpdump, configuration: https://gist.github.com/mnordhoff/c30a38a7d747b500c77d55813bdc18ad

### PR DESCRIPTION
**Pull request by omoerbeek**
So be a bit more lenient with replacing auth records by unauth, as unauth (typically infra records) might come in while we are resolving.

Should fix #12078. 

But the issue of doing multiple cache lookups that assume records do no expire in-between during the resolving process is a fundamental issue. In the future we might create a separate infra cache which should take this fundamental  issue into account.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Review by Habbie — APPROVED** [review]

File: pdns/recursordist/test-recursorcache_cc.cc [hunk 1]
```diff
@@ -426,6 +426,53 @@ BOOST_AUTO_TEST_CASE(test_RecursorCacheGhost)
...
+  now = ttd - 1;
+  ttd = now + expiry;
+  ns1.d_ttl = static_cast<uint32_t>(ttd); // XXX truncation
+  records.clear();
+  records.push_back(ns1);
+
+  MRC.replace(now, ns1.d_name, QType(ns1.d_type), records, signatures, authRecords, false, DNSName("powerdns.com."), boost::none);
+  BOOST_CHECK_EQUAL(MRC.size(), 1U);
+
+  // Let time pass, if we did not insert the non-auth record, it wil be expired
```
Comment (Habbie) [inline pdns/recursordist/test-recursorcache_cc.cc:467]:
```suggestion
  // Let time pass, if we did not insert the non-auth record, it will be expired
```
