### PR TITLE
rec: Only log MOADNSExceptions if logging.log_common_errors is true.

### LINKED ISSUE #14582: rec: Some "common" error messages are no longer hidden behind `log-common-errors`
- Program: Recursor 
 - Issue type: Bug report

### Short description

As reported by `qvr` on IRC, we might be logging messages by default that used to / should have been hidden behind `log-common-errors`:
```
10:41  qvr i'm upgrading to rec5.0 and we're seeing a lot of error level log messages for "PIPE function created an exception", apparently before #14185 these could be suppressed with log-common-errors=no but now they will always come through, but ratelimited?
10:41  PowerIssue pull #14185 omoerbeek (closed,merged): rec: log vm.max_map_count possibly being too low and log a few exceptions (with rate limiting) https://github.com/PowerDNS/pdns/pull/14185
10:44  qvr well, "a lot" is a hyperbole, but every minute and they are annoying :)
10:45  cmouse qvr: is there any details?
10:45  rgacogne qvr: it looks that way, yes, but note that these errors should probably not be happening. do you have any idea what is triggering them?
10:46  qvr broken clients and/or queries, most common seems: Error parsing packet of 51 bytes (rd=1), out of bounds: dnsname issue: Found an invalid label length in qname
10:46  qvr other one is Query with QD > 1 (18)
10:46  rgacogne ah
10:47  rgacogne ok, I was wrongly assuming these were caught in a different place
10:47  rgacogne this seems like a bug then, because errors like these should indeed remain hidden behind log-common-errors IMHO
```

### PR DESCRIPTION
**Pull request by omoerbeek**
But do not ratelimit them. Note that `MOADNSExceptions` is derived from `std::runtime_errror` and not from `std::exception`.

Also introduce the same logic related to `gettag()` in `rec-tcp.cc` compared to `pdns_recursor.cc`. 
Churn is a bit high as `s_rateLimitedLogger` changed into `g_rateLimitedLogger`, to make it available in `rec-tcp.cc`.

Fixes #14582

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/recursordist/pdns_recursor.cc [hunk 1]
```diff
@@ -2285,13 +2283,18 @@ static string* doProcessUDPQuestion(const std::string& question, const ComboAddr
               eventTrace.add(RecEventTrace::LuaGetTag, ctag, false);
             }
           }
+          catch (const MOADNSException& moadnsexception) {
```
Comment (rgacogne) [inline pdns/recursordist/pdns_recursor.cc:2286]: > But do not ratelimit them. Note that `MOADNSExceptions` is derived from `std::runtime_errror` and not from `std::exception`.

Something is weird here, because  `std::runtime_error` derives from `std::exception`.

Comment (omoerbeek) [reply pdns/recursordist/pdns_recursor.cc:2286]: I misread the docs on https://en.cppreference.com/w/cpp/error/runtime_error. The declaration does not show the base class, only the Inheritance diagram does.

**Review by rgacogne — APPROVED** [review]
