### PR TITLE
ixfrdist: store TTL in stored zones

### LINKED ISSUE #6635: ixfrdist: does not honor records ttl
- Program: ixfrdist
 - Issue type: Bug report

### Short description
ixfrdist does not honor records TTL and fall-back to 3600.

### Steps to reproduce

1. I do have a RPZ DNS zone with the following records

```
# pdnsutil list-zone rpz.test
$ORIGIN .
nxd-10.blocked.rpz.test	30	IN	A	2.2.2.2
nxd-1.blocked.rpz.test	30	IN	A	2.2.2.2
nxd-2.blocked.rpz.test	30	IN	A	2.2.2.2
nxd-3.blocked.rpz.test	30	IN	A	2.2.2.2
nxd-4.blocked.rpz.test	30	IN	A	2.2.2.2
nxd-5.blocked.rpz.test	30	IN	A	2.2.2.2
nxd-6.blocked.rpz.test	30	IN	A	2.2.2.2
nxd-7.blocked.rpz.test	30	IN	A	2.2.2.2
nxd-8.blocked.rpz.test	30	IN	A	2.2.2.2
nxd-9.blocked.rpz.test	30	IN	A	2.2.2.2
rpz.test	30	IN	SOA	a.misconfigured.powerdns.server hostmaster.rpz.test 56 30 15 604800 30
```

2. Executing a zone-transfer on the Authoritative server I get

```
# dig -t axfr @127.0.0.1 rpz.test

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.3 <<>> -t axfr @127.0.0.1 rpz.test
; (1 server found)
;; global options: +cmd
rpz.test.		30	IN	SOA	a.misconfigured.powerdns.server. hostmaster.rpz.test. 56 30 15 604800 30
nxd-10.blocked.rpz.test. 30	IN	A	2.2.2.2
nxd-1.blocked.rpz.test.	30	IN	A	2.2.2.2
nxd-2.blocked.rpz.test.	30	IN	A	2.2.2.2
nxd-3.blocked.rpz.test.	30	IN	A	2.2.2.2
nxd-4.blocked.rpz.test.	30	IN	A	2.2.2.2
nxd-5.blocked.rpz.test.	30	IN	A	2.2.2.2
nxd-6.blocked.rpz.test.	30	IN	A	2.2.2.2
nxd-7.blocked.rpz.test.	30	IN	A	2.2.2.2
nxd-8.blocked.rpz.test.	30	IN	A	2.2.2.2
nxd-9.blocked.rpz.test.	30	IN	A	2.2.2.2
rpz.test.		30	IN	SOA	a.misconfigured.powerdns.server. hostmaster.rpz.test. 56 30 15 604800 30
;; Query time: 13 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon May 21 15:50:28 BST 2018
;; XFR size: 12 records (messages 3, bytes 496)
```

3. The ixfrdist cache folder shows 

```
# cat /var/lib/ixfrdist/rpz.test./56
$ORIGIN rpz.test.
@	IN	SOA	a.misconfigured.powerdns.server. hostmaster.rpz.test. 56 30 15 604800 30
@	IN	SOA	a.misconfigured.powerdns.server. hostmaster.rpz.test. 56 30 15 604800 30
@	IN	SOA	a.misconfigured.powerdns.server. hostmaster.rpz.test. 56 30 15 604800 30
nxd-1.blocked	IN	A	2.2.2.2
nxd-10.blocked	IN	A	2.2.2.2
nxd-2.blocked	IN	A	2.2.2.2
nxd-3.blocked	IN	A	2.2.2.2
nxd-4.blocked	IN	A	2.2.2.2
nxd-5.blocked	IN	A	2.2.2.2
nxd-6.blocked	IN	A	2.2.2.2
nxd-7.blocked	IN	A	2.2.2.2
nxd-8.blocked	IN	A	2.2.2.2
nxd-9.blocked	IN	A	2.2.2.2
@	IN	SOA	a.misconfigured.powerdns.server. hostmaster.rpz.test. 56 30 15 604800 30
```

4. Performing the XFR  via ixfrdist I get

```
dig -t axfr @10.22.52.154 -p 5300 rpz.test

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.3 <<>> -t axfr @10.22.52.154 -p 5300 rpz.test
; (1 server found)
;; global options: +cmd
rpz.test.		3600	IN	SOA	a.misconfigured.powerdns.server. hostmaster.rpz.test. 56 30 15 604800 30
nxd-1.blocked.rpz.test.	3600	IN	A	2.2.2.2
nxd-10.blocked.rpz.test. 3600	IN	A	2.2.2.2
nxd-2.blocked.rpz.test.	3600	IN	A	2.2.2.2
nxd-3.blocked.rpz.test.	3600	IN	A	2.2.2.2
nxd-4.blocked.rpz.test.	3600	IN	A	2.2.2.2
nxd-5.blocked.rpz.test.	3600	IN	A	2.2.2.2
nxd-6.blocked.rpz.test.	3600	IN	A	2.2.2.2
nxd-7.blocked.rpz.test.	3600	IN	A	2.2.2.2
nxd-8.blocked.rpz.test.	3600	IN	A	2.2.2.2
nxd-9.blocked.rpz.test.	3600	IN	A	2.2.2.2
rpz.test.		3600	IN	SOA	a.misconfigured.powerdns.server. hostmaster.rpz.test. 56 30 15 604800 30
;; Query time: 0 msec
;; SERVER: 10.22.52.154#5300(10.22.52.154)
;; WHEN: Mon May 21 15:51:46 BST 2018
;; XFR size: 12 records (messages 12, bytes 769)
```

### Expected behaviour

Ixfrdist should keep track of records TTL in the cache and honor it in the responses.
The result of the same `XFR` query on the Auth and on ixfrdist should provide consistent responses.

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
Closes #6635

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/ixfrutils.cc [hunk 1]
```diff
@@ -110,8 +110,9 @@ void writeZoneToDisk(const records_t& records, const DNSName& zone, const std::s
   fprintf(fp, "$ORIGIN %s\n", zone.toString().c_str());
   for(const auto& outer : {soarecord, records, soarecord} ) {
     for(const auto& r: outer) {
-      fprintf(fp, "%s\tIN\t%s\t%s\n",
+      fprintf(fp, "%s\t%i\tIN\t%s\t%s\n",
```
Comment (rgacogne) [inline pdns/ixfrutils.cc]: `"%i"` is for an `int`, `d_ttl` is a `uint32_t` so we should use `"%"PRIu32`, which requires:
```
#include <cinttypes>
```
