### PR TITLE
ignore SOA-EDIT for PRESIGNED zones. Fixes #5814

### LINKED ISSUE #5814: SOA-EDIT should be ignored in PRESIGNED case
- Program: Authoritative
 - Issue type: Bug report

### Short description
When both SOA-EDIT and PRESIGNED are set on a zone, we bump the SOA, making the signature invalid.

### Environment
 - Operating system: Debian 9.2
 - Software version: 4.1.0-rc1, 4.0.0, 4.0.4, rel/auth-4.0.x as of fbae572ef709e9322bc1654445bc5da081c4a83a
 - Software source: repo.powerdns.com

### Steps to reproduce
1. slave a signed zone
2. configure SOA-EDIT metadata on it
3. validate the SOA

### Expected behaviour
the SOA validates

### Actual behaviour
the SOA does not validate

### Other information
from pdns-public-ns1, on the public pdns instance that is a slave to the hidden, signing, master:
```
sqlite> select * from domains;
...
41|powerdns.com|127.0.0.2|1507792736|SLAVE|2017101201|
sqlite> select * from domainmetadata where domain_id=41;
9|41|SOA-EDIT|INCEPTION-INCREMENT
11|41|PRESIGNED|1
```

dig output:
```
; <<>> DiG 9.11.2 <<>> +dnssec soa powerdns.com @pdns-public-ns1.powerdns.com.
...
;; ANSWER SECTION:
powerdns.com.		3600	IN	SOA	pdns-public-ns1.powerdns.com. pieter\.lexis.powerdns.com. 2017101203 10800 3600 604800 3600
powerdns.com.		3600	IN	RRSIG	SOA 8 2 3600 20171026000000 20171005000000 36021 powerdns.com. C/VixIC4NriFNtWrA9eTUprDPos9lph36ol+klQ6W7SAdI86QL5SvRVT jREjdzignOjl2pKUv3mjeOPBR+lZhNdJBo1OD9Gpy6wv8fLwE9tM9/Rk qmM3Sq7/bfUw+y2tRV9UudKRWJLTHLSCUMTisyGtLfaOt68h+/4USfgR ZOU=
```

remove it:
```
sqlite> delete from domainmetadata where kind='SOA-EDIT';
```

wait for cache. Retry dig:
```
;; ANSWER SECTION:
powerdns.com.		3600	IN	RRSIG	SOA 8 2 3600 20171026000000 20171005000000 36021 powerdns.com. C/VixIC4NriFNtWrA9eTUprDPos9lph36ol+klQ6W7SAdI86QL5SvRVT jREjdzignOjl2pKUv3mjeOPBR+lZhNdJBo1OD9Gpy6wv8fLwE9tM9/Rk qmM3Sq7/bfUw+y2tRV9UudKRWJLTHLSCUMTisyGtLfaOt68h+/4USfgR ZOU=
powerdns.com.		3600	IN	SOA	pdns-public-ns1.powerdns.com. pieter\.lexis.powerdns.com. 2017101201 10800 3600 604800 3600
```

note slightly lowered serial. This one validates.

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
When a zone is PRESIGNED, we should ignore the SOA-EDIT setting for it, as otherwise we cause the SOA signature to be bogus.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [x] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

File: pdns/dbdnsseckeeper.cc [hunk 1]
```diff
@@ -233,6 +233,11 @@ void DNSSECKeeper::getSoaEdit(const DNSName& zname, std::string& value)
...
   static const string soaEditSigned(::arg()["default-soa-edit-signed"]);
 
+  if (isPresigned(zname)) {
+    // SOA editing on a presigned zone never makes sense
+    return;
+  }
+
   getFromMeta(zname, "SOA-EDIT", value);
 
   if ((!soaEdit.empty() || !soaEditSigned.empty()) && value.empty() && !isPresigned(zname)) {
```
Comment (rgacogne) [inline pdns/dbdnsseckeeper.cc]: The `&& !isPresigned(zname)` part could be removed now

Comment (Habbie) [reply pdns/dbdnsseckeeper.cc]: Thanks, amended & pushed.
