### PR TITLE
Auth: start DNSProxy before doing secpoll

### LINKED ISSUE #2453: Security poll on startup not working when using recursor pass-through
PowerDNS auth is set up with a recursor= line in the config to pass through recursive queries; it's set as nameserver in resolv.conf on the auth system itself as well.

When starting up the auth server, it wtries to do a secpoll, but fails, because recursor forwarding is not yet started at that point.

It does fall through to the next resolv.conf entry though -- only that one was down at this point for me, so I noticed the error code.

Probablty secpoll should be done after recursor forwarding is started.

Confirmed by Peter on IRC.

### PR DESCRIPTION
**Pull request by pieterlexis**
Fixes #2453

### CODE REVIEW

**Comment by Habbie** [comment]
Nitpick: this starts the proxy before dropping privs which means a few packets might get passed back and forth as root.

**Comment by cmouse** [comment]
@Habbie interestingly, so does doSecPoll.

**Comment by Habbie** [comment]
Yes, we noticed that too :)

**Comment by pieterlexis** [comment]
@cmouse: how's this?

**Comment by mind04** [comment]
- Please keep all secpoll code in secpoll.cc. The current fragmentation is confusing.
- Recursor and secpoll are now running as root.
- I'm not sure about the recursor in auth replacing the ones in resolve.conf, maybe use the recursor in auth as the recursor of last resort? But even then I'm no fan of bypassing resolv.conf. I think the allow-recursion setting will complicate things, or at least add confusion, when secpoll does not resolve.

**Comment by pieterlexis** [comment]
@mind04 like this?

**Comment by mind04** [comment]
:+1:

File: pdns/secpoll-auth.cc [hunk 1]
```diff
@@ -45,7 +45,7 @@ static vector<ComboAddress> parseResolveConf()
       for(vector<string>::const_iterator iter = parts.begin()+1; iter != parts.end(); ++iter) {
 	
 	try {
-	  ret.push_back(ComboAddress(*iter, 53));
+	  s_servers.push_back(ComboAddress(*iter, 53));
```
Comment (ahupowerdns) [inline pdns/secpoll-auth.cc]: s_servers? s_nameservers? s_resolvers? s_resolverconfservers?

File: pdns/secpoll-auth.cc [hunk 2]
```diff
@@ -69,13 +67,16 @@ int doResolve(const string& qname, uint16_t qtype, vector<DNSResourceRecord>& re
...
-    s_servers = servers; // in case we chrooted in the meantime
+  if (s_servers.empty()) {
+    L<<Logger::Warning<<"No recursors set, secpoll impossible."<<endl;
+    return RCode::ServFail;
+  }
 
-  if(s_servers.empty())
-    L<<Logger::Warning<<"Unable to poll PowerDNS security status, did not get any servers from resolv.conf"<<endl;
+  string msg ="Doing secpoll, using resolvers: ";
+  for (ComboAddress server : s_servers) {
```
Comment (ahupowerdns) [inline pdns/secpoll-auth.cc]: nit - you could do const auto& server here, or ComboAddress& - not important here, but important for performance in other places.

File: pdns/secpoll-auth.cc (hunk 1 above)
Comment (pieterlexis) [inline pdns/secpoll-auth.cc]: I kept to using the existing nomenclature for this variable, but it might help to rename it to `s_secpollresolvers`.

File: pdns/secpoll-auth.cc (hunk 2 above)
Comment (pieterlexis) [inline pdns/secpoll-auth.cc]: As we're on a C++ 2011 binge, let's go :)
