### PR TITLE
auth API: when querying with rrset_name, respect it for comments too

### LINKED ISSUE #14539: API calls "GET /servers/{server_id}/zones/{zone_id}" with query parameters 'rrset_name' doesn't limit to the specified RRSets
- [X] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [X] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative
 - Issue type: Bug report

### Short description

Calling the API "GET /servers/{server_id}/zones/{zone_id}" with query parameters 'rrset_name' and rrset_type doesn't limit the output to the specified RRSet.  
For example, it returns the comments for another RRSet

### Environment

 - Operating system: kubernetes
 - Software version:  4.8.4 
 - Software source: below output from `pdns_server --version`
```
Jul 30 14:18:04 Features: libcrypto-ecdsa libcrypto-ed25519 libcrypto-ed448 libcrypto-eddsa lua lua-records PKCS#11 protobuf sodium curl DoT scrypt 
Jul 30 14:18:04 Built-in modules: 
Jul 30 14:18:04 Configured with: " '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--runstatedir=/run' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-option-checking=fatal' '--sysconfdir=/etc/pdns' '--disable-static' '--disable-dependency-tracking' '--disable-silent-rules' '--with-modules=' '--with-lua=luajit' '--with-dynmodules= bind gmysql gpgsql pipe remote ldap lua2 gsqlite3 tinydns' '--enable-tools' '--with-libsodium' '--enable-ixfrdist' '--enable-unit-tests' '--enable-lua-records' '--enable-experimental-pkcs11' '--enable-dns-over-tls' '--enable-systemd' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CC=gcc' 'CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer ' 'LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld-errors -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes ' 'CPPFLAGS=-DLDAP_DEPRECATED' 'CXX=g++' 'CXXFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer ' 'LT_SYS_LIBRARY_PATH=/usr/lib64:' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'"
```

### Steps to reproduce

1. Create a zone:
```bash
cat > zone.json <<EOF
{"name": "helloworld.com.", "kind": "Native", "masters": [], "nameservers": ["ns1.helloworld.com.", "ns2.helloworld.com."]}
EOF
```

```bash
curl -X POST -H "X-API-Key: secret" -H "Content-Type: application/json" -d@zone.json "http://localhost:8081/api/v1/servers/localhost/zones"
```
2. Create the records

```bash
cat > record-test.helloworld.com.json <<EOF
{
    "rrsets":
    [
        {
            "name": "test.helloworld.com.",
            "type": "A",
            "ttl": 3600,
            "changetype": "REPLACE",
            "comments":
            [
	            {
                "account": "powerdns-operator",
                "content": "a very important comment",
                "modified_at": 1722338368
            	}
    		],
            "records":
            [
                {
                    "content": "1.1.1.1",
                    "disabled": false
                },
                {
                    "content": "2.2.2.2",
                    "disabled": false
                }
            ]
        }
    ]
}
EOF
```

```bash
cat > record-test1.helloworld.com.json <<EOF
{
    "rrsets":
    [
        {
            "name": "test1.helloworld.com.",
            "type": "A",
            "ttl": 3600,
            "changetype": "REPLACE",
            "records":
            [
                {
                    "content": "1.1.1.1",
                    "disabled": false
                }
            ]
        }
    ]
}
EOF
```

```bash
curl -X PATCH -H "X-API-Key: secret" -H "Content-Type: application/json" -d@record-test.helloworld.com.json "http://localhost:8081/api/v1/servers/localhost/zones/helloworld.com"
```

```bash
curl -X PATCH -H "X-API-Key: secret" -H "Content-Type: application/json" -d@record-test1.helloworld.com.json "http://localhost:8081/api/v1/servers/localhost/zones/helloworld.com"
```
3. Verify informations
```bash
curl -H "X-API-Key: secret" "http://localhost:8081/api/v1/servers/localhost/zones/helloworld.com"
```
```json
{
    "account": "",
    "api_rectify": false,
    "catalog": "",
    "dnssec": false,
    "edited_serial": 2024073004,
    "id": "helloworld.com.",
    "kind": "Native",
    "last_check": 0,
    "master_tsig_key_ids":     [],
    "masters":    [],
    "name": "helloworld.com.",
    "notified_serial": 0,
    "nsec3narrow": false,
    "nsec3param": "",
    "rrsets":    [
        {
            "comments":
            [
                {
                    "account": "powerdns-operator",
                    "content": "a very important comment",
                    "modified_at": 1722345870
                }
            ],
            "name": "test.helloworld.com.",
            "records":
            [
                {
                    "content": "1.1.1.1",
                    "disabled": false
                },
                {
                    "content": "2.2.2.2",
                    "disabled": false
                }
            ],
            "ttl": 300,
            "type": "A"
        },
        {
            "comments":
            [],
            "name": "test1.helloworld.com.",
            "records":
            [
                {
                    "content": "1.1.1.1",
                    "disabled": false
                }
            ],
            "ttl": 300,
            "type": "A"
        },
        {
            "comments":
            [],
            "name": "helloworld.com.",
            "records":
            [
                {
                    "content": "a.misconfigured.dns.server.invalid. hostmaster.helloworld.com. 2024073004 10800 3600 604800 3600",
                    "disabled": false
                }
            ],
            "ttl": 1500,
            "type": "SOA"
        },
        {
            "comments":
            [],
            "name": "helloworld.com.",
            "records":
            [
                {
                    "content": "ns1.helloworld.com.",
                    "disabled": false
                },
                {
                    "content": "ns2.helloworld.com.",
                    "disabled": false
                }
            ],
            "ttl": 1500,
            "type": "NS"
        }
    ],
    "serial": 2024073004,
    "slave_tsig_key_ids":
    [],
    "soa_edit": "",
    "soa_edit_api": "DEFAULT",
    "url": "/api/v1/servers/localhost/zones/helloworld.com."
}
```
4. Get informations about Zone for a specific RRSet
```bash
curl -H "X-API-Key: secret" "http://localhost:8083/api/v1/servers/localhost/zones/helloworld.com?rrset_name=test1.helloworld.com&rrset_type=A"
```
```json
{
    "account": "",
    "api_rectify": false,
    "catalog": "",
    "dnssec": false,
    "edited_serial": 2024073004,
    "id": "helloworld.com.",
    "kind": "Native",
    "last_check": 0,
    "master_tsig_key_ids":
    [],
    "masters":
    [],
    "name": "helloworld.com.",
    "notified_serial": 0,
    "nsec3narrow": false,
    "nsec3param": "",
    "rrsets":
    [
        {
            "comments":
            [
                {
                    "account": "powerdns-operator",
                    "content": "a very important comment",
                    "modified_at": 1722345870
                }
            ],
            "name": "test.helloworld.com.",
            "records":
            [],
            "ttl": 0,
            "type": "A"
        },
        {
            "comments":
            [],
            "name": "test1.helloworld.com.",
            "records":
            [
                {
                    "content": "1.1.1.1",
                    "disabled": false
                }
            ],
            "ttl": 300,
            "type": "A"
        }
    ],
    "serial": 2024073004,
    "slave_tsig_key_ids":
    [],
    "soa_edit": "",
    "soa_edit_api": "DEFAULT",
    "url": "/api/v1/servers/localhost/zones/helloworld.com."
}
```
### Expected behaviour
I expected the output for step 4. not to include the following rrset:
```json
        {
            "comments":
            [
                {
                    "account": "powerdns-operator",
                    "content": "a very important comment",
                    "modified_at": 1722345870
                }
            ],
            "name": "test.helloworld.com.",
            "records":
            [],
            "ttl": 0,
            "type": "A"
        },
```
### Actual behaviour
See step 4.

### PR DESCRIPTION
**Pull request by Habbie**
### Short description
While `rrset_name` (plus optionally `rrset_type`) turns `list` into `lookup` for records, we don't have `lookup` for comments, so we need to filter those comments out explicitly after listing them all from the database.

This also shows that in case of a zone with lots of comments, the 'rrset filter' (which actually -is- efficient for records) does a lot of extra work for comments.

~~Needs a test.~~ has a test now

Fixes #14539

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Comment by Habbie** [comment]
> Needs a test.

now rewritten to be much simpler, and now includes a test

**Comment by Habbie** [comment]
> This also shows that in case of a zone with lots of comments, the 'rrset filter' (which actually -is- efficient for records) does a lot of extra work for comments.

noted down separately in #14357

**Comment by omoerbeek** [comment]
No review (yet), but I remember testing a case when you were working on this. It was fixed using this PR.

File: pdns/ws-auth.cc [hunk 1]
```diff
@@ -445,21 +445,21 @@ static void fillZone(UeberBackend& backend, const DNSName& zonename, HttpRespons
...
       }
       else {
-        QType qType;
-        if (req->getvars.count("rrset_type") == 0) {
-          qType = QType::ANY;
-        }
-        else {
+        qName = DNSName(req->getvars["rrset_name"]);
+        if (req->getvars.count("rrset_type") != 0) {
           qType = req->getvars["rrset_type"];
```
Comment (omoerbeek) [inline pdns/ws-auth.cc:460]: Never a big fan of this implicit conversion, but ok.

**Review by omoerbeek — APPROVED** [review]

File: pdns/ws-auth.cc (hunk 1 above)
Comment (Habbie) [reply pdns/ws-auth.cc:460]: looking at this made me realise I'd prefer the throw-on-unknown-type variant (`DNSRecordContent::TypeToNumber`) here, but I don't want to backport that, so I'll clean up separately.

Comment (Habbie) [reply pdns/ws-auth.cc:460]: the throwing version causes Internal Server Error, so that will require a bigger rework. Given that this is a search, I'll leave it at the current "nothing found" behaviour for now

Comment (Habbie) [reply pdns/ws-auth.cc:460]: indeed, but from just seeing the assignment it's hard to figure out what happens for wrong types

Comment (zeha) [reply pdns/ws-auth.cc:460]: yes. might have been worth a comment.
not failing the request has a slight advantage for forward-compat, but 🤷🏼

Comment (Habbie) [reply pdns/ws-auth.cc:460]: yeah, I also realised a comment would have been nice
