### PR TITLE
auth: createForward and createForward6 will use the zone_record as base

### LINKED ISSUE #7522: createForward6() not working properly when used one label down from the apex
- Program: Authoritative 4.2-alpha
 - Issue type: Bug report

### Short description

`createForward6()` does not function the way the documentation describes. It only works in the root of a zone, not one label down.

### Environment
 - Operating system: Ubuntu 18.10 (cosmic)
 - Software version: 4.2.0~alpha1-1pdns.cosmic
 - Software source: PowerDNS repository

### Steps to reproduce

1. Create `*.static.example.com IN LUA AAAA "createForward6()"` within the zone `example.com`.
2. Query the record `dig aaaa 2001-db8--1.static.example.com`

### Expected behaviour

It should return:

```
2001-db8--1.static.example.com. IN AAAA 2001:db8::1
```

### Actual behaviour

Instead, it returns:

```
2001-db8--1.static.example.com. IN AAAA ::
```

### Other information

This works properly a label higher (directly under the zone itself). I.e.:

```
*.example.com IN LUA AAAA createForward6()
```

Yields the proper answer of `2001-db8--1.example.com IN AAAA 2001:db8::1`.

### PR DESCRIPTION
**Pull request by BozhanL**
### Short description

`createForward` and `createForward6` will use the `zone_record` as base. Closes #7522
### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

### CODE REVIEW

**Review by miodvallat — APPROVED** [review]
Looking good.

**Review by Habbie — COMMENTED** [review]
agreed, looks good! A few small requests:

* can you handle clang-tidy's complaints? You can see them inline in the files view
* as far as I can tell, there is now no need to pass domain_id separately, so maybe just remove it

File: pdns/lua-record.cc [hunk 1]
```diff
@@ -915,8 +916,14 @@ static void setupLuaRecords(LuaContext& lua) // NOLINT(readability-function-cogn
       return std::string("error");
     });
   lua.writeFunction("createForward", []() {
-      static string allZerosIP("0.0.0.0");
-      DNSName rel=s_lua_record_ctx->qname.makeRelative(s_lua_record_ctx->zone);
+      static string allZerosIP{"0.0.0.0"};
+      DNSName record_name{s_lua_record_ctx->zone_record.d_name};
+      if (record_name.isWildcard() == false) {
```
Comment (BozhanL) [inline pdns/lua-record.cc:921]: From my understanding, the coding guideline recommends comparing to false explicitly. However, clang-tidy doesn't like this style. Which one is preferred?
https://github.com/PowerDNS/pdns/blob/788f396a78120c6c9ec0c5466fdfaa45b9145ce1/CODING_GUIDELINES.md?plain=1#L611-L615
https://github.com/PowerDNS/pdns/blob/788f396a78120c6c9ec0c5466fdfaa45b9145ce1/pdns/tkey.cc#L78
https://github.com/PowerDNS/pdns/blob/788f396a78120c6c9ec0c5466fdfaa45b9145ce1/pdns/dnsdistdist/dnsdist-lua.cc#L98

Comment (Habbie) [reply pdns/lua-record.cc:921]: ohh. Our guideline and our clang-tidy config are in conflict then. For now, let's make clang-tidy happy.

**Review by Habbie — APPROVED** [review]
