### PR TITLE
rec: Be more careful using refresh mode only for the record asked.

### LINKED ISSUE #11371: rec: Refetch confused, repetitive queries to root, TLDs fail temporarily
- Program: Recursor
 - Issue type: Bug report

### Short description
As you know, I run master and turned refetch on recently. As you may or may not know, I scan hundreds of TLDs sometimes (mostly `DNSKEY` and `SOA`). If timed right, it can queue up a lot of refetches (or maybe `AAAA` tasks).

Something weird just happened with many Donuts TLDs during or after a scan. (Donuts has a lot of TLDs, and they follow ~3 nameserver/TTL patterns. This affected the old Donuts TLDs with `v0n0`-style nameservers, rather than the old Afilias TLDs with `a0`-style nameservers and possibly different TTLs.)

Refetch started making repetitive queries for e.g. `example.`/`A`, and non-repetitive queries for e.g. `v0n0.nic.example.`/`A` and `AAAA`, all of them to the root servers.

It also seems to return `SERVFAIL` for the entire TLDs while this is going on, or shortly afterwards.

It logs errors sometimes.

The TLDs start to work correctly after a few minutes.

I also have some `trace-regex`es.

I am confuse. And I'm sorry this is vague and hard to reproduce.

### Environment
 - Operating system: Ubuntu 20.04 (amd64)
 - Software version: 4.7.0~alpha0+master.577.g256447562-1pdns.focal
 - Software source: PowerDNS repository

### Steps to reproduce
I am not sure.
1. Configure PowerDNS as below
2. Run `dig wtf dnskey` and `dig wtf soa` periodically for a few days
3. Maybe run `dig wtf ns`, `dig v0n0.nic.wtf`, `dig v0n0.nic.wtf aaaa` and so on

### Expected behaviour
No SERVFAIL.

Ideally, fewer duplicate queries.

### Actual behaviour
Suffering.

### Other information
I have some information. I switched TLDs to get fresher data and because they were all (temporarily) broken.

`tcpdump` for one TLD:

```
2022-02-27 05:54:52.030007 IP 45.79.214.107.19467 > 192.5.5.241.53: 58811 [1au] A? place. (34)
2022-02-27 05:54:52.030674 IP 192.5.5.241.53 > 45.79.214.107.19467: 58811- 0/8/13 (751)
2022-02-27 05:54:52.031069 IP 45.79.214.107.31857 > 199.7.83.42.53: 60482 [1au] A? place. (34)
2022-02-27 05:54:52.047703 IP 199.7.83.42.53 > 45.79.214.107.31857: 60482- 0/8/13 (751)
2022-02-27 05:54:52.048446 IP6 2600:3c02:e000:74::53c:1.52966 > 2001:7fe::53.53: 62702 [1au] A? v0n0.nic.place. (43)
2022-02-27 05:54:52.064080 IP6 2001:7fe::53.53 > 2600:3c02:e000:74::53c:1.52966: 62702- 0/8/13 (756)
2022-02-27 05:54:52.064809 IP 45.79.214.107.3244 > 192.5.5.241.53: 14074 [1au] A? v0n1.nic.place. (43)
2022-02-27 05:54:52.066486 IP 192.5.5.241.53 > 45.79.214.107.3244: 14074- 0/8/13 (751)
2022-02-27 05:54:52.066866 IP 45.79.214.107.37582 > 193.0.14.129.53: 5458 [1au] A? v0n2.nic.place. (43)
2022-02-27 05:54:52.082861 IP 193.0.14.129.53 > 45.79.214.107.37582: 5458- 0/8/13 (756)
2022-02-27 05:54:52.083441 IP6 2600:3c02:e000:74::53c:1.60432 > 2001:500:200::b.53: 61011 [1au] A? v0n3.nic.place. (43)
2022-02-27 05:54:52.098510 IP6 2001:500:200::b.53 > 2600:3c02:e000:74::53c:1.60432: 61011- 0/8/13 (756)
2022-02-27 05:54:52.099258 IP6 2600:3c02:e000:74::53c:1.37308 > 2001:500:2f::f.53: 3939 [1au] AAAA? v0n0.nic.place. (43)
2022-02-27 05:54:52.101022 IP6 2001:500:2f::f.53 > 2600:3c02:e000:74::53c:1.37308: 3939- 0/8/13 (751)
2022-02-27 05:54:52.101419 IP 45.79.214.107.18712 > 192.203.230.10.53: 32174 [1au] AAAA? v0n1.nic.place. (43)
2022-02-27 05:54:52.113009 IP 192.203.230.10.53 > 45.79.214.107.18712: 32174- 0/8/13 (751)
2022-02-27 05:54:52.113604 IP6 2600:3c02:e000:74::53c:1.56548 > 2001:500:9f::42.53: 21131 [1au] AAAA? v0n3.nic.place. (43)
2022-02-27 05:54:52.130410 IP6 2001:500:9f::42.53 > 2600:3c02:e000:74::53c:1.56548: 21131- 0/8/13 (756)
2022-02-27 05:54:52.131106 IP6 2600:3c02:e000:74::53c:1.45124 > 2001:7fd::1.53: 53872 [1au] AAAA? v0n1.nic.place. (43)
2022-02-27 05:54:52.146172 IP6 2001:7fd::1.53 > 2600:3c02:e000:74::53c:1.45124: 53872- 0/8/13 (756)
2022-02-27 05:54:52.146977 IP 45.79.214.107.56628 > 198.97.190.53.53: 16732 [1au] A? v2n0.nic.place. (43)
2022-02-27 05:54:52.164753 IP 198.97.190.53.53 > 45.79.214.107.56628: 16732- 0/8/13 (751)
2022-02-27 05:54:52.165618 IP 45.79.214.107.13629 > 199.7.91.13.53: 55812 [1au] AAAA? v0n2.nic.place. (43)
2022-02-27 05:54:52.182809 IP 199.7.91.13.53 > 45.79.214.107.13629: 55812- 0/8/13 (751)
2022-02-27 05:54:52.183607 IP6 2600:3c02:e000:74::53c:1.25385 > 2001:500:2::c.53: 20496 [1au] AAAA? v2n0.nic.place. (43)
2022-02-27 05:54:52.201083 IP6 2001:500:2::c.53 > 2600:3c02:e000:74::53c:1.25385: 20496- 0/8/13 (751)
2022-02-27 05:54:52.201815 IP6 2600:3c02:e000:74::53c:1.13391 > 2001:500:a8::e.53: 55096 [1au] A? v2n1.nic.place. (43)
2022-02-27 05:54:52.202329 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.13391: 55096- 0/8/13 (751)
2022-02-27 05:54:52.203139 IP6 2600:3c02:e000:74::53c:1.5244 > 2001:500:a8::e.53: 45282 [1au] AAAA? v2n1.nic.place. (43)
2022-02-27 05:54:52.203763 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.5244: 45282- 0/8/13 (751)
2022-02-27 05:54:56.722790 IP6 2600:3c02:e000:74::53c:1.53459 > 2001:500:a8::e.53: 3414 [1au] A? place. (34)
2022-02-27 05:54:56.723365 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.53459: 3414- 0/8/13 (751)
2022-02-27 05:54:56.723908 IP6 2600:3c02:e000:74::53c:1.63834 > 2001:500:a8::e.53: 4584 [1au] A? place. (34)
2022-02-27 05:54:56.725547 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.63834: 4584- 0/8/13 (751)
2022-02-27 05:54:56.726247 IP6 2600:3c02:e000:74::53c:1.30784 > 2001:500:1::53.53: 65350 [1au] AAAA? v0n0.nic.place. (43)
2022-02-27 05:54:56.744499 IP6 2001:500:1::53.53 > 2600:3c02:e000:74::53c:1.30784: 65350- 0/8/13 (751)
2022-02-27 05:54:56.745317 IP 45.79.214.107.26898 > 192.5.5.241.53: 37895 [1au] A? v0n3.nic.place. (43)
2022-02-27 05:54:56.746136 IP 192.5.5.241.53 > 45.79.214.107.26898: 37895- 0/8/13 (751)
2022-02-27 05:54:56.746600 IP 45.79.214.107.59455 > 192.5.5.241.53: 35533 [1au] A? v0n2.nic.place. (43)
2022-02-27 05:54:56.747345 IP 192.5.5.241.53 > 45.79.214.107.59455: 35533- 0/8/13 (751)
2022-02-27 05:54:56.747774 IP 45.79.214.107.20770 > 192.5.5.241.53: 875 [1au] A? v0n1.nic.place. (43)
2022-02-27 05:54:56.748433 IP 192.5.5.241.53 > 45.79.214.107.20770: 875- 0/8/13 (751)
2022-02-27 05:54:56.748954 IP 45.79.214.107.28449 > 192.5.5.241.53: 43483 [1au] AAAA? v0n2.nic.place. (43)
2022-02-27 05:54:56.749583 IP 192.5.5.241.53 > 45.79.214.107.28449: 43483- 0/8/13 (751)
2022-02-27 05:54:56.750016 IP 45.79.214.107.18386 > 192.5.5.241.53: 17156 [1au] A? v2n0.nic.place. (43)
2022-02-27 05:54:56.750685 IP 192.5.5.241.53 > 45.79.214.107.18386: 17156- 0/8/13 (751)
2022-02-27 05:54:56.751183 IP 45.79.214.107.65184 > 192.5.5.241.53: 44115 [1au] AAAA? v0n2.nic.place. (43)
2022-02-27 05:54:56.751780 IP 192.5.5.241.53 > 45.79.214.107.65184: 44115- 0/8/13 (751)
2022-02-27 05:54:56.752300 IP 45.79.214.107.46952 > 192.5.5.241.53: 40793 [1au] AAAA? v0n1.nic.place. (43)
2022-02-27 05:54:56.752960 IP 192.5.5.241.53 > 45.79.214.107.46952: 40793- 0/8/13 (751)
2022-02-27 05:54:56.753363 IP 45.79.214.107.51155 > 192.5.5.241.53: 27249 [1au] A? v0n0.nic.place. (43)
2022-02-27 05:54:56.753975 IP 192.5.5.241.53 > 45.79.214.107.51155: 27249- 0/8/13 (751)
2022-02-27 05:54:56.754406 IP 45.79.214.107.25414 > 192.5.5.241.53: 41765 [1au] A? v2n1.nic.place. (43)
2022-02-27 05:54:56.754980 IP 192.5.5.241.53 > 45.79.214.107.25414: 41765- 0/8/13 (751)
2022-02-27 05:54:56.755478 IP 45.79.214.107.12946 > 192.5.5.241.53: 19479 [1au] AAAA? v2n0.nic.place. (43)
2022-02-27 05:54:56.756380 IP 192.5.5.241.53 > 45.79.214.107.12946: 19479- 0/8/13 (751)
2022-02-27 05:54:56.757245 IP 45.79.214.107.18657 > 192.5.5.241.53: 39615 [1au] AAAA? v2n1.nic.place. (43)
2022-02-27 05:54:56.757864 IP 192.5.5.241.53 > 45.79.214.107.18657: 39615- 0/8/13 (751)
2022-02-27 05:54:56.759082 IP 45.79.214.107.39982 > 192.5.5.241.53: 23304 [1au] AAAA? v0n3.nic.place. (43)
2022-02-27 05:54:56.759693 IP 192.5.5.241.53 > 45.79.214.107.39982: 23304- 0/8/13 (751)
2022-02-27 05:54:59.773983 IP 45.79.214.107.44074 > 192.5.5.241.53: 32292 [1au] A? place. (34)
2022-02-27 05:54:59.774756 IP 192.5.5.241.53 > 45.79.214.107.44074: 32292- 0/8/13 (751)
2022-02-27 05:54:59.775256 IP 45.79.214.107.39247 > 192.5.5.241.53: 64153 [1au] A? place. (34)
2022-02-27 05:54:59.776106 IP 192.5.5.241.53 > 45.79.214.107.39247: 64153- 0/8/13 (751)
2022-02-27 05:54:59.776596 IP 45.79.214.107.8236 > 192.5.5.241.53: 33425 [1au] A? v0n1.nic.place. (43)
2022-02-27 05:54:59.778350 IP 192.5.5.241.53 > 45.79.214.107.8236: 33425- 0/8/13 (751)
2022-02-27 05:54:59.778851 IP6 2600:3c02:e000:74::53c:1.12810 > 2001:500:a8::e.53: 50420 [1au] A? v0n3.nic.place. (43)
2022-02-27 05:54:59.779469 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.12810: 50420- 0/8/13 (751)
2022-02-27 05:54:59.779899 IP6 2600:3c02:e000:74::53c:1.63853 > 2001:500:a8::e.53: 20594 [1au] A? v0n0.nic.place. (43)
2022-02-27 05:54:59.780574 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.63853: 20594- 0/8/13 (751)
2022-02-27 05:54:59.781046 IP6 2600:3c02:e000:74::53c:1.52651 > 2001:500:a8::e.53: 65095 [1au] A? v2n0.nic.place. (43)
2022-02-27 05:54:59.781615 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.52651: 65095- 0/8/13 (751)
2022-02-27 05:54:59.782061 IP6 2600:3c02:e000:74::53c:1.25086 > 2001:500:a8::e.53: 55252 [1au] A? v2n1.nic.place. (43)
2022-02-27 05:54:59.782645 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.25086: 55252- 0/8/13 (751)
2022-02-27 05:54:59.783206 IP6 2600:3c02:e000:74::53c:1.61514 > 2001:500:a8::e.53: 24599 [1au] AAAA? v0n0.nic.place. (43)
2022-02-27 05:54:59.783725 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.61514: 24599- 0/8/13 (751)
2022-02-27 05:54:59.784243 IP6 2600:3c02:e000:74::53c:1.49038 > 2001:500:a8::e.53: 39883 [1au] AAAA? v2n1.nic.place. (43)
2022-02-27 05:54:59.785981 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.49038: 39883- 0/8/13 (751)
2022-02-27 05:54:59.786524 IP6 2600:3c02:e000:74::53c:1.61615 > 2001:500:a8::e.53: 36973 [1au] AAAA? v2n0.nic.place. (43)
2022-02-27 05:54:59.786995 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.61615: 36973- 0/8/13 (751)
2022-02-27 05:54:59.787482 IP6 2600:3c02:e000:74::53c:1.13898 > 2001:500:a8::e.53: 35117 [1au] AAAA? v0n0.nic.place. (43)
2022-02-27 05:54:59.788062 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.13898: 35117- 0/8/13 (751)
2022-02-27 05:54:59.788485 IP6 2600:3c02:e000:74::53c:1.45069 > 2001:500:a8::e.53: 6554 [1au] AAAA? v0n3.nic.place. (43)
2022-02-27 05:54:59.789096 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.45069: 6554- 0/8/13 (751)
2022-02-27 05:55:03.295455 IP6 2600:3c02:e000:74::53c:1.13104 > 2001:500:a8::e.53: 26992 [1au] A? place. (34)
2022-02-27 05:55:03.296128 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.13104: 26992- 0/8/13 (751)
2022-02-27 05:55:03.296562 IP6 2600:3c02:e000:74::53c:1.36406 > 2001:500:a8::e.53: 14124 [1au] A? place. (34)
2022-02-27 05:55:03.297135 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.36406: 14124- 0/8/13 (751)
2022-02-27 05:55:03.297535 IP6 2600:3c02:e000:74::53c:1.21653 > 2001:500:a8::e.53: 18211 [1au] AAAA? v0n1.nic.place. (43)
2022-02-27 05:55:03.298229 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.21653: 18211- 0/8/13 (751)
2022-02-27 05:55:08.304984 IP6 2600:3c02:e000:74::53c:1.50999 > 2001:500:a8::e.53: 25159 [1au] A? place. (34)
2022-02-27 05:55:08.305676 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.50999: 25159- 0/8/13 (751)
2022-02-27 05:55:08.306360 IP6 2600:3c02:e000:74::53c:1.58359 > 2001:500:a8::e.53: 40485 [1au] A? place. (34)
2022-02-27 05:55:08.307689 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.58359: 40485- 0/8/13 (751)
2022-02-27 05:55:08.308345 IP6 2600:3c02:e000:74::53c:1.35481 > 2001:500:a8::e.53: 57622 [1au] A? v0n2.nic.place. (43)
2022-02-27 05:55:08.308910 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.35481: 57622- 0/8/13 (751)
2022-02-27 05:55:13.314887 IP6 2600:3c02:e000:74::53c:1.4921 > 2001:500:a8::e.53: 5073 [1au] A? place. (34)
2022-02-27 05:55:13.315465 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.4921: 5073- 0/8/13 (751)
2022-02-27 05:55:13.315931 IP6 2600:3c02:e000:74::53c:1.32601 > 2001:500:a8::e.53: 12826 [1au] A? place. (34)
2022-02-27 05:55:13.316621 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.32601: 12826- 0/8/13 (751)
2022-02-27 05:55:13.317039 IP6 2600:3c02:e000:74::53c:1.63095 > 2001:500:a8::e.53: 50691 [1au] AAAA? v0n2.nic.place. (43)
2022-02-27 05:55:13.317529 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.63095: 50691- 0/8/13 (751)
2022-02-27 05:55:18.323437 IP6 2600:3c02:e000:74::53c:1.48807 > 2001:500:a8::e.53: 8820 [1au] A? place. (34)
2022-02-27 05:55:18.324182 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.48807: 8820- 0/8/13 (751)
2022-02-27 05:55:18.324815 IP6 2600:3c02:e000:74::53c:1.44324 > 2001:500:a8::e.53: 2566 [1au] A? place. (34)
2022-02-27 05:55:18.325458 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.44324: 2566- 0/8/13 (751)
2022-02-27 05:55:18.326125 IP6 2600:3c02:e000:74::53c:1.26138 > 2001:500:a8::e.53: 62999 [1au] A? v0n3.nic.place. (43)
2022-02-27 05:55:18.327788 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.26138: 62999- 0/8/13 (751)
2022-02-27 05:55:26.172423 IP 45.79.214.107.44649 > 192.112.36.4.53: 31117 [1au] A? place. (34)
2022-02-27 05:55:26.200798 IP 192.112.36.4.53 > 45.79.214.107.44649: 31117- 0/8/13 (756)
2022-02-27 05:55:26.201603 IP 45.79.214.107.33684 > 192.5.5.241.53: 59444 [1au] A? place. (34)
2022-02-27 05:55:26.202328 IP 192.5.5.241.53 > 45.79.214.107.33684: 59444- 0/8/13 (751)
2022-02-27 05:55:26.202744 IP 45.79.214.107.44432 > 192.5.5.241.53: 26372 [1au] AAAA? v0n3.nic.place. (43)
2022-02-27 05:55:26.203423 IP 192.5.5.241.53 > 45.79.214.107.44432: 26372- 0/8/13 (751)
2022-02-27 05:55:31.208937 IP 45.79.214.107.56906 > 192.5.5.241.53: 55176 [1au] A? place. (34)
2022-02-27 05:55:31.209581 IP 192.5.5.241.53 > 45.79.214.107.56906: 55176- 0/8/13 (751)
2022-02-27 05:55:31.209997 IP 45.79.214.107.40006 > 192.5.5.241.53: 30504 [1au] A? place. (34)
2022-02-27 05:55:31.210846 IP 192.5.5.241.53 > 45.79.214.107.40006: 30504- 0/8/13 (751)
2022-02-27 05:55:31.211263 IP6 2600:3c02:e000:74::53c:1.10561 > 2001:500:12::d0d.53: 58864 [1au] A? v2n0.nic.place. (43)
2022-02-27 05:55:31.239568 IP6 2001:500:12::d0d.53 > 2600:3c02:e000:74::53c:1.10561: 58864- 0/8/13 (756)
2022-02-27 05:55:36.245921 IP 45.79.214.107.43996 > 192.5.5.241.53: 6254 [1au] A? place. (34)
2022-02-27 05:55:36.247614 IP 192.5.5.241.53 > 45.79.214.107.43996: 6254- 0/8/13 (751)
2022-02-27 05:55:36.248072 IP6 2600:3c02:e000:74::53c:1.38818 > 2001:500:2f::f.53: 34209 [1au] A? place. (34)
2022-02-27 05:55:36.248712 IP6 2001:500:2f::f.53 > 2600:3c02:e000:74::53c:1.38818: 34209- 0/8/13 (751)
2022-02-27 05:55:36.249171 IP6 2600:3c02:e000:74::53c:1.9710 > 2001:500:2f::f.53: 24642 [1au] AAAA? v2n0.nic.place. (43)
2022-02-27 05:55:36.251005 IP6 2001:500:2f::f.53 > 2600:3c02:e000:74::53c:1.9710: 24642- 0/8/13 (751)
2022-02-27 05:55:41.257567 IP6 2600:3c02:e000:74::53c:1.3376 > 2001:503:ba3e::2:30.53: 4076 [1au] A? place. (34)
2022-02-27 05:55:41.258206 IP6 2001:503:ba3e::2:30.53 > 2600:3c02:e000:74::53c:1.3376: 4076- 0/8/13 (751)
2022-02-27 05:55:41.258592 IP6 2600:3c02:e000:74::53c:1.34327 > 2001:503:ba3e::2:30.53: 24559 [1au] A? place. (34)
2022-02-27 05:55:41.270014 IP6 2001:503:ba3e::2:30.53 > 2600:3c02:e000:74::53c:1.34327: 24559- 0/8/13 (751)
2022-02-27 05:55:41.270553 IP 45.79.214.107.42983 > 192.33.4.12.53: 13148 [1au] A? v2n1.nic.place. (43)
2022-02-27 05:55:41.288058 IP 192.33.4.12.53 > 45.79.214.107.42983: 13148- 0/8/13 (751)
2022-02-27 05:55:46.293867 IP6 2600:3c02:e000:74::53c:1.48507 > 2001:500:a8::e.53: 40340 [1au] A? place. (34)
2022-02-27 05:55:46.294509 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.48507: 40340- 0/8/13 (751)
2022-02-27 05:55:46.295132 IP6 2600:3c02:e000:74::53c:1.53332 > 2001:500:a8::e.53: 7629 [1au] A? place. (34)
2022-02-27 05:55:46.295722 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.53332: 7629- 0/8/13 (751)
2022-02-27 05:55:46.296434 IP6 2600:3c02:e000:74::53c:1.49552 > 2001:500:a8::e.53: 23885 [1au] AAAA? v2n1.nic.place. (43)
2022-02-27 05:55:46.297030 IP6 2001:500:a8::e.53 > 2600:3c02:e000:74::53c:1.49552: 23885- 0/8/13 (751)
```

`trace-regex` for `pictures` TLD with `dig pictures ns`:

(There was no EDE.)

```
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: 1 [15087/1] question for 'pictures|NS' from [::1]:46321
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: : no TA found for 'pictures' among 1
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: : got TA for '.'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: QM pictures.|NS child=(empty): doResolve
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Wants DNSSEC processing, auth data in query for 2
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Recursion not requested for 'pictures|2', peeking at auth/forward zones
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: QM pictures.|NS child=(empty): Step0 Not cached
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Checking if we have NS in cache for 'pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v0n0.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1474
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v0n1.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1478
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v0n2.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1483
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v0n3.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1490
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v2n0.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1498
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v2n1.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1505
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: We have NS in cache for 'pictures' (flawedNSSet=0)
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: QM pictures.|NS child=(empty): Step1 Ancestor from cache is pictures
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: QM pictures.|NS child=pictures: Step2 New child
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: QM pictures.|NS child=pictures: Step3 Going to do final resolve
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Wants DNSSEC processing, auth data in query for 2
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: No cache hit for 'pictures|2', trying to find an appropriate NS record
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Checking if we have NS in cache for 'pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v0n0.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1474
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v0n1.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1478
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v0n2.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1483
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v0n3.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1490
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v2n0.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1498
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS (with ip, or non-glue) in cache for 'pictures' -> 'v2n1.nic.pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: within bailiwick: 1,  in cache, ttl=1505
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: We have NS in cache for 'pictures' (flawedNSSet=0)
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Cache consultations done, have 6 NS to contact
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures.: Nameservers: v0n2.nic.pictures(0.00ms), v2n0.nic.pictures(0.00ms), v0n1.nic.pictures(0.00ms),
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures.:              v0n3.nic.pictures(0.00ms), v0n0.nic.pictures(0.00ms), v2n1.nic.pictures(0.00ms)
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS v0n2.nic.pictures in non-resolving map, skipping
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Failed to get IP for NS v0n2.nic.pictures, trying next if available
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS v2n0.nic.pictures in non-resolving map, skipping
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Failed to get IP for NS v2n0.nic.pictures, trying next if available
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS v0n1.nic.pictures in non-resolving map, skipping
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Failed to get IP for NS v0n1.nic.pictures, trying next if available
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS v0n3.nic.pictures in non-resolving map, skipping
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Failed to get IP for NS v0n3.nic.pictures, trying next if available
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS v0n0.nic.pictures in non-resolving map, skipping
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Failed to get IP for NS v0n0.nic.pictures, trying next if available
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: NS v2n1.nic.pictures in non-resolving map, skipping
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Failed to get IP for NS v2n1.nic.pictures, trying next if available
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Failed to resolve via any of the 6 offered NS at level 'pictures'
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: Ageing nameservers for level 'pictures', next query might succeed
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: pictures: failed (res=-1)
Feb 27 05:38:13 ultimate pdns-recursor[2865083]: QM pictures.|NS child=pictures: Step3 Final resolve: Server Failure/0
```

Successful `trace-regex` for `money` TLD at 05:36 and 05:37, even though the queries had failed at 05:30:

* `dig money ns`: https://mn0.us/R-Mcwd-zvx0f
* `dig v2n1.nic.money`: https://mn0.us/CRdFMPE5qtKU

FYI, sometimes it logs "deadline passed" errors, but I don't think that's a problem. E.g.:

```
Feb 27 06:15:50 ultimate pdns-recursor[2865083]: msg="deadline passed" oserror="Argument list too long" subsystem="taskq" level=0 ts="1645942550.972" name="v0n3.nic.digital" qtype="AAAA"
```

Configuration:

```
$ sudo rg -vN '^(#|$)' /etc/powerdns/recursor.conf
aggressive-nsec-cache-size=10000
allow-from=100.64.0.0/10, 127.0.0.0/8, ::1/128, 2600:3c02::f03c:91ff:fe70:fd08/128, 2600:3c02::f03c:91ff:febc:a28b/128, 2600:3c02::f03c:92ff:fefd:f09a/128, 2600:3c02:e000:74::/64, 2600:3c02:e000:bc::/64, 2600:3c02:e001:1d00::/56, fd7a:115c:a1e0::/48
allow-trust-anchor-query
any-to-tcp
carbon-ourname=ultimate_mattnordhoff_net
carbon-server=2a02:2770:8::2635:0:1
config-dir=/etc/powerdns
dnssec=validate
dnssec-log-bogus
edns-padding-from=100.64.0.0/10, fd7a:115c:a1e0::/48
edns-padding-mode=always
extended-resolution-errors
forward-zones=82.100.in-addr.arpa=2600:3c02:e000:74::53a:1, 83.100.in-addr.arpa=2600:3c02:e000:74::53a:1, 98.100.in-addr.arpa=2600:3c02:e000:74::53a:1, 122.100.in-addr.arpa=2600:3c02:e000:74::53a:1, d.f.ip6.arpa=2600:3c02:e000:74::53a:1
hint-file=/usr/share/dns/root.hints
include-dir=/etc/powerdns/recursor.d
local-address=100.82.87.107, 127.0.0.1, ::1, 2600:3c02:e000:74::53c:0, fd7a:115c:a1e0:ab12:4843:cd96:6252:576b
log-common-errors
lua-config-file=/etc/powerdns/recursor.lua
max-cache-entries=100000
max-cache-ttl=172800
max-negative-ttl=10800
max-packetcache-entries=50000
non-local-bind
query-local-address=0.0.0.0, ::
quiet=yes
refresh-on-ttl-perc=10
setgid=pdns
setuid=pdns
tcp-fast-open-connect
threads=1
udp-truncation-threshold=1452
```

```
$ cat /etc/powerdns/recursor.lua
dofile("/usr/share/pdns-recursor/lua-config/rootkeys.lua")

addNTA("82.100.in-addr.arpa")
addNTA("98.100.in-addr.arpa")
addNTA("122.100.in-addr.arpa")
addNTA("d.f.ip6.arpa")
```

### PR DESCRIPTION
**Pull request by omoerbeek**
Otherwise we get bad interaction with QM, as newly discovered
delegation points are stored in the cache, but not seen the QM
algorithm. Might/should fix #11371.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

**Comment by mnordhoff** [comment]
There are a few flaky servers in `rec_control dump-failedservers`, and I just saw it send a refetch query to one flaky server, resend it to a different server, and continue on without exploding.

**Comment by omoerbeek** [comment]
Good! Thanks for testing. I'll mark this as ready for review.

File: pdns/syncres.cc [hunk 1]
```diff
@@ -1661,7 +1661,7 @@ bool SyncRes::doCNAMECacheCheck(const DNSName &qname, const QType qtype, vector<
   QType foundQT = QType::ENT;
 
   /* we don't require auth data for forward-recurse lookups */
-  if (g_recCache->get(d_now.tv_sec, qname, QType::CNAME, !wasForwardRecurse && d_requireAuthData, &cset, d_cacheRemote, d_refresh, d_routingTag, d_doDNSSEC ? &signatures : nullptr, d_doDNSSEC ? &authorityRecs : nullptr, &d_wasVariable, &state, &wasAuth, &authZone, &d_fromAuthIP) > 0) {
```
Comment (rgacogne) [inline pdns/syncres.cc:1664]: Don't we want to keep using `d_refresh` for the CNAME (and then likely DNAME below) lookup?

**Review by rgacogne — COMMENTED** [review]
It makes sense to me to stop using the "refresh mode" when doing cache lookups for "infra" queries, although I'm not sure I agree with not using it for {C,D}NAME lookups.

File: pdns/syncres.cc (hunk 1 above)
Comment (omoerbeek) [reply pdns/syncres.cc:1664]: Maybe I am being over cautious. Will revisit.

**Comment by omoerbeek** [comment]
If we're doing respecting refresh mode in `{C,D}NAME` lookup, it does have the consequence that we will be doing explicit lookups for those qtypes. I'm wondering if that could be an issue...

**Comment by rgacogne** [comment]
> If we're respecting refresh mode in {C,D}NAME lookup, it does have the consequence that we will be doing explicit lookups for those qtypes. I'm wondering if that could be an issue...

If we have seen them before and they are about to expire, that seems fine to me.
