### PR TITLE
dnsdist: Change dnsdist stats functions to always return lowercase names

### LINKED ISSUE #5287: Normalize 0x20 queries in dnsdist statistics
- Program: dnsdist
 - Issue type: Bug report

### Short description

dnsdist copies the QNAME as sent by the client into the buffer used for generating statistics. As a result a client sending 0x20 queries generates odd output in topQueries().

### Environment
 - Operating system: Ubuntu 16.04
 - Software version: 1.1.0
 - Software source: pdns repo

### Other information
Example from production:
```
> topQueries(1000)
 100  0.conTRol4.Pool.NTp.org.                   13  0.1%
 135  MX.pool.ntp.org.                            6  0.1%
 198  1.lEDe.pOoL.ntP.oRg.                        2  0.0%
 246  _ntp._UdP.SG.POOL.NtP.Org.                  1  0.0%
 272  0.XX.pool.ntp.org.                          1  0.0%
 275  1.fReEbsd.pOol.nTP.Org.                     1  0.0%
 276  0.Se.pool.ntp.Org.                          1  0.0%

```

### PR DESCRIPTION
**Pull request by RobinGeuze**
### Short description
Changes getTopQueries and getGenResponses to return lowercase versions for all names. Closes #5287 

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/dnsdist-lua.cc [hunk 1]
```diff
@@ -158,7 +158,7 @@ std::unordered_map<int, vector<boost::variant<string,double>>> getGenResponses(u
   vector<pair<int, DNSName>> rcounts;
   rcounts.reserve(counts.size());
   for(const auto& c : counts) 
-    rcounts.push_back(make_pair(c.second, c.first));
+    rcounts.push_back(make_pair(c.second, c.first.makeLowerCase()));
```
Comment (rgacogne) [inline pdns/dnsdist-lua.cc]: I think you need to lowercase earlier otherwise the counts are going to be off.

File: pdns/dnsdist-lua.cc [hunk 2]
```diff
@@ -1351,7 +1351,7 @@ vector<std::function<void(void)>> setupLua(bool client, const std::string& confi
       vector<pair<int, DNSName>> rcounts;
       rcounts.reserve(counts.size());
       for(const auto& c : counts) 
-	rcounts.push_back(make_pair(c.second, c.first));
+	rcounts.push_back(make_pair(c.second, c.first.makeLowerCase()));
```
Comment (rgacogne) [inline pdns/dnsdist-lua.cc]: Same thing here.

File: pdns/dnsdist-lua.cc (hunk 1 above)
Comment (RobinGeuze) [inline pdns/dnsdist-lua.cc]: Nope since it uses maps, which uses the default compare and less operators, which in turn lowercase everything themselves.

File: pdns/dnsdist-lua.cc (hunk 2 above)
Comment (RobinGeuze) [inline pdns/dnsdist-lua.cc]: As above.

File: pdns/dnsdist-lua.cc (hunk 1 above)
Comment (rgacogne) [inline pdns/dnsdist-lua.cc]: Oh, you are right, my bad!

Comment (rgacogne) [inline pdns/dnsdist-lua.cc]: I wonder if it wouldn't be better to lowercase a bit later then, replacing `rc.second.toString()` by something like `rc.second.makeLowerCase().toString()`, so we only do the lowercasing for the names we are going to print, not all of them.
