### PR TITLE
Grow tinybackend capabilities a bit

### LINKED ISSUE #14563: tinydns backend and dns_notify: no such domain in our database
- [*] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [*] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Authoritative
 - Issue type: Bug report

### Short description
While "debugging" a few things in a new installation with tinydns backend (one single cdb file) I noticed that I'm unable to send notify to secondaries.
If I try to force it via pdns_control notify I get `No such domain xxx in our database`, despite `pdns_control list-zones` being flawless `All zonecount: 40`.
Meanwhile pdns answers all queries flawlessly.

So, I launched `pdnsutil check-all-zones` and I discovered that for every zone I get:
`[Error] Unable to get zone information for zone 'xxx'`
Also, for every zone after the first I get:
`[Error] Zone ID 4294967295 of 'xxx' in backend tinydns has already been used by zone 'firstzone' in backend tinydns. `
This is consistent with pdns assigning a default id to all tinydns zones but I wonder if it's part of the problem.

### Environment
 - Operating system: Gentoo linux kernel 6.6.30
 - Software version: 4.9.1
 - Software source: Gentoo packages

### Steps to reproduce
1. Configure pdns to run with a tinydns cdb backend (with more than one zone?)
2. Try `pdns_control notify` for any zone, it fails for me
Config, comments removed:
```allow-axfr-ips=127.0.0.0/8,::1
allow-axfr-ips+=150.145.42.11
allow-axfr-ips+=150.145.42.106
allow-axfr-ips+=192.167.160.13
allow-axfr-ips+=2a00:1620:a0::13
allow-axfr-ips+=194.119.192.34
allow-axfr-ips+=2a00:1620:c0:220:194:119:192:34
allow-axfr-ips+=150.146.205.10
allow-axfr-ips+=193.206.141.38
allow-axfr-ips+=2001:760:ffff:ffff::aa
allow-axfr-ips+=192.167.240.10
allow-axfr-ips+=192.167.170.250
allow-axfr-ips+=2a00:1620:a0:40::250
launch=tinydns
tinydns-dbfile=/service/tinydns6/root/data.cdb
load-modules=libgsqlite3backend.so, libtinydnsbackend.so
local-address=192.167.170.7,2a00:1620:a0:40::7
log-dns-queries=yes
primary=yes
query-local-address=192.167.170.7 2a00:1620:a0:40::7
setgid=pdns
setuid=pdns
```
### Additional information
Raised this in mailing list already, I was told it may be worthy of a bug report.

### PR DESCRIPTION
**Pull request by miodvallat**
### Short description
This PR extends the `TinyBackend` capabilities to:
- implement the `getDomainInfo` in order to query a single domain.
- make sure all backend functions which may end up discovering domains update the internal state, in order to make sure that we can compute unique domain ids which are not `-1`.

Fixes #14563

### Checklist
I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [X] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [X] probably introduced new bugs

### CODE REVIEW

File: modules/tinydnsbackend/tinydnsbackend.cc [hunk 1]
```diff
@@ -88,46 +88,45 @@ TinyDNSBackend::TinyDNSBackend(const string& suffix)
...
+  if (itByZone != zone_index.end()) {
+    return itByZone;
+  }
+
+  TinyDomainInfo tmp;
+  s_lastId++;
+  tmp.zone = domain.zone;
+  tmp.id = s_lastId;
+  tmp.notified_serial = domain.serial;
+  return state->insert(tmp).first;
```
Comment (Habbie) [inline modules/tinydnsbackend/tinydnsbackend.cc:104]: I guess this would "leak" if, over the runtime of an instance, a lot of domains get added and removed? (I'm not too concerned about this, to be clear)

File: modules/tinydnsbackend/tinydnsbackend.cc [hunk 2]
```diff
@@ -195,6 +194,52 @@ void TinyDNSBackend::getAllDomains(vector<DomainInfo>* domains, bool getSerial,
...
+    auto iter = updateState(domain, state);
+    // Keep domain id in sync with our current state.
+    domain.id = iter->id;
+  }
+}
+
+//NOLINTNEXTLINE(readability-identifier-length)
+bool TinyDNSBackend::getDomainInfo(const DNSName& domain, DomainInfo& di, bool getSerial)
+{
+  auto domainInfo = s_domainInfo.lock(); //TODO: We could actually lock less if we do it per suffix.
```
Comment (Habbie) [inline modules/tinydnsbackend/tinydnsbackend.cc:219]: doing it per suffix would cause ID reuse between the different backend instances. Having the map central (like this PR does now) actually makes more sense to me

**Review by Habbie — APPROVED** [review]
approved, with notes

File: modules/tinydnsbackend/tinydnsbackend.cc (hunk 1 above)
Comment (miodvallat) [reply modules/tinydnsbackend/tinydnsbackend.cc:104]: Yes. But then I really, really doubt people would be using TinyDNS to share hundreds of domains...

File: modules/tinydnsbackend/tinydnsbackend.cc (hunk 2 above)
Comment (miodvallat) [reply modules/tinydnsbackend/tinydnsbackend.cc:219]: I definitely did not want risk changing the existing logic and data structures too much at this point.

Comment (Habbie) [reply modules/tinydnsbackend/tinydnsbackend.cc:219]: understood. You can just remove the comments about doing it per suffix :)

File: modules/tinydnsbackend/tinydnsbackend.cc (hunk 1 above)
Comment (miodvallat) [reply modules/tinydnsbackend/tinydnsbackend.cc:104]: And how many domains did you delete in these 50k?

Comment (Habbie) [reply modules/tinydnsbackend/tinydnsbackend.cc:104]: churn was low

File: modules/tinydnsbackend/tinydnsbackend.cc (hunk 2 above)
Comment (miodvallat) [reply modules/tinydnsbackend/tinydnsbackend.cc:219]: Absolutely not, it was carefully cut'n'pasted from the existing code. It used to appear in `TinyDNSBackend::getUpdatedPrimaries`.

Comment (Habbie) [reply modules/tinydnsbackend/tinydnsbackend.cc:219]: oh right, ok. Then it's something to think about later :)
