### PR TITLE
recursor: Add DNAME support

### LINKED ISSUE #6318: Recursor not resolving DNSSEC signed DNAME
- Program: Recursor 
 - Issue type: Bug report 

### Short description

The recursor appears to not properly validate a DNAME per [RFC 6672](https://tools.ietf.org/html/rfc6672#section-5.3):

> ### 5.3.1.  Signed DNAME, Unsigned Synthesized CNAME
> In any response, a signed DNAME RR indicates a non-terminal
> redirection of the query.  There might or might not be a server-
> synthesized CNAME in the answer section; if there is, the CNAME will
> never be signed.  For a DNSSEC validator, verification of the DNAME
> RR and then that the CNAME was properly synthesized is sufficient
> proof.

Currently the resolver does not seem to validate this correctly (I have not verified the other parts of section 5.3).

### Environment

 - Operating system: Linux (Debian 9)
 - Software version: 4.1.1, 0.0.2018g9b7f95a-1pdns.stretch
 - Software source: PowerDNS repo

### Steps to reproduce

1. Enable DNSSEC validation on the recursor (`dnssec=validate`).
2. Request any record for any host in below a DNAME record.

Example for `slxh.nl` which has a DNAME to `slxh.eu`: `dig +dnssec -t A mail.slxh.nl`

### Expected behaviour

The recursor returns the DNAME record, the synthesized CNAME and the response for the CNAME target. For the example above, this would be the same A record as `mail.slxh.eu`.

### Actual behaviour

The recursor returns SERVFAIL.

### Other information

Relevant bit of the trace for `www.slxh.nl`:

```
[1] www.slxh.nl: Got 6 answers from ns1.slxh.eu (<snip>), rcode=0 (No Error), aa=1, in 7ms
[1] www.slxh.nl: accept answer 'slxh.nl|RRSIG|DNAME 13 2 86400 20180315000000 20180222000000 48322 slxh.nl. SdNc6GsKtT7Q+e4Jgp0eZElvcATfhr71qafD6FoOPqyuOBGk4ATSQLDu51sRLRZQYGgUAdVZZAi7hxAeU90rHg==' from 'slxh.nl' nameservers? ttl=86400, place=1 RRSIG - separate
[1] www.slxh.nl: accept answer 'www.slxh.eu|RRSIG|A 13 3 3600 20180315000000 20180222000000 15594 slxh.eu. T9XkK93kRDFOsxqBPQ7sCiuq79ObgcM7BNfJWFU8/BuC57L8Co4LN79W5xXngLJXGBVges+AgrAdTzYOR3r2NA==' from 'slxh.nl' nameservers? ttl=3600, place=1 NO!
[1] www.slxh.nl: accept answer 'www.slxh.nl|CNAME|www.slxh.eu.' from 'slxh.nl' nameservers? ttl=86400, place=1 YES!
[1] www.slxh.nl: accept answer 'www.slxh.eu|A|<snip> from 'slxh.nl' nameservers? ttl=3600, place=1 NO!
[1] www.slxh.nl: accept answer 'slxh.nl|DNAME|slxh.eu.' from 'slxh.nl' nameservers? ttl=86400, place=1 YES!
[1] www.slxh.nl: OPT answer '.' from 'slxh.nl' nameservers
[1] : got status Secure for name slxh.nl (from slxh.nl)
[1] : got initial zone status Secure for record slxh.nl
[1] : got status Secure for name www.slxh.nl (from slxh.nl)
[1] : got initial zone status Secure for record www.slxh.nl
[1] Validating non-additional record for www.slxh.nl
[1] Bogus!
[1] validation state was Secure, state update is Bogus, validation state is now Bogus
```

Note that the CNAME is followed and validated correctly even though the validation is already bogus:

```
[1] www.slxh.nl: updating validation state for response to www.slxh.nl from Bogus with the state from the CNAME quest: Secure
[1] validation state was Bogus, state update is Secure, validation state is now Bogus
```

### Usecase

Redirect a subtree of the domain name tree in DNS. See [RFC 6672 section 6](https://tools.ietf.org/html/rfc6672#section-6).

### Description

Validate the DNAME record correctly as specified by RFC 6676.
This can be performed by validating the DNAME and synthesizing the CNAME on successful validation (the included CNAME can be compared or ignored).

### PR DESCRIPTION
**Pull request by pieterlexis**
### Short description
With this, the recursor understands DNAME records and can synthesize CNAME records based on DNAMEs in the cache. This was dubbed by @Habbie as "aggressive DNAME caching".

This PR has been opened for early review.

Intends to close #6318

#### TODO

- [x] CNAME check from auth
- [ ] DNAME chains test
- [x] DNAME CNAME chains test
- [ ] Make the negative cache aware of DNAME as described in RFC 6672 section 5.3
- [ ] The wildcards and DNAME (SHOULD NOT in the RFC, but you know how the internet is)
- [x] De-duplicate codepaths for DNAME and CNAME as much as possible
- [x] End to End regression tests

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled and tested this code
- [ ] included documentation (including possible behaviour changes)
- [x] documented the code
- [ ] added or modified regression test(s)
- [x] added or modified unit test(s)

### CODE REVIEW

File: pdns/recursordist/test-syncres_cc.cc [hunk 1]
```diff
@@ -10226,6 +10226,795 @@ BOOST_AUTO_TEST_CASE(test_getDSRecords_multialgo_prefer_gost_over_sha1) {
...
+        setLWResult(res, 0, true, false, true);
+        addRecordToLW(res, "host.unsigned.", QType::A, "192.0.2.3", DNSResourceRecord::ANSWER, 3600);
+        return 1;
+      }
+      return 0;
+    });
+
+  vector<DNSRecord> ret;
+  int res = sr->beginResolve(qname, QType(QType::A), QClass::IN, ret);
+  BOOST_CHECK_EQUAL(res, RCode::NoError);
```
Comment (rgacogne) [inline pdns/recursordist/test-syncres_cc.cc]: Perhaps we should check the validation status explicitly:
```
BOOST_CHECK_EQUAL(sr->getValidationState(), Secure);
```

File: pdns/syncres.cc [hunk 2]
```diff
@@ -880,6 +885,129 @@ DNSName SyncRes::getBestNSNamesFromCache(const DNSName &qname, const QType& qtyp
...
+    return true;
+  }
+
+  vector<DNSRecord> dset;
+  vector<std::shared_ptr<RRSIGRecordContent>> dsignatures;
+  vector<std::shared_ptr<DNSRecord>> dauthorityRecs;
+  bool wasAuth;
+
+  auto labels = qname.getRawLabels();
+  DNSName dnameName(g_rootdnsname);
```
Comment (rgacogne) [inline pdns/syncres.cc]: We are unlikely to find a `DNAME` for the root, so perhaps we could skip it?

File: pdns/syncres.cc [hunk 3]
```diff
@@ -880,6 +885,129 @@ DNSName SyncRes::getBestNSNamesFromCache(const DNSName &qname, const QType& qtyp
...
+        DNSName subdomain(dnameName);
+        /* if we are retrieving a DS, we only care about the state of the parent zone */
+        if(qtype == QType::DS)
+          subdomain.chopOff();
+
+        computeZoneCuts(subdomain, g_rootdnsname, depth);
+
+        vState recordState = getValidationStatus(dnameName, false);
+        if (recordState == Secure) {
+          LOG(prefix<<qname<<": got Indeterminate state from the CNAME cache, validating.."<<endl);
```
Comment (rgacogne) [inline pdns/syncres.cc]: s/CNAME/DNAME/

File: pdns/syncres.cc [hunk 4]
```diff
@@ -880,6 +885,129 @@ DNSName SyncRes::getBestNSNamesFromCache(const DNSName &qname, const QType& qtyp
...
+          state = SyncRes::validateRecordsWithSigs(depth, dnameName, QType(QType::DNAME), dnameName, dset, dsignatures);
+          if (state != Indeterminate) {
+            LOG(prefix<<qname<<": got Indeterminate state from the CNAME cache, new validation result is "<<vStates[state]<<endl);
```
Comment (rgacogne) [inline pdns/syncres.cc]: s/CNAME/DNAME/

File: pdns/syncres.cc [hunk 5]
```diff
@@ -880,6 +885,129 @@ DNSName SyncRes::getBestNSNamesFromCache(const DNSName &qname, const QType& qtyp
...
+        ret.push_back(authDR);
+      }
+
+      if (qtype == QType::DNAME && qname == dnameName) {
+        res = 0;
+        return true;
+      }
+
+      // Synthesize a CNAME
+      auto dnameSuffix = getRR<DNAMERecordContent>(record)->d_content;
```
Comment (rgacogne) [inline pdns/syncres.cc]: `getRR()` might return `nullptr`.

File: pdns/syncres.cc [hunk 6]
```diff
@@ -2117,11 +2255,22 @@ RCode::rcodes_ SyncRes::updateCacheFromRecords(unsigned int depth, LWResult& lwr
...
-              recordState = Indeterminate;
+            /*
+             * RFC 6672 section 5.3.1
+             *  In any response, a signed DNAME RR indicates a non-terminal
+             *  redirection of the query.  There might or might not be a server-
+             *  synthesized CNAME in the answer section; if there is, the CNAME will
+             *  never be signed.  For a DNSSEC validator, verification of the DNAME
+             *  RR and then that the CNAME was properly synthesized is sufficient
+             *  proof.
+             */
```
Comment (rgacogne) [inline pdns/syncres.cc]: So we don't really validate that the `CNAME` was properly synthesized below, we fix it if it wasn't. Is that the correct behavior?

File: pdns/syncres.cc [hunk 7]
```diff
@@ -2383,6 +2547,23 @@ bool SyncRes::processRecords(const std::string& prefix, const DNSName& qname, co
...
+  if (!dnameTarget.empty() && !newtarget.empty()) {
+    DNSName substTarget = qname.makeRelative(dnameOwner) + dnameTarget;
+    if (substTarget != newtarget) {
+      LOG("Received wrong DNAME substitution. qname='" + qname.toLogString() +
+          "', DNAME owner='" + dnameOwner.toLogString() + "', DNAME target='" + dnameTarget.toLogString() +
+          "', received CNAME='" + newtarget.toLogString() + "', substituted CNAME='" + substTarget.toLogString() + "'");
+      // Fix the CNAME
+      for (auto& r: ret) {
+        if (r.d_name == qname && r.d_type == QType::CNAME) {
+          r.d_content = std::make_shared<CNAMERecordContent>(CNAMERecordContent(substTarget));
```
Comment (rgacogne) [inline pdns/syncres.cc]: s/std::make_shared<CNAMERecordContent>(CNAMERecordContent(substTarget));/std::make_shared<CNAMERecordContent>(substTarget);

File: pdns/syncres.cc (hunk 6 above)
Comment (pieterlexis) [reply pdns/syncres.cc]: RFC 6672 section 3.4.1 "Resolver Algorithm", in step 4 "Analyze the response"

>        D.  If the response shows a DNAME and that is not the answer
           itself, cache the DNAME (upon successful DNSSEC validation if
           the client is a validating resolver).  If substitution of the
           DNAME's target name for its owner name in the SNAME would
           overflow the legal size for a domain name, return an
           implementation-dependent error to the application; otherwise,
           perform the substitution and go to step 1.

Comment (pieterlexis) [reply pdns/syncres.cc]: Ans it looks like we expect the CNAME to be in the response, I'll fix that as well

File: pdns/syncres.cc (hunk 7 above)
Comment (pieterlexis) [reply pdns/syncres.cc]:
```
error: no matching function for call to ‘make_shared(DNSName&)’
```

File: pdns/recursordist/test-syncres_cc.cc [hunk 8]
```diff
@@ -10792,6 +10792,238 @@ BOOST_AUTO_TEST_CASE(test_records_sanitization_scrubs_ns_nxd) {
...
+  // Now check the cache
+  ret.clear();
+  res = sr->beginResolve(target, QType(QType::A), QClass::IN, ret);
+
+  BOOST_CHECK_EQUAL(res, RCode::NoError);
+  BOOST_REQUIRE_EQUAL(ret.size(), 3);
+
+  BOOST_CHECK_EQUAL(queries, 4);
+
+  BOOST_CHECK(ret[0].d_type == QType::DNAME);
```
Comment (rgacogne) [inline pdns/recursordist/test-syncres_cc.cc]: Same.

File: pdns/recursordist/test-syncres_cc.cc [hunk 9]
```diff
@@ -10792,6 +10792,238 @@ BOOST_AUTO_TEST_CASE(test_records_sanitization_scrubs_ns_nxd) {
...
+          return 1;
+        }
+        if (domain == target && type == QType::DS) { // dname.powerdns|DS
+          return genericDSAndDNSKEYHandler(res, domain, dnameOwner, type, keys);
+        }
+        if (domain == target) {
+          setLWResult(res, 0, true, false, false);
+          addRecordToLW(res, dnameOwner, QType::DNAME, dnameTarget.toString());
+          addRRSIG(keys, res->d_records, dnameOwner, 300);
+          addRecordToLW(res, domain, QType::CNAME, cnameTarget.toString());
```
Comment (rgacogne) [inline pdns/recursordist/test-syncres_cc.cc]: Perhaps we might add a comment stating that the CNAME is not signed on purpose?

File: pdns/recursordist/test-syncres_cc.cc [hunk 10]
```diff
@@ -10792,6 +10792,238 @@ BOOST_AUTO_TEST_CASE(test_records_sanitization_scrubs_ns_nxd) {
...
+  vector<DNSRecord> ret;
+  int res = sr->beginResolve(target, QType(QType::A), QClass::IN, ret);
+
+  BOOST_CHECK_EQUAL(res, RCode::NoError);
+  BOOST_CHECK_EQUAL(sr->getValidationState(), Secure);
+  BOOST_REQUIRE_EQUAL(ret.size(), 5); /* DNAME + RRSIG(DNAME) + CNAME + A + RRSIG(A) */
+
+  BOOST_CHECK_EQUAL(queries, 11);
+
+  BOOST_CHECK(ret[0].d_type == QType::DNAME);
```
Comment (rgacogne) [inline pdns/recursordist/test-syncres_cc.cc]: require

File: pdns/recursordist/test-syncres_cc.cc [hunk 11]
```diff
@@ -10792,6 +10792,238 @@ BOOST_AUTO_TEST_CASE(test_records_sanitization_scrubs_ns_nxd) {
...
+  ret.clear();
+  res = sr->beginResolve(target, QType(QType::A), QClass::IN, ret);
+
+  BOOST_CHECK_EQUAL(res, RCode::NoError);
+  BOOST_CHECK_EQUAL(sr->getValidationState(), Secure);
+  BOOST_REQUIRE_EQUAL(ret.size(), 5); /* DNAME + RRSIG(DNAME) + CNAME + A + RRSIG(A) */
+
+  BOOST_CHECK_EQUAL(queries, 11);
+
+  BOOST_CHECK(ret[0].d_type == QType::DNAME);
```
Comment (rgacogne) [inline pdns/recursordist/test-syncres_cc.cc]: require

File: pdns/syncres.cc [hunk 12]
```diff
@@ -1002,25 +1031,54 @@ bool SyncRes::doCNAMECacheCheck(const DNSName &qname, const QType &qtype, vector
           ret.push_back(authDR);
         }
 
-        if(qtype != QType::CNAME) { // perhaps they really wanted a CNAME!
-          set<GetBestNSAnswer>beenthere;
+        DNSName newTarget;
+        if (foundQT == QType::DNAME) {
+          if (qtype == QType::DNAME && qname == foundName) { // client wanted the DNAME, no need to synthesize a CNAME
```
[the remark this answers is not in the document]
Comment (pieterlexis) [reply pdns/syncres.cc]: No, we look for the exact DNAME only if the user wants the DNAME, as this is a valid config:

```
a IN DNAME b
a IN A 192.0.2.0
```

File: pdns/syncres.cc [hunk 13]
```diff
@@ -2337,6 +2404,10 @@ RCode::rcodes_ SyncRes::updateCacheFromRecords(unsigned int depth, LWResult& lwr
       expectSignature = false;
     }
 
+    if (isDNAMEAnswer && !isAA && i->first.place == DNSResourceRecord::ANSWER && i->first.type == QType::DNAME && qname.isPartOf(i->first.name)) {
+      isAA = true;
```
[the remark this answers is not in the document]
Comment (pieterlexis) [reply pdns/syncres.cc]: you're right, must be a brainfart :)

File: pdns/syncres.cc [hunk 14]
```diff
@@ -2366,11 +2437,25 @@ RCode::rcodes_ SyncRes::updateCacheFromRecords(unsigned int depth, LWResult& lwr
...
-              recordState = Indeterminate;
+            /*
+             * RFC 6672 section 5.3.1
+             *  In any response, a signed DNAME RR indicates a non-terminal
+             *  redirection of the query.  There might or might not be a server-
+             *  synthesized CNAME in the answer section; if there is, the CNAME will
+             *  never be signed.  For a DNSSEC validator, verification of the DNAME
+             *  RR and then that the CNAME was properly synthesized is sufficient
+             *  proof.
+             *
```
[the remark this answers is not in the document]
Comment (pieterlexis) [reply pdns/syncres.cc]: ha, I thought I had that code. Will add CNAME synthesis to `processRecords`.

**Comment by pieterlexis** [comment]
Build failure unrelated to changes. Could use another review

File: pdns/recursordist/test-syncres_cc.cc [hunk 15]
```diff
@@ -10792,6 +10792,428 @@ BOOST_AUTO_TEST_CASE(test_records_sanitization_scrubs_ns_nxd) {
...
+          setLWResult(res, 0, false, false, true);
+          addRecordToLW(res, dnameTarget, QType::NS, "b.gtld-servers.net.", DNSResourceRecord::AUTHORITY, 172800);
+          addRecordToLW(res, "b.gtld-servers.net.", QType::A, "192.0.2.2", DNSResourceRecord::ADDITIONAL, 3600);
+          return 1;
+        }
+      } else if (ip == ComboAddress("192.0.2.1:53")) {
+        if (domain == target) {
+          setLWResult(res, 0, true, false, false);
+          addRecordToLW(res, dnameOwner, QType::DNAME, dnameTarget.toString());
+          addRecordToLW(res, domain, QType::CNAME, cnameTarget.toString());
```
Comment (rgacogne) [inline pdns/recursordist/test-syncres_cc.cc]: It might be nice to have another test checking what happens if the `CNAME` is not present?

File: pdns/syncres.cc [hunk 16]
```diff
@@ -2513,10 +2606,33 @@ bool SyncRes::processRecords(const std::string& prefix, const DNSName& qname, co
...
       negindic=true;
     }
-    else if(rec.d_place==DNSResourceRecord::ANSWER && rec.d_type==QType::CNAME && (!(qtype==QType(QType::CNAME))) && rec.d_name == qname) {
-      ret.push_back(rec);
-      if (auto content = getRR<CNAMERecordContent>(rec)) {
-        newtarget=content->getTarget();
+    else if(rec.d_place==DNSResourceRecord::ANSWER && s_redirectionQTypes.count(rec.d_type) > 0 && // CNAME or DNAME answer
+        s_redirectionQTypes.count(qtype.getCode()) == 0) { // But not in response to a CNAME or DNAME query
+      if (rec.d_type == QType::CNAME && rec.d_name == qname) {
+        if (!dnameOwner.empty()) { // We synthesize ourselves
```
Comment (rgacogne) [inline pdns/syncres.cc]: What happens if the `CNAME` is present in the answer _before_ the `DNAME`? Aren't we going to send an answer with the original `CNAME`, the original `DNAME` then a synthesized `CNAME`?

Comment (pieterlexis) [reply pdns/syncres.cc]: yes, that would happen then. We could keep track of this and don't synthesize, but this also feels.... dirty

File: pdns/recursordist/test-syncres_cc.cc [hunk 17]
```diff
@@ -10792,6 +10792,428 @@ BOOST_AUTO_TEST_CASE(test_records_sanitization_scrubs_ns_nxd) {
...
+
+  BOOST_CHECK(ret[2].d_type == QType::CNAME);
+  BOOST_CHECK_EQUAL(ret[2].d_name, target);
+
+  BOOST_CHECK(ret[3].d_type == QType::A);
+  BOOST_CHECK_EQUAL(ret[3].d_name, cnameTarget);
+
+  BOOST_CHECK(ret[4].d_type == QType::RRSIG);
+  BOOST_CHECK_EQUAL(ret[4].d_name, cnameTarget);
+
```
[the remark this answers is not in the document]
Comment (pieterlexis) [reply pdns/recursordist/test-syncres_cc.cc]: We do, from line 11054 onward. The CNAME from a DNAME is never cached and always synthesized on a DNAME cache hit.

**Comment by rgacogne** [comment]
Looks good! I see several unchecked boxes in the TODO above, do you intend on fixing them before we merge this?
