### PR TITLE
rec: Initialize OpenSSL before chrooting

### LINKED ISSUE #3994: Recursor validation broken with chroot
in 8d16388f33f0d4ab4fb4016f1243a07f5b0a7cfc

```
Jun 14 18:26:07 Starting validation of answer to powerdns.com. for 127.0.0.1:48681
Jun 14 18:26:07 Got 1 RRSETs: 
Jun 14 18:26:07 Going to validate: powerdns.com./A: 1 sigs for 1 records
Jun 14 18:26:07 .: Wants DNSSEC processing in query for DNSKEY
Jun 14 18:26:07 .: Looking for CNAME cache hit of '.|CNAME'
Jun 14 18:26:07 .: No CNAME cache hit of '.|CNAME' found
Jun 14 18:26:07 .: No cache hit for '.|DNSKEY', trying to find an appropriate NS record
Jun 14 18:26:07 .: Checking if we have NS in cache for '.'
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'g.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'd.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'b.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'm.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'j.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'f.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'k.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'l.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'e.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'a.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'i.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'h.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: NS (with ip, or non-glue) in cache for '.' -> 'c.root-servers.net.'
Jun 14 18:26:07 .: within bailiwick: 1,  in cache, ttl=86388
Jun 14 18:26:07 .: We have NS in cache for '.' (flawedNSSet=0)
Jun 14 18:26:07 .: Cache consultations done, have 13 NS to contact
Jun 14 18:26:07 .: Nameservers: f.root-servers.net.(0.00ms), h.root-servers.net.(0.00ms), i.root-servers.net.(0.00ms), 
Jun 14 18:26:07 .:              a.root-servers.net.(0.00ms), j.root-servers.net.(0.00ms), l.root-servers.net.(0.00ms), 
Jun 14 18:26:07 .:              d.root-servers.net.(0.00ms), k.root-servers.net.(0.00ms), e.root-servers.net.(0.00ms), 
Jun 14 18:26:07 .:              g.root-servers.net.(0.00ms), b.root-servers.net.(0.00ms), c.root-servers.net.(22.35ms), 
Jun 14 18:26:07 .:              m.root-servers.net.(27.91ms)
Jun 14 18:26:07 .: Trying to resolve NS 'f.root-servers.net.' (1/13)
Jun 14 18:26:07    f.root-servers.net.: Wants DNSSEC processing in query for A
Jun 14 18:26:07    f.root-servers.net.: Looking for CNAME cache hit of 'f.root-servers.net.|CNAME'
Jun 14 18:26:07    f.root-servers.net.: No CNAME cache hit of 'f.root-servers.net.|CNAME' found
Jun 14 18:26:07    f.root-servers.net.: Found cache hit for A: 192.5.5.241[ttl=86388] 
Jun 14 18:26:07 .: Resolved '.' NS f.root-servers.net. to: 192.5.5.241
Jun 14 18:26:07 .: Trying IP 192.5.5.241:53, asking '.|DNSKEY'
Jun 14 18:26:08 .: Got 4 answers from f.root-servers.net. (192.5.5.241), rcode=0 (No Error), aa=1, in 116ms
Jun 14 18:26:08 .: accept answer '.|DNSKEY|256 3 8 AwEAAarQO0FTE/l6LEKFlZllJIwXuLGd3q5d8S8NH+ntOeIMN81A5wAI18g3u9w/esNkThwgXTEa2mX1iOPdTcl3yRleAExxF22lEU2E0GKY2XdYr/BxP5fojJAPRgtEGDl72NSwSnD2/a8uPNirAJZoab36Hlw41QxEl7bmCo0280mt' from '.' nameservers? 1 YES!
Jun 14 18:26:08 .: accept answer '.|DNSKEY|257 3 8 AwEAAagAIKlVZrpC6Ia7gEzahOR+9W29euxhJhVVLOyQbSEW0O8gcCjFFVQUTf6v58fLjwBd0YI0EzrAcQqBGCzh/RStIoO8g0NfnfL2MTJRkxoXbfDaUeVPQuYEhg37NZWAJQ9VnMVDxP/VHL496M/QZxkjf5/Efucp2gaDX6RS6CXpoY68LsvPVjR0ZSwzz1apAzvN9dlzEheX7ICJBBtuA6G3LQpzW5hOA2hzCTMjJPJ8LbqF6dsV6DoBQzgul0sGIcGOYl7OyQdXfZ57relSQageu+ipAdTTJ25AsRTAoub8ONGcLmqrAmRLKBP1dfwhYB4N7knNnulqQxA+Uk1ihz0=' from '.' nameservers? 1 YES!
Jun 14 18:26:08 .: accept answer '.|RRSIG|DNSKEY 8 0 172800 20160624235959 20160610000000 19036 . NxwsGY7wP9IC4+wcBi7fnUyBbRcExyDEIa0ITrkaqVQ0BodrMPa+MTpblSdraHUjltaTLQ+lDByG5jAjHDcn8bGVSKGUqShw7EOdYd6WpmMWOd8KcBatoGnvn6/tWslfUAY/h8BxtiPQziVIR7Cz6ue6DaiklKHa5ckZkmhQSmra7vI8IJ88RT/kC9ljCc+oQgBCfHRKrBdZw3Bj6ZWqy3/IIvckcFLa8N9uIxEAqGULmmFlalv7KdfI1vNAdI4n1qmnlCSIJevW4RXUFlGP+eTuGBuNsQ1Sik7On+n/9Ea4u6KARArj4hgQ6sGcfAPBDF2vuRPjQkE0XBZKYcY7yg==' from '.' nameservers? 1 RRSIG - separate
Jun 14 18:26:08 .: OPT answer '.' from '.' nameservers
Jun 14 18:26:08 .: determining status after receiving this packet
Jun 14 18:26:08 .: answer is in: resolved to '256 3 8 AwEAAarQO0FTE/l6LEKFlZllJIwXuLGd3q5d8S8NH+ntOeIMN81A5wAI18g3u9w/esNkThwgXTEa2mX1iOPdTcl3yRleAExxF22lEU2E0GKY2XdYr/BxP5fojJAPRgtEGDl72NSwSnD2/a8uPNirAJZoab36Hlw41QxEl7bmCo0280mt|DNSKEY'
Jun 14 18:26:08 .: answer is in: resolved to '257 3 8 AwEAAagAIKlVZrpC6Ia7gEzahOR+9W29euxhJhVVLOyQbSEW0O8gcCjFFVQUTf6v58fLjwBd0YI0EzrAcQqBGCzh/RStIoO8g0NfnfL2MTJRkxoXbfDaUeVPQuYEhg37NZWAJQ9VnMVDxP/VHL496M/QZxkjf5/Efucp2gaDX6RS6CXpoY68LsvPVjR0ZSwzz1apAzvN9dlzEheX7ICJBBtuA6G3LQpzW5hOA2hzCTMjJPJ8LbqF6dsV6DoBQzgul0sGIcGOYl7OyQdXfZ57relSQageu+ipAdTTJ25AsRTAoub8ONGcLmqrAmRLKBP1dfwhYB4N7knNnulqQxA+Uk1ihz0=|DNSKEY'
Jun 14 18:26:08 .: status=got results, this level of recursion done
Jun 14 18:26:08 DNSKEY did not match the DS, parent DS: 257 3 8 AwEAAagAIKlVZrpC6Ia7gEzahOR+9W29euxhJhVVLOyQbSEW0O8gcCjFFVQUTf6v58fLjwBd0YI0EzrAcQqBGCzh/RStIoO8g0NfnfL2MTJRkxoXbfDaUeVPQuYEhg37NZWAJQ9VnMVDxP/VHL496M/QZxkjf5/Efucp2gaDX6RS6CXpoY68LsvPVjR0ZSwzz1apAzvN9dlzEheX7ICJBBtuA6G3LQpzW5hOA2hzCTMjJPJ8LbqF6dsV6DoBQzgul0sGIcGOYl7OyQdXfZ57relSQageu+ipAdTTJ25AsRTAoub8ONGcLmqrAmRLKBP1dfwhYB4N7knNnulqQxA+Uk1ihz0= ! = 0 0 0 -
Jun 14 18:26:08 ended up with zero valid DNSKEYs, going Bogus
Jun 14 18:26:08 ! state = Bogus, now have 0 keys
Jun 14 18:26:08 Answer to powerdns.com. for 127.0.0.1:48681 validates as Bogus
Jun 14 18:26:08 Sending out SERVFAIL for powerdns.com. because recursor or query demands it for Bogus results
Jun 14 18:26:08 2 [1/1] answer to question 'powerdns.com.|A': 0 answers, 0 additional, took 3 packets, 158.999 ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=0
```

`pdns_recursor --local-port=5300 --chroot=/tmp/pdns-chroot --socket-dir=. --dnssec=validate --trace`

This was reported on IRC by rcmc-ronny

### PR DESCRIPTION
**Pull request by pieterlexis**
When chroot()'ing into a 'bare' directory, /dev/random is not available.
This means that OpenSSL cannot gather randomness and all validations
will fail.

Closes #3994

### CODE REVIEW

File: pdns/pdns_recursor.cc [hunk 1]
```diff
@@ -2566,6 +2567,9 @@ int serviceMain(int argc, char*argv[])
 
   showProductVersion();
   seedRandom(::arg()["entropy-source"]);
+  openssl_thread_setup();
+  openssl_seed();
```
Comment (rgacogne) [inline pdns/pdns_recursor.cc]: We should call `openssl_seed()` after `fork()`, if I'm not mistaken: https://wiki.openssl.org/index.php/Random_fork-safety

Comment (pieterlexis) [inline pdns/pdns_recursor.cc]: I don't believe we need the randomness anyway when only verifying signatures (although something about ecc is nagging in the back of my mind)

Comment (rgacogne) [inline pdns/pdns_recursor.cc]: You are right, but I'm worried about what is going to happen when/if one day we use openssl for something else that verifying signatures :-)

Comment (Habbie) [inline pdns/pdns_recursor.cc]: That nagging on the back of your mind is the stuff deterministic ECDSA fixes. Our core randomness need for openssl is generating keys, which indeed we do not do today in the recursor, but let's get this right from the start :)

**Comment by pieterlexis** [comment]
could use another quick once-over
