### PR TITLE
Rec: systemd-journal structured logging followup

### LINKED ISSUE #11705: rec: Task queue(?) logging "resolving" and "done"
- Program: Recursor
 - Issue type: Bug report

### Short description
I upgraded Recursor master and now it's frequently logging "`resolving`" and "`done`". I'm guessing it's coming from the task queue system (fetching nameserver `AAAA` records) but it's hard to be sure. (I can't just grep the codebase for "done"...)

I only have `log-common-errors` and otherwise default logging, so this is surprising. And without further detail, it's borderline useless.

### Environment
 - Operating system: Ubuntu 20.04 (amd64)
 - Software version: 4.8.0~alpha0+master.335.g86727d60b-1pdns.focal
 - Software source: PowerDNS repository

I was previously using 4.8.0~alpha0+master.255.gf049f691b-1pdns.focal.

### Steps to reproduce
1. Install?
2. Maybe enable `log-common-errors`?
3. `dig mattnordhoff.net` or something that will result in `AAAA` tasks

### Expected behaviour
No logging

### Actual behaviour
```
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: resolving
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: resolving
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: done
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: resolving
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: done
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: resolving
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: done
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: resolving
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: done
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: resolving
Jun 17 14:22:55 ultimate pdns_recursor[2734553]: done
Jun 17 14:22:56 ultimate pdns_recursor[2734553]: message repeated 3 times: [ done]
```

### Other information
```
$ sudo rg -vN '^(#|$)' /etc/powerdns/recursor.conf
aggressive-nsec-cache-size=10000
allow-from=100.64.0.0/10, 127.0.0.0/8, ::1/128, 2600:3c02::f03c:91ff:fe70:fd08/128, 2600:3c02::f03c:91ff:febc:a28b/128, 2600:3c02::f03c:92ff:fefd:f09a/128, 2600:3c02:e000:74::/64, 2600:3c02:e000:bc::/64, 2600:3c02:e001:1d00::/56, fd7a:115c:a1e0::/48
allow-trust-anchor-query
any-to-tcp
carbon-ourname=ultimate_mattnordhoff_net
carbon-server=2a02:2770:8::2635:0:1
config-dir=/etc/powerdns
dnssec=validate
dnssec-log-bogus
edns-padding-from=100.64.0.0/10, fd7a:115c:a1e0::/48
edns-padding-mode=always
extended-resolution-errors
forward-zones=82.100.in-addr.arpa=2600:3c02:e000:74::53a:1, 83.100.in-addr.arpa=2600:3c02:e000:74::53a:1, 98.100.in-addr.arpa=2600:3c02:e000:74::53a:1, 122.100.in-addr.arpa=2600:3c02:e000:74::53a:1, d.f.ip6.arpa=2600:3c02:e000:74::53a:1
hint-file=/usr/share/dns/root.hints
include-dir=/etc/powerdns/recursor.d
local-address=100.82.87.107, 127.0.0.1, ::1, 2600:3c02:e000:74::53c:0, fd7a:115c:a1e0:ab12:4843:cd96:6252:576b
log-common-errors
lua-config-file=/etc/powerdns/recursor.lua
max-cache-entries=100000
max-cache-ttl=172800
max-negative-ttl=10800
max-packetcache-entries=50000
non-local-bind
query-local-address=0.0.0.0, ::
quiet=yes
refresh-on-ttl-perc=10
setgid=pdns
setuid=pdns
tcp-fast-open-connect
threads=1
udp-source-port-avoid=11211,41641
udp-truncation-threshold=1452
```

### LINKED ISSUE #11706: Recursor startup logging missing details
- Program: Recursor
 - Issue type: Bug report

### Short description
I upgraded Recursor master and the startup logging lost all detail. For example it repeatedly logs "Listening for queries" but not what IPs or ports it's listening on.

See also #11705.

### Environment
 - Operating system: Ubuntu 20.04 (amd64)
 - Software version: 4.8.0~alpha0+master.335.g86727d60b-1pdns.focal
 - Software source: PowerDNS repository

I was previously using 4.8.0~alpha0+master.255.gf049f691b-1pdns.focal.

### Steps to reproduce
1. Install?
2. Maybe enable `log-common-errors`?

### Expected behaviour
Detailed logging similar to or the same as what it was before

### Actual behaviour
`syslog` shows:
```
Jun 17 14:21:24 ultimate pdns-recursor[2734553]: PowerDNS Recursor 4.8.0-alpha0.335.master.g86727d60b (C) 2001-2022 PowerDNS.COM BV
Jun 17 14:21:24 ultimate pdns-recursor[2734553]: Using 64-bits mode. Built using gcc 9.4.0 on Jun 17 2022 11:58:38 by root@01cab996a69e.
Jun 17 14:21:24 ultimate pdns-recursor[2734553]: PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: If using IPv6, please raise sysctl net.ipv6.route.max_size to a size >= 16384
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Enabling IPv4 transport for outgoing queries
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Enabling IPv6 transport for outgoing queries
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Read Trust Anchors from file, no changes detected
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Setting access control
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Will not send queries to
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Redirecting queries
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: message repeated 4 times: [ Redirecting queries]
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Inserting rfc 1918 private space zones
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Listening for queries
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: message repeated 4 times: [ Listening for queries]
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Enabled TCP data-ready filter for (slight) DoS protection
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Listening for queries
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: message repeated 4 times: [ Listening for queries]
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Operating with single distributor/worker thread
Jun 17 14:21:24 ultimate pdns_recursor[2734553]: Done priming cache with root hints
Jun 17 14:21:25 ultimate pdns_recursor[2734553]: Enabled multiplexer
Jun 17 14:21:25 ultimate systemd[1]: Started PowerDNS Recursor.
Jun 17 14:21:25 ultimate pdns_recursor[2734553]: Refreshed . records
Jun 17 14:21:26 ultimate pdns_recursor[2734553]: Not validating response for security status update, this is a non-release version
Jun 17 14:21:27 ultimate systemd[1]: Reloading.
```

### Other information
```
$ sudo rg -vN '^(#|$)' /etc/powerdns/recursor.conf
aggressive-nsec-cache-size=10000
allow-from=100.64.0.0/10, 127.0.0.0/8, ::1/128, 2600:3c02::f03c:91ff:fe70:fd08/128, 2600:3c02::f03c:91ff:febc:a28b/128, 2600:3c02::f03c:92ff:fefd:f09a/128, 2600:3c02:e000:74::/64, 2600:3c02:e000:bc::/64, 2600:3c02:e001:1d00::/56, fd7a:115c:a1e0::/48
allow-trust-anchor-query
any-to-tcp
carbon-ourname=ultimate_mattnordhoff_net
carbon-server=2a02:2770:8::2635:0:1
config-dir=/etc/powerdns
dnssec=validate
dnssec-log-bogus
edns-padding-from=100.64.0.0/10, fd7a:115c:a1e0::/48
edns-padding-mode=always
extended-resolution-errors
forward-zones=82.100.in-addr.arpa=2600:3c02:e000:74::53a:1, 83.100.in-addr.arpa=2600:3c02:e000:74::53a:1, 98.100.in-addr.arpa=2600:3c02:e000:74::53a:1, 122.100.in-addr.arpa=2600:3c02:e000:74::53a:1, d.f.ip6.arpa=2600:3c02:e000:74::53a:1
hint-file=/usr/share/dns/root.hints
include-dir=/etc/powerdns/recursor.d
local-address=100.82.87.107, 127.0.0.1, ::1, 2600:3c02:e000:74::53c:0, fd7a:115c:a1e0:ab12:4843:cd96:6252:576b
log-common-errors
lua-config-file=/etc/powerdns/recursor.lua
max-cache-entries=100000
max-cache-ttl=172800
max-negative-ttl=10800
max-packetcache-entries=50000
non-local-bind
query-local-address=0.0.0.0, ::
quiet=yes
refresh-on-ttl-perc=10
setgid=pdns
setuid=pdns
tcp-fast-open-connect
threads=1
udp-source-port-avoid=11211,41641
udp-truncation-threshold=1452
```

### PR DESCRIPTION
**Pull request by omoerbeek**
### Short description

As @mnordhoff noted, the new systemd-journal backend isn't nice for human consumption. So switch back to the row of `k=v` pairs output by default and introduce a setting to use the systemd-journal backend. This setting also allows for other backends to be used (in the future).

Also: respect loglevel. The traditional output was filtered, but for structured logging, that was not done. While there, shortcut the traditional way as well, to avoid unnecessary churn.

Should fix #11705 and #11706

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [X] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

### CODE REVIEW

File: pdns/recursordist/rec-main.cc [hunk 1]
```diff
@@ -2782,16 +2793,17 @@ int main(int argc, char** argv)
...
+    s_logUrgency = (Logger::Urgency)::arg().asNum("loglevel");
     g_slogStructured = ::arg().mustDo("structured-logging");
+    s_structured_logger_backend = ::arg()["structured-logging-backend"];
 
-    if (logUrgency < Logger::Error)
-      logUrgency = Logger::Error;
-    if (!g_quiet && logUrgency < Logger::Info) { // Logger::Info=6, Logger::Debug=7
-      logUrgency = Logger::Info; // if you do --quiet=no, you need Info to also see the query log
+    if (s_logUrgency < Logger::Error)
+      s_logUrgency = Logger::Error;
```
Comment (fredmorcos) [inline pdns/recursordist/rec-main.cc:2801]: `{` and `}` are missing.

File: pdns/recursordist/rec-main.cc [hunk 2]
```diff
@@ -2847,16 +2863,16 @@ int main(int argc, char** argv)
...
-    logUrgency = (Logger::Urgency)::arg().asNum("loglevel");
+    s_logUrgency = (Logger::Urgency)::arg().asNum("loglevel");
     g_slogStructured = ::arg().mustDo("structured-logging");
 
-    if (logUrgency < Logger::Error)
-      logUrgency = Logger::Error;
-    if (!g_quiet && logUrgency < Logger::Info) { // Logger::Info=6, Logger::Debug=7
-      logUrgency = Logger::Info; // if you do --quiet=no, you need Info to also see the query log
+    if (s_logUrgency < Logger::Error)
+      s_logUrgency = Logger::Error;
```
Comment (fredmorcos) [inline pdns/recursordist/rec-main.cc:2870]: `{` and `}` are missing.

File: pdns/recursordist/rec-main.cc [hunk 3]
```diff
@@ -885,6 +887,10 @@ static const char* toTimestampStringMilli(const struct timeval& tv, char* buf, s
 #ifdef HAVE_SYSTEMD
 static void loggerSDBackend(const Logging::Entry& entry)
 {
+  Logger::Urgency u = entry.d_priority ? Logger::Urgency(entry.d_priority) : Logger::Info;
+  if (u > s_logUrgency) {
+    return;
+  }
```
Comment (fredmorcos) [inline pdns/recursordist/rec-main.cc:893]: Perhaps a comment of what's happening here could be helpful: "We don't need to log anything if the log level is at a higher urgency than the user-requested level".

File: pdns/recursordist/rec-main.cc [hunk 4]
```diff
@@ -922,6 +928,10 @@ static void loggerBackend(const Logging::Entry& entry)
 {
   static thread_local std::stringstream buf;
 
+  Logger::Urgency u = entry.d_priority ? Logger::Urgency(entry.d_priority) : Logger::Info;
+  if (u > s_logUrgency) {
+    return;
+  }
```
Comment (fredmorcos) [inline pdns/recursordist/rec-main.cc:934]: Perhaps a comment of what's happening here could be helpful: "We don't need to log anything if the log level is at a higher urgency than the user-requested level".

**Review by fredmorcos — APPROVED** [review]
Minor stuff, nothing blocking though.
